import { defineConstruction, CONSTRUCTION_STATUS as S } from '../schemas.js';

export const MODIFIER = [
  defineConstruction({
    id: 'adj-noun-stack',
    family: 'modifier',
    left: 'ADJ', right: 'N', result: 'N', head: 1,
    status: S.APPROXIMATION,
    relation: 'amod',
    construction: 'attributive-adjective',
    roles: { left: 'adjective', right: 'noun' },
    limitation: 'Result typed N not NP so adjectives stack (the old grey man)',
    note: 'UD amod — head is the noun',
    flags: ['stack-hack', 'ud-aligned-head'],
    grades: { C: 'G', R: 'Y', H: 'G', X: 'G' },
  }),
  /**
   * Hint sim nucleus: ADJ+NC→NC. NC port of ADJ+N — keep compound as NC
   * under attributive stacking (old coffee cup).
   */
  defineConstruction({
    id: 'adj-nc-stack',
    family: 'modifier',
    left: 'ADJ', right: 'NC', result: 'NC', head: 1,
    status: S.APPROXIMATION,
    relation: 'amod',
    construction: 'attributive-adjective-compound',
    roles: { left: 'adjective', right: 'compound-noun' },
    limitation: 'NC port of adj-noun-stack; result stays NC so further compounds stack',
    note: 'Hint nucleus — ADJ on pure-noun compound',
    flags: ['stack-hack', 'ud-aligned-head', 'hint-nucleus', 'nc-port'],
    grades: { C: 'G', R: 'Y', H: 'G', X: 'G' },
  }),
  defineConstruction({
    id: 'adv-adj',
    family: 'modifier',
    left: 'ADV', right: 'ADJ', result: 'ADJ', head: 1,
    status: S.GRAMMAR,
    relation: 'advmod',
    construction: 'degree-adverb-adjective',
    roles: { left: 'adverb', right: 'adjective' },
    note: 'VERY OLD',
    flags: ['ud-aligned'],
  }),
  defineConstruction({
    id: 'adv-vp-pre',
    family: 'modifier',
    left: 'ADV', right: 'VP', result: 'VP', head: 1,
    status: S.APPROXIMATION,
    relation: 'advmod',
    construction: 'preverbal-adverb',
    roles: { left: 'adverb', right: 'verb-phrase' },
    limitation: 'discourse/connective ADV sometimes lands here',
    note: 'QUICKLY RAN',
    flags: [],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'vp-adv-post',
    family: 'modifier',
    left: 'VP', right: 'ADV', result: 'VP', head: 0,
    status: S.GRAMMAR,
    relation: 'advmod',
    construction: 'postverbal-adverb',
    roles: { left: 'verb-phrase', right: 'adverb' },
    note: 'RAN QUICKLY',
    flags: ['ud-aligned'],
  }),
  defineConstruction({
    id: 'np-pp',
    family: 'modifier',
    left: 'NP', right: 'PP', result: 'NP', head: 0,
    status: S.APPROXIMATION,
    relation: 'nmod',
    construction: 'np-pp-attachment',
    roles: { left: 'noun-phrase', right: 'pp' },
    limitation: 'Catalan generator; nmod vs other PP attachments not typed',
    note: 'THE CATALAN GENERATOR (NP side)',
    flags: ['catalan', 'attachment-ambiguous'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'adj-infinitive',
    family: 'modifier',
    left: 'ADJ', right: 'INF', result: 'ADJ', head: 0,
    status: S.GRAMMAR,
    relation: 'xcomp',
    construction: 'adjective-infinitive',
    roles: { left: 'adjective', right: 'infinitive' },
    note: 'likely TO BE true',
    flags: ['ud-aligned'],
  }),
];
