import { defineConstruction, CONSTRUCTION_STATUS as S } from '../schemas.js';

export const PUNCTUATION = [
  defineConstruction({
    id: 'adv-comma-fronted',
    family: 'punctuation',
    left: 'ADV', right: 'COMMA', result: 'FRONTED', head: 0,
    status: S.SCAFFOLD,
    construction: 'fronting-bridge',
    note: 'Parser assembly for fronted adjunct; comma is punct',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'sbar-comma-fronted',
    family: 'punctuation',
    left: 'SBAR', right: 'COMMA', result: 'FRONTED', head: 0,
    status: S.SCAFFOLD,
    construction: 'fronting-bridge',
    note: 'Parser assembly for fronted SBAR',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'pp-comma-fronted',
    family: 'punctuation',
    left: 'PP', right: 'COMMA', result: 'FRONTED', head: 0,
    status: S.SCAFFOLD,
    construction: 'fronting-bridge',
    note: 'Parser assembly for fronted PP',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'fronted-matrix',
    family: 'punctuation',
    left: 'FRONTED', right: 'S', result: 'S', head: 1,
    status: S.GRAMMAR,
    construction: 'comma-fronted-adjunct',
    roles: { left: 'fronted-bridge', right: 'matrix' },
    note: '…, he left — matrix clause is the head',
    flags: ['ud-aligned'],
  }),
  defineConstruction({
    id: 'np-comma-bridge',
    family: 'punctuation',
    left: 'NP', right: 'COMMA', result: 'NPCOMMA', head: 0,
    status: S.SCAFFOLD,
    construction: 'appos-list-bridge',
    note: 'Parser assembly for apposition / listing',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'apposition',
    family: 'punctuation',
    left: 'NPCOMMA', right: 'NP', result: 'APPOS', head: 0,
    status: S.APPROXIMATION,
    relation: 'appos',
    construction: 'apposition',
    roles: { left: 'first-np-bridge', right: 'appositive' },
    limitation: 'APPOS intermediate; list/appos isomer with npcomma-list',
    note: 'UD appos attaches to the FIRST NP',
    flags: ['ud-aligned-head', 'scaffold-result'],
    grades: { C: 'G', R: 'Y', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'appos-close-comma',
    family: 'punctuation',
    left: 'APPOS', right: 'COMMA', result: 'NP', head: 0,
    status: S.SCAFFOLD,
    construction: 'appos-closing-comma',
    note: 'Closing comma absorption',
    flags: ['punct', 'scaffold-path'],
  }),
  defineConstruction({
    id: 'npcomma-list',
    family: 'punctuation',
    left: 'NPCOMMA', right: 'NP', result: 'NP', head: 0,
    status: S.APPROXIMATION,
    construction: 'np-list',
    limitation: 'Apposition and listing are genuinely ambiguous here',
    note: 'the dog , the cat and the man — first conjunct heads',
    flags: ['isomer', 'coordination'],
    grades: { C: 'Y', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 's-comma-bridge',
    family: 'punctuation',
    left: 'S', right: 'COMMA', result: 'SCOMMA', head: 0,
    status: S.SCAFFOLD,
    construction: 'clausal-conj-bridge',
    note: 'Parser assembly for clausal coordination with comma',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'scomma-s',
    family: 'punctuation',
    left: 'SCOMMA', right: 'S', result: 'S', head: 0,
    status: S.APPROXIMATION,
    relation: 'conj',
    construction: 'asymmetric-clausal-sequence',
    limitation: 'Also covers asyndetic sequences; first clause heads per UD conj',
    note: 'he ran , she fell — RULING: first clause heads',
    flags: ['ud-aligned', 'ruling'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'terminal-punct',
    family: 'punctuation',
    left: 'S', right: 'PUNCT', result: 'S', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'sentence-final-punctuation',
    roles: { left: 'clause', right: 'terminal-punct' },
    note: 'Clause absorbs terminal . ! ? ; : (and repeated marks as one PUNCT atom)',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  /**
   * NOMINAL ROOT ABSORB. Web/title fragments root on nouns (`Great electrician.`)
   * with terminal punct outside the NP. Same seatbelt as S+PUNCT: punct is not
   * the skeleton; the NP is. Head stays on the nominal.
   */
  defineConstruction({
    id: 'np-terminal-punct',
    family: 'punctuation',
    left: 'NP', right: 'PUNCT', result: 'NP', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'nominal-final-punctuation',
    roles: { left: 'noun-phrase', right: 'terminal-punct' },
    note: 'NP absorbs terminal punct — seatbelt, not skeleton',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'adj-terminal-punct',
    family: 'punctuation',
    left: 'ADJ', right: 'PUNCT', result: 'ADJ', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'adjectival-final-punctuation',
    roles: { left: 'adjective', right: 'terminal-punct' },
    note: 'Adjectival fragments with terminal punct (seatbelt)',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  /**
   * Hint sim nuclei: punct-absorb parity for bare N and NC.
   * We already absorb on S / NP / ADJ; pure nouns and compounds need the same seatbelt.
   */
  defineConstruction({
    id: 'n-terminal-punct',
    family: 'punctuation',
    left: 'N', right: 'PUNCT', result: 'N', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'noun-final-punctuation',
    roles: { left: 'noun', right: 'terminal-punct' },
    note: 'Hint nucleus — bare N absorbs terminal punct (parity with NP/S/ADJ)',
    flags: ['ud-aligned', 'punct', 'closure', 'hint-nucleus'],
  }),
  defineConstruction({
    id: 'nc-terminal-punct',
    family: 'punctuation',
    left: 'NC', right: 'PUNCT', result: 'NC', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'compound-noun-final-punctuation',
    roles: { left: 'compound-noun', right: 'terminal-punct' },
    note: 'Hint nucleus — NC absorbs terminal punct (parity with N)',
    flags: ['ud-aligned', 'punct', 'closure', 'hint-nucleus'],
  }),
];
