import { defineConstruction, CONSTRUCTION_STATUS as S } from '../schemas.js';

export const PUNCTUATION = [
  defineConstruction({
    id: 'adv-comma-fronted',
    family: 'punctuation',
    left: 'ADV', right: 'COMMA', result: 'FRONTED', head: 0,
    status: S.SCAFFOLD,
    construction: 'fronting-bridge',
    note: 'Parser assembly for fronted adjunct; comma is punct',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'sbar-comma-fronted',
    family: 'punctuation',
    left: 'SBAR', right: 'COMMA', result: 'FRONTED', head: 0,
    status: S.SCAFFOLD,
    construction: 'fronting-bridge',
    note: 'Parser assembly for fronted SBAR',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'pp-comma-fronted',
    family: 'punctuation',
    left: 'PP', right: 'COMMA', result: 'FRONTED', head: 0,
    status: S.SCAFFOLD,
    construction: 'fronting-bridge',
    note: 'Parser assembly for fronted PP',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'fronted-matrix',
    family: 'punctuation',
    left: 'FRONTED', right: 'S', result: 'S', head: 1,
    status: S.GRAMMAR,
    construction: 'comma-fronted-adjunct',
    roles: { left: 'fronted-bridge', right: 'matrix' },
    note: '…, he left — matrix clause is the head',
    flags: ['ud-aligned'],
  }),
  defineConstruction({
    id: 'np-comma-bridge',
    family: 'punctuation',
    left: 'NP', right: 'COMMA', result: 'NPCOMMA', head: 0,
    status: S.SCAFFOLD,
    construction: 'appos-list-bridge',
    note: 'Parser assembly for apposition / listing',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'apposition',
    family: 'punctuation',
    left: 'NPCOMMA', right: 'NP', result: 'APPOS', head: 0,
    status: S.APPROXIMATION,
    relation: 'appos',
    construction: 'apposition',
    roles: { left: 'first-np-bridge', right: 'appositive' },
    limitation: 'APPOS intermediate; list/appos isomer with npcomma-list',
    note: 'UD appos attaches to the FIRST NP',
    flags: ['ud-aligned-head', 'scaffold-result'],
    grades: { C: 'G', R: 'Y', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'appos-close-comma',
    family: 'punctuation',
    left: 'APPOS', right: 'COMMA', result: 'NP', head: 0,
    status: S.SCAFFOLD,
    construction: 'appos-closing-comma',
    note: 'Closing comma absorption',
    flags: ['punct', 'scaffold-path'],
  }),
  defineConstruction({
    id: 'npcomma-list',
    family: 'punctuation',
    left: 'NPCOMMA', right: 'NP', result: 'NP', head: 0,
    status: S.APPROXIMATION,
    construction: 'np-list',
    limitation: 'Apposition and listing are genuinely ambiguous here',
    note: 'the dog , the cat and the man — first conjunct heads',
    flags: ['isomer', 'coordination'],
    grades: { C: 'Y', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 's-comma-bridge',
    family: 'punctuation',
    left: 'S', right: 'COMMA', result: 'SCOMMA', head: 0,
    status: S.SCAFFOLD,
    construction: 'clausal-conj-bridge',
    note: 'Parser assembly for clausal coordination with comma',
    flags: ['scaffold-result', 'punct'],
  }),
  defineConstruction({
    id: 'scomma-s',
    family: 'punctuation',
    left: 'SCOMMA', right: 'S', result: 'S', head: 0,
    status: S.APPROXIMATION,
    relation: 'conj',
    construction: 'asymmetric-clausal-sequence',
    limitation: 'Also covers asyndetic sequences; first clause heads per UD conj',
    note: 'he ran , she fell — RULING: first clause heads',
    flags: ['ud-aligned', 'ruling'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  /**
   * INERT BRACKETING MARKS — `WRAP`.
   *
   * Quotes, parentheses, dashes and slashes are not terminal punctuation and
   * must not be typed as `PUNCT`: every `PUNCT` rule absorbs to the LEFT, and a
   * bracketing mark's defining property is that it also occurs to the left of
   * what it marks. `"` opening a quotation has nothing behind it to absorb into.
   *
   * So `WRAP` is a separate element with symmetric valence — it bonds on either
   * side and never takes the head. The chemistry is a noble-gas ligand: it
   * occupies a site, forms no polar bond, and leaves the host's type and head
   * exactly as they were.
   *
   * MEASURED BEFORE WRITTEN. Deleting these tokens outright raises
   * truth-reachability on the frozen gate corpus from 32.4% to 40.8%, while a
   * matched random deletion of the SAME token counts over 5 seeds moves it
   * 0.0pp. The gain is specific to these marks, not to shorter input.
   */
  defineConstruction({
    id: 's-wrap-right',
    family: 'punctuation',
    left: 'S', right: 'WRAP', result: 'S', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 's', right: 'bracketing-mark' },
    note: 'S absorbs a following quote / paren / dash — seatbelt, not skeleton',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 's-wrap-left',
    family: 'punctuation',
    left: 'WRAP', right: 'S', result: 'S', head: 1,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'bracketing-mark', right: 's' },
    note: 'A leading quote / paren / dash is absorbed by the S that follows it',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'np-wrap-right',
    family: 'punctuation',
    left: 'NP', right: 'WRAP', result: 'NP', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'np', right: 'bracketing-mark' },
    note: 'NP absorbs a following quote / paren / dash — seatbelt, not skeleton',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'np-wrap-left',
    family: 'punctuation',
    left: 'WRAP', right: 'NP', result: 'NP', head: 1,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'bracketing-mark', right: 'np' },
    note: 'A leading quote / paren / dash is absorbed by the NP that follows it',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'n-wrap-right',
    family: 'punctuation',
    left: 'N', right: 'WRAP', result: 'N', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'n', right: 'bracketing-mark' },
    note: 'N absorbs a following quote / paren / dash — seatbelt, not skeleton',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'n-wrap-left',
    family: 'punctuation',
    left: 'WRAP', right: 'N', result: 'N', head: 1,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'bracketing-mark', right: 'n' },
    note: 'A leading quote / paren / dash is absorbed by the N that follows it',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'nc-wrap-right',
    family: 'punctuation',
    left: 'NC', right: 'WRAP', result: 'NC', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'nc', right: 'bracketing-mark' },
    note: 'NC absorbs a following quote / paren / dash — seatbelt, not skeleton',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'nc-wrap-left',
    family: 'punctuation',
    left: 'WRAP', right: 'NC', result: 'NC', head: 1,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'bracketing-mark', right: 'nc' },
    note: 'A leading quote / paren / dash is absorbed by the NC that follows it',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'adj-wrap-right',
    family: 'punctuation',
    left: 'ADJ', right: 'WRAP', result: 'ADJ', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'adj', right: 'bracketing-mark' },
    note: 'ADJ absorbs a following quote / paren / dash — seatbelt, not skeleton',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'adj-wrap-left',
    family: 'punctuation',
    left: 'WRAP', right: 'ADJ', result: 'ADJ', head: 1,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'inert-bracketing-mark',
    roles: { left: 'bracketing-mark', right: 'adj' },
    note: 'A leading quote / paren / dash is absorbed by the ADJ that follows it',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'terminal-punct',
    family: 'punctuation',
    left: 'S', right: 'PUNCT', result: 'S', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'sentence-final-punctuation',
    roles: { left: 'clause', right: 'terminal-punct' },
    note: 'Clause absorbs terminal . ! ? ; : (and repeated marks as one PUNCT atom)',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  /**
   * NOMINAL ROOT ABSORB. Web/title fragments root on nouns (`Great electrician.`)
   * with terminal punct outside the NP. Same seatbelt as S+PUNCT: punct is not
   * the skeleton; the NP is. Head stays on the nominal.
   */
  defineConstruction({
    id: 'np-terminal-punct',
    family: 'punctuation',
    left: 'NP', right: 'PUNCT', result: 'NP', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'nominal-final-punctuation',
    roles: { left: 'noun-phrase', right: 'terminal-punct' },
    note: 'NP absorbs terminal punct — seatbelt, not skeleton',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'adj-terminal-punct',
    family: 'punctuation',
    left: 'ADJ', right: 'PUNCT', result: 'ADJ', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'adjectival-final-punctuation',
    roles: { left: 'adjective', right: 'terminal-punct' },
    note: 'Adjectival fragments with terminal punct (seatbelt)',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  /**
   * Hint sim nuclei: punct-absorb parity for bare N and NC.
   * We already absorb on S / NP / ADJ; pure nouns and compounds need the same seatbelt.
   */
  defineConstruction({
    id: 'n-terminal-punct',
    family: 'punctuation',
    left: 'N', right: 'PUNCT', result: 'N', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'noun-final-punctuation',
    roles: { left: 'noun', right: 'terminal-punct' },
    note: 'Hint nucleus — bare N absorbs terminal punct (parity with NP/S/ADJ)',
    flags: ['ud-aligned', 'punct', 'closure', 'hint-nucleus'],
  }),
  defineConstruction({
    id: 'nc-terminal-punct',
    family: 'punctuation',
    left: 'NC', right: 'PUNCT', result: 'NC', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'compound-noun-final-punctuation',
    roles: { left: 'compound-noun', right: 'terminal-punct' },
    note: 'Hint nucleus — NC absorbs terminal punct (parity with N)',
    flags: ['ud-aligned', 'punct', 'closure', 'hint-nucleus'],
  }),
  defineConstruction({
    id: 'salutation-s-comma',
    family: 'punctuation',
    left: 'S', right: 'COMMA', result: 'S', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'salutation-closing-comma',
    roles: { left: 'salutation-clause', right: 'closing-comma' },
    note: 'Regards , / Visit , — clausal imperative/salutation with closing comma',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
  defineConstruction({
    id: 'salutation-adv-comma',
    family: 'punctuation',
    left: 'ADV', right: 'COMMA', result: 'S', head: 0,
    status: S.GRAMMAR,
    relation: 'punct',
    construction: 'salutation-closing-comma',
    roles: { left: 'salutation-adverb', right: 'closing-comma' },
    note: 'Sincerely , — adverbial discourse sign-off with closing comma',
    flags: ['ud-aligned', 'punct', 'closure'],
  }),
];
