import { defineConstruction, CONSTRUCTION_STATUS as S } from '../schemas.js';

export const VERB = [
  defineConstruction({
    id: 'verb-pp',
    family: 'verb',
    left: 'V', right: 'PP', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    relation: 'obl',
    construction: 'verb-pp-attachment',
    roles: { left: 'verb', right: 'pp' },
    limitation: 'obl / advcl / xcomp-PP collapsed into one V+PP rule',
    note: 'Verb plus prepositional phrase',
    flags: ['attachment-ambiguous'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'verb-np-object',
    family: 'verb',
    left: 'V', right: 'NP', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    relation: 'obj',
    construction: 'transitive-vp',
    roles: { left: 'verb', right: 'object' },
    limitation: 'obj / iobj / nominal xcomp not distinguished',
    note: 'Verb plus nominal object',
    flags: ['object-bundle'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'verb-npo-object',
    family: 'verb',
    left: 'V', right: 'NPO', result: 'VP', head: 0,
    status: S.GRAMMAR,
    relation: 'obj',
    construction: 'transitive-vp-pronominal',
    roles: { left: 'verb', right: 'accusative-object' },
    note: 'saw HIM — case-marked object',
    flags: ['ud-aligned'],
  }),
  defineConstruction({
    id: 'verb-adj',
    family: 'verb',
    left: 'V', right: 'ADJ', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    construction: 'verb-adjective',
    roles: { left: 'verb', right: 'adjective' },
    limitation: 'secondary predication / resultative / small-clause collapsed',
    note: 'Verb plus adjective',
    flags: ['construction-bundle'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'vp-pp',
    family: 'verb',
    left: 'VP', right: 'PP', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    construction: 'vp-pp-attachment',
    roles: { left: 'verb-phrase', right: 'pp' },
    limitation: 'Catalan attachment generator; site not typed',
    note: 'THE CATALAN GENERATOR (VP side)',
    flags: ['catalan', 'attachment-ambiguous'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'verb-particle',
    family: 'verb',
    left: 'V', right: 'PRT', result: 'V', head: 0,
    status: S.GRAMMAR,
    relation: 'compound:prt',
    construction: 'phrasal-verb',
    roles: { left: 'verb', right: 'particle' },
    note: 'UD compound:prt — gave up',
    flags: ['ud-aligned'],
  }),
  defineConstruction({
    id: 'vp-particle',
    family: 'verb',
    left: 'VP', right: 'PRT', result: 'VP', head: 0,
    status: S.GRAMMAR,
    relation: 'compound:prt',
    construction: 'particle-shift',
    roles: { left: 'verb-phrase', right: 'particle' },
    note: 'picked it UP — particle shift',
    flags: ['ud-aligned-head'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'verb-infinitive',
    family: 'verb',
    left: 'V', right: 'INF', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    construction: 'verb-infinitival-complement',
    roles: { left: 'verb', right: 'infinitive' },
    limitation: 'xcomp vs ccomp vs purpose not split',
    note: 'wants TO RUN',
    flags: ['construction-bundle'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  /**
   * Hint sim nucleus: VP+INF host extension of V+INF.
   * Once the verb has projected to VP (object/PP taken), infinitival
   * complements should still attach.
   */
  defineConstruction({
    id: 'vp-infinitive',
    family: 'verb',
    left: 'VP', right: 'INF', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    construction: 'vp-infinitival-complement',
    roles: { left: 'verb-phrase', right: 'infinitive' },
    limitation: 'xcomp vs purpose vs result not split; host extension of V+INF',
    note: 'Hint nucleus — wants him TO RUN style after object builds VP',
    flags: ['construction-bundle', 'hint-nucleus', 'host-extension'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  defineConstruction({
    id: 'verb-sbar',
    family: 'verb',
    left: 'V', right: 'SBAR', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    construction: 'verb-clausal-complement',
    roles: { left: 'verb', right: 'clause' },
    limitation: 'ccomp / csubj / advcl not split',
    note: 'answered THAT …',
    flags: ['construction-bundle'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
  /**
   * Hint sim nucleus: VP+SBAR host extension of V+SBAR.
   * Strong ensemble gain without coverage churn — gold answers land in chart.
   */
  defineConstruction({
    id: 'vp-sbar',
    family: 'verb',
    left: 'VP', right: 'SBAR', result: 'VP', head: 0,
    status: S.APPROXIMATION,
    construction: 'vp-clausal-complement',
    roles: { left: 'verb-phrase', right: 'clause' },
    limitation: 'ccomp / advcl not split; host extension of V+SBAR',
    note: 'Hint nucleus — told him THAT … after object builds VP',
    flags: ['construction-bundle', 'hint-nucleus', 'host-extension'],
    grades: { C: 'G', R: 'G', H: 'G', X: 'Y' },
  }),
];
