/**
 * SCDL Emit Packet Pass
 *
 * Assembles the final PixelBrainAssetPacket from the expanded AST.
 * Calls into the existing createPixelBrainAssetPacket() from pixelbrain-asset-packet.js.
 */

import {
  createPixelBrainAssetPacket,
  normalizePixelBrainCanvas,
  stableJson,
} from '../../pixelbrain-asset-packet.js';
import { hashString } from '../../shared.js';

/**
 * @param {object} ast - Fully expanded SCDL AST
 * @param {import('../scdl.errors.js').SCDLError[]} _errors
 * @returns {import('../../pixelbrain-asset-packet.js').PixelBrainAssetPacket}
 */
export function emitPacketPass(ast, _errors) {
  if (ast.sceneGraph) return emitSceneGraphPacket(ast);

  const canvas = normalizePixelBrainCanvas(ast.canvas);

  // Flatten all coordinates from all parts
  const allCoordinates = [];
  const allNoise = [];

  for (const part of ast.parts) {
    for (const coord of (part.coordinates || [])) {
      allCoordinates.push({
        x:        coord.x,
        y:        coord.y,
        color:    coord.color,
        partId:   coord.partId || part.id,
        material: coord.material || part.material,
        role:     coord.role,
        sourceOpId: coord.sourceOpId,
        _fillIntent: coord._fillIntent || false,
      });
    }
    for (const noise of (part.noiseDescriptors || [])) {
      allNoise.push(noise);
    }
  }

  // Build palette entries from AST palette
  const paletteColors = Object.values(ast.palette || {}).filter(Boolean);
  const sourcePalette = paletteColors.length
    ? [{ key: 'scdl-source', colors: paletteColors, source: 'scdl', weights: [] }]
    : [];

  // Build part metadata tags
  const partTags = (ast.parts || []).map(p => `${p.id}:${p.material}`);

  const packet = createPixelBrainAssetPacket({
    id:      null, // stableId generated by packet factory
    canvas,
    geometry: {
      mode:        'coordinates',
      coordinates: allCoordinates,
    },
    palette: {
      sourcePalette,
      authority: 'scdl.emit-packet.v1',
    },
    source: {
      kind:  'scdl',
      id:    ast.asset,
      label: `SCDL:${ast.asset}`,
    },
    material: {
      id: _primaryMaterial(ast.parts),
    },
    noiseDescriptors: allNoise,
    provenance: {
      createdBy:  'scdl-compiler.v1',
      operations: [
        { op: 'parse',          checksum: ast.checksum },
        { op: 'semantic-unifier', schemaVersion: 'PB-SEM-v1' },
        { op: 'compile',        partCount: ast.parts.length },
        { op: 'coordinates',    count: allCoordinates.length },
      ],
    },
    metadata: {
      tags:  ['scdl', ast.type, ...partTags],
      notes: [
        `SCDL asset: ${ast.asset}`,
        `Canvas: ${canvas.width}x${canvas.height}`,
        `Parts: ${ast.parts.map(p => p.id).join(', ')}`,
        ast.parts.some(p => p.intentOps?.length) ? 'Contains trace intents (runtime resolution)' : null,
      ].filter(Boolean),
    },
  });

  return packet;
}

function _primaryMaterial(parts) {
  if (!parts || parts.length === 0) return 'source';
  return parts[0].material || 'source';
}

function emitSceneGraphPacket(ast) {
  const canvas = normalizePixelBrainCanvas(ast.canvas);
  const sceneGraph = ast.sceneGraph;
  const id = `pbasset_${hashString(stableJson(sceneGraph)).toString(16).padStart(8, '0')}`;

  const paletteColors = Object.values(ast.palette || {}).filter(Boolean);
  const sourcePalette = paletteColors.length
    ? [{ key: 'scdl-source', colors: paletteColors, source: 'scdl', weights: [] }]
    : [];

  const countNodes = nodes => (nodes || []).reduce(
    (n, node) => n + 1 + (node.kind === 'group' ? countNodes(node.children) : 0), 0
  );

  return createPixelBrainAssetPacket({
    id, // identity law: hash of the canonical program, never pixels
    canvas,
    geometry: { mode: 'scene-graph', sceneGraph, coordinates: [] },
    palette: { sourcePalette, authority: 'scdl.emit-packet.v1' },
    source: { kind: 'scdl', id: ast.asset, label: `SCDL:${ast.asset}` },
    material: { id: 'source' },
    provenance: {
      createdBy: 'scdl-compiler.v1',
      operations: [
        { op: 'parse', checksum: ast.checksum },
        { op: 'semantic-unifier', schemaVersion: 'PB-SEM-v1' },
        { op: 'scene-graph', defCount: Object.keys(sceneGraph.defs).length, rootNodeCount: countNodes(sceneGraph.roots) },
      ],
    },
    metadata: {
      tags: ['scdl', 'scene-graph', ast.type],
      notes: [
        `SCDL scene-graph asset: ${ast.asset}`,
        `Canvas: ${canvas.width}x${canvas.height}`,
        `Defs: ${Object.keys(sceneGraph.defs).join(', ') || '(none)'}`,
      ],
    },
  });
}

