import type { GrimoireTrack } from './types';

// Big Father — a real Suno incantation by Vaelrix, released 2026-06-11.
// All metadata from the published clip JSON (studio-api-prod.suno.com).
// No pacing block: tempo was not measured — the heuristic fallback uses
// DEFAULT_PACING and the UI labels that sync "estimated" (honesty law).
// Section markers in the source prompt ([Chorus], and a typo'd "[Chorus[")
// are stage directions, not sung text, and are excluded from lyrics.
export const BIG_FATHER: GrimoireTrack = {
  id: 'eaba93dc-bf75-4319-a67e-ddcedafc1c43',
  title: 'Big Father',
  artist: 'Vaelrix',
  model: 'chirp-fenix',
  modelVersion: 'v5.5',
  duration: 206.64, // 3:27, from the clip metadata
  sunoUrl: 'https://suno.com/song/eaba93dc-bf75-4319-a67e-ddcedafc1c43',
  audioUrl: 'https://cdn1.suno.ai/eaba93dc-bf75-4319-a67e-ddcedafc1c43.mp3',
  coverUrl: 'https://cdn2.suno.ai/image_eaba93dc-bf75-4319-a67e-ddcedafc1c43.jpeg',
  stageArtUrl: `${import.meta.env.BASE_URL}media/big-father-stage.png`,
  meta: [
    ['Duration', '3:27'],
    ['Model', 'chirp-fenix · v5.5'],
    ['Persona', 'Vaelrix'],
    ['Style', 'Sorrow jazz × hyperpop × cinematic trip-hop'],
    ['Key', 'Aeolian E minor (from the published style tags)'],
    ['Released', 'June 11, 2026'],
    ['Source', 'suno.com'],
  ],
  provenance: {
    statement: 'Crafted with human intention and AI assistance.',
    tools: ['Suno v5.5 · chirp-fenix', 'Persona — Vaelrix'],
    assistance:
      'Sorrow jazz / hyperpop / cinematic trip-hop fusion · piano motifs · cello & violin quartet harmonies',
  },
  lyrics: [
    'body is dead, with a mind of a Zero',
    'Copy the death of divine like a hero',
    'Sloppy, my breath is aligned with a weird flow',
    "Obvious stench from the rhyme, I'm a scarecrow.",
    'Big Father, the godfather of sick authors',
    "Depicting slaughter, I'm bouncer of the afterlife",
    'Hear a wack bar on your rise? And then you have to fight',
    'More than a pound of flesh is needed for the sacrifice',
    'Big Father, the godfather of sick authors',
    "Depicting slaughter, I'm bouncer of the afterlife",
    'Hear a wack bar on your rise? And then you have to fight',
    'More than a pound of flesh is needed for the sacrifice',
    "I'm a scarecrow.",
    'Modified range like my rage is a zoomed scope',
    'Stone visage like the man on the moon',
    'Soul vicious, understand I am doom.',
    'Dope Victor. slam in the booth, go figure.',
    "Laminated truth won't wither",
    "Hands that made the booth can't picture",
    'holding back like a chiropractor.',
    'put a pyro actor on a steel plated stretcher.',
    'Heel of a century, A centaur with a mind of a Griffon.',
    'but never peter out,',
    'Lines of disses, they never fizzle out',
    'Tongue sizzling with magic,',
    "my school bus leads to Ms FIzzle's house",
    'Chris Kringle mouth,',
    "Voice is a gift, a presence you can't figure out",
    'Void is a rift in my skull that emits a shout',
    'strong enough to split the planet and leave a fissure, delivered doubt',
    'Wizard, they shiver around the aura',
    'Bipolar bear of horror',
    'Entered through the portal as a mortal and emerged',
    'as a son of God, sorcerer',
    'With more than one gift, and more than one honorific',
    'Complicated rage, concentrated venom.',
    'Big Father, through the gamut I been a part of',
    'went through the demons, the legions, the slaughter',
    'Rhyme doctor, bringing life with my water',
    'Divine proctor. Hollow God denied all the',
    'Faith rejectors, I play with a rage and engaged in pressure',
    'I came with a flame and a mania',
    'they labeled schizophrenia, and maybe the pain in the letters',
    'Is easy to get rid of, elated to know',
    'That my craziest flow is mentally put together...',
    'Big Father, the godfather of sick authors',
    "Depicting slaughter, I'm bouncer of the afterlife",
    'Hear a wack bar on your rise? And then you have to fight',
    'More than a pound of flesh is needed for the sacrifice',
    'Big Father, the godfather of sick authors',
    "Depicting slaughter, I'm bouncer of the afterlife",
    'Hear a wack bar on your rise? And then you have to fight',
    'More than a pound of flesh is needed for the sacrifice',
    "Holy Heathen like Q, I don't even like you",
    'Puerto Rican Kaiju, More than deep, a Typhoon.',
    "Holy Heathen like Q, I don't even like you",
    'Puerto Rican Kaiju, More than deep, a Typhoon.',
  ],
  annotations: [],
};
