import type { GrimoireTrack } from './types';

// Saiyan Blood — a Vaelrix incantation on the custom Scholomance V2 model.
// Honesty law: id, creation date and lyrics below are lifted verbatim from the
// file's own ID3 tags (comment: "made with suno; created=2026-07-19T11:44:40.308182Z;
// id=3563e460-584a-4ecb-b09a-dd4dccde0a60"); duration is measured from the master
// (237.89s). Style ("Hip-Hop · Rap") was reported by Vaelrix — the file carries no
// style/model tag; the model is the album-wide custom Scholomance V2. The audio is
// the LOCAL master Vaelrix supplied, served from public/media — not a Suno CDN URL.
// sunoUrl is derived from the embedded id (a provenance link, not verified live),
// and there is no track-specific cover, so it reuses the album art.
export const SAIYAN_BLOOD: GrimoireTrack = {
  id: '3563e460-584a-4ecb-b09a-dd4dccde0a60',
  title: 'Saiyan Blood',
  artist: 'Vaelrix',
  model: 'Scholomance V2',
  modelVersion: 'custom',
  duration: 238, // 3:58, measured from the master (237.89s)
  sunoUrl: 'https://suno.com/song/3563e460-584a-4ecb-b09a-dd4dccde0a60',
  // Local master (BASE_URL-relative so it survives a deploy under a subpath),
  // not a Suno CDN URL — Vaelrix supplied the file directly.
  audioUrl: `${import.meta.env.BASE_URL}media/saiyan-blood.mp3`,
  // No track-specific cover was supplied; reuse Vaelrix's album art.
  coverUrl: `${import.meta.env.BASE_URL}media/scholomancer-cover.png`,
  meta: [
    ['Duration', '3:58'],
    ['Model', 'Custom Suno model · Scholomance V2'],
    ['Persona', 'Vaelrix'],
    ['Style', 'Hip-Hop · Rap'],
    ['Released', 'July 19, 2026'],
    ['Source', 'Local master'],
  ],
  provenance: {
    statement: 'Crafted with human intention and AI assistance.',
    tools: ['Suno · custom model — Scholomance V2', 'Persona — Vaelrix'],
    assistance: 'Hip-hop · rap',
  },
  // No measured tempo — this track carries no pacing block and falls back to
  // DEFAULT_PACING, whose sync the UI already labels "estimated" (honesty law).
  // Verbatim from the master's embedded lyrics-eng tag, with blank stanza breaks
  // and [Section] directions dropped — the registry carries sung text only.
  lyrics: [
    "Raising a sword in a sordid state",
    "Abhorrence absorbed in a gorgeous blade",
    "Sorcerer stone on the hilt, Okay.",
    "Torture is laced on the corpses I make",
    "Morgue getting filled by the cost of mistakes",
    "Orifice of anguish exposing the hate.",
    "Morbid disguise, see the snake on my face",
    "War is alive in the syncopated pace...",
    "Okay..",
    "Okay..",
    "Mentally unwell, mage with a gun spell.",
    "Minister of dark arts, The offspring of Kal-El",
    "Law bleeds over the mic, cost of the light that flows well",
    "The eight is sideways on my own scale.....",
    "Copacetic skill, and raw will",
    "encoded chromosomes glowing indigo, strong build",
    "Poetic pulse like a cold chill",
    "Coldly manifest, scripting code with a stone quill... Ugh",
    "Explosive terminology",
    "Focus serving prophecy, the flow? It burns inside of me",
    "mode of cursive doctrine seasons death like it's autumn leaves",
    "Flow marching on the beat like soldiers serving Constantine",
    "Steam engine revving constantly, Mephistopheles",
    "setting stops with me, impossibly",
    "the head of honest letting monsters bleed to see the God in me",
    "Completed what I am by fusing death with my artistry",
    "I swallowed the Darkness",
    "I bathed in the abyss",
    "it was never enough, Never enough",
    "I swallowed the Darkness",
    "I bathed in the abyss",
    "it was never enough, Never enough",
    "Light bearer with the mind carrying blight",
    "My fist craters like an aerial strike",
    "I keep staring at the mirror like",
    "Fear is unstable design,",
    "A two legged table will collapse, give it time",
    "Light bearer with the mind carrying blight",
    "My fist craters like an aerial strike",
    "I keep staring at the mirror like",
    "Fear is unstable design,",
    "A two legged table will collapse, give it time",
    "A two legged table will collapse, give it time",
    "A two legged table will collapse, give it time",
    "My red dot covers the world like Jupiter's spot.",
    "I'm nuclear hot, My doctrine, munroe, a storm.",
    "Mental hemisphere ironclad, the bad is only lukewarm",
    "compared to the pad of the vast death and devil horns",
    "Layered craft, Lasagna, Bars filling a Garfield",
    "I'm a Hidden legend serving wealth like a Pirate Treasure Map",
    "all the bullshit in the past, I remember that.",
    "Weapons ending health like a virus, make the web detach",
    "Limitless like NZT-48",
    "MVP of morbid state, meter centipede recording hate",
    "abundance of feats, I stay achieving while they stuck in place",
    "Wordplay incredible, the synthesis like alchemy, I run the game",
    "CPU, becomes CP9",
    "I say SHAVE! then your face cracked with easy rhymes",
    "A TV mind, I tell a vision and you see the signs",
    "should I kill a rap or leave it behind? I'll never know.",
    "Light bearer with the mind carrying blight",
    "My fist craters like an aerial strike",
    "I keep staring at the mirror like",
    "Fear is unstable design,",
    "A two legged table will collapse, give it time",
    "Light bearer with the mind carrying blight",
    "My fist craters like an aerial strike",
    "I keep staring at the mirror like",
    "Fear is unstable design,",
    "A two legged table will collapse, give it time",
    "A two legged table will collapse, give it time",
    "A two legged table will collapse, give it time",
    "Magical bars letting the demon out.",
    "Wrath in the heart causing a deeper drought",
    "Lazarus mind, slaughter the beat again",
    "Masochist heart, train with Vegeta's whims",
    "Magical bars letting the demon out.",
    "Wrath in the heart causing a deeper drought",
    "Lazarus mind, slaughter the beat again",
    "Masochist heart, train with Vegeta's whims",
  ],
  annotations: [],
};
