import { useMemo, useRef, useState } from 'react';
import { useGameChannel, useSystem } from '../../hooks/mmorpg/useGameUi';
import type { GraphNode, Region } from '../../lib/mmorpg/contracts';
import { Badge, Button, EmptyState, Panel, SearchField, Tabs } from './primitives';
import { CommandButton, ResourceState } from './systemSupport';
const EMPTY_REGIONS: Region[] = [];
function useViewport() {
  const [zoom, setZoom] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 });
  const drag = useRef<{ x: number; y: number; px: number; py: number }>();
  return { zoom, pan, reset: () => { setZoom(1); setPan({ x: 0, y: 0 }); }, changeZoom: (delta: number) => setZoom(z => Math.max(.5, Math.min(4, z + delta))),
    handlers: {
      onPointerDown: (e: React.PointerEvent<SVGSVGElement>) => { if ((e.target as Element).closest('[data-marker]')) return; e.currentTarget.setPointerCapture(e.pointerId); drag.current = { x: e.clientX, y: e.clientY, px: pan.x, py: pan.y }; },
      onPointerMove: (e: React.PointerEvent<SVGSVGElement>) => { if (drag.current) setPan({ x: drag.current.px + e.clientX - drag.current.x, y: drag.current.py + e.clientY - drag.current.y }); },
      onPointerUp: () => { drag.current = undefined; }, onPointerCancel: () => { drag.current = undefined; },
      onKeyDown: (e: React.KeyboardEvent<SVGSVGElement>) => { const delta: Record<string, [number, number]> = { ArrowLeft: [32, 0], ArrowRight: [-32, 0], ArrowUp: [0, 32], ArrowDown: [0, -32] }; if (delta[e.key]) { e.preventDefault(); setPan(p => ({ x: p.x + delta[e.key][0], y: p.y + delta[e.key][1] })); } },
    },
  };
}
export function MapWindow() {
  const resource = useSystem('map'); const liveRegions = useGameChannel('regions', EMPTY_REGIONS);
  const regions = resource.state === 'ready' ? resource.data.regions || [] : liveRegions;
  const [regionId, setRegionId] = useState(''); const [filter, setFilter] = useState('All'); const [waypoint, setWaypoint] = useState<{ x: number; y: number }>(); const [markerId, setMarkerId] = useState('');
  const view = useViewport(); const region = regions.find(r => r.id === regionId) || regions[0];
  if (!region) return <EmptyState title="Chart unavailable">The current region has not supplied map data.</EmptyState>;
  const markers = region.markers.filter(m => filter === 'All' || m.kind === filter);
  return <div className="sui-stack"><div className="sui-map-toolbar"><select aria-label="Region" value={region.id} onChange={e => { setRegionId(e.target.value); view.reset(); setWaypoint(undefined); }}>{regions.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><div className="sui-toolbar"><Button aria-label="Zoom map out" onClick={() => view.changeZoom(-.25)}>−</Button><Badge>{Math.round(view.zoom * 100)}%</Badge><Button aria-label="Zoom map in" onClick={() => view.changeZoom(.25)}>+</Button><Button onClick={view.reset}>Reset view</Button></div></div><Tabs options={['All', ...new Set(region.markers.map(m => m.kind))]} value={filter} onChange={setFilter} /><svg className="sui-map" viewBox={`0 0 ${region.width} ${region.height}`} role="img" aria-label={`${region.name} map. Arrow keys pan. Select a marker to place a waypoint.`} tabIndex={0} {...view.handlers}><g transform={`translate(${view.pan.x} ${view.pan.y}) scale(${view.zoom})`}>{region.image && <image href={region.image} width={region.width} height={region.height} />}{markers.map(marker => <g key={marker.id} data-marker="true" role="button" tabIndex={0} aria-label={`${marker.label}, ${marker.kind}${marker.discovered === false ? ', undiscovered' : ''}`} transform={`translate(${marker.x} ${marker.y})`} onClick={() => { setMarkerId(marker.id); setWaypoint({ x: marker.x, y: marker.y }); }} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setMarkerId(marker.id); setWaypoint({ x: marker.x, y: marker.y }); } }}><circle r={Math.max(4, region.width / 130)} opacity={marker.discovered === false ? .4 : 1} /><text y={-Math.max(8, region.width / 80)} textAnchor="middle">{marker.kind === 'player' ? 'You' : marker.label}</text></g>)}{waypoint && <path d={`M ${waypoint.x - 10} ${waypoint.y} h 20 M ${waypoint.x} ${waypoint.y - 10} v 20`} stroke="var(--sui-gold)" strokeWidth="3" />}</g></svg><div className="sui-toolbar"><span>Waypoint</span><label>X <input aria-label="Waypoint X" type="number" min={0} max={region.width} value={waypoint?.x ?? ''} onChange={e => setWaypoint({ x: Math.min(region.width, Math.max(0, Number(e.target.value))), y: waypoint?.y || 0 })} /></label><label>Y <input aria-label="Waypoint Y" type="number" min={0} max={region.height} value={waypoint?.y ?? ''} onChange={e => setWaypoint({ x: waypoint?.x || 0, y: Math.min(region.height, Math.max(0, Number(e.target.value))) })} /></label><Button onClick={() => setWaypoint(undefined)}>Clear waypoint</Button></div><small>{region.markers.find(m => m.id === markerId)?.label || 'Select a location. Waypoints are personal navigation marks.'}</small><details><summary>Map legend</summary>{[...new Set(region.markers.map(m => m.kind))].map(kind => <p key={kind}>◇ {kind}</p>)}</details></div>;
}
export function ProgressionWindow() {
  const resource = useSystem('progression'); const [search, setSearch] = useState(''); const [selectedId, setSelectedId] = useState<string>(); const view = useViewport();
  const nodes = resource.data.nodes || []; const selected = nodes.find(n => n.id === selectedId);
  const byId = useMemo(() => new Map(nodes.map(n => [n.id, n])), [nodes]);
  const ancestors = useMemo(() => { const visited = new Set<string>(); const visit = (id: string) => { if (visited.has(id)) return; visited.add(id); byId.get(id)?.prerequisites.forEach(visit); }; if (selected) visit(selected.id); return visited; }, [selected, byId]);
  const extent = { width: Math.max(800, ...nodes.map(n => n.x + 180)), height: Math.max(500, ...nodes.map(n => n.y + 80)) };
  return <ResourceState resource={resource}><div className="sui-toolbar"><SearchField value={search} onChange={setSearch} label="Find a semantic node" /><Button onClick={() => view.changeZoom(-.25)} aria-label="Zoom graph out">−</Button><Button onClick={() => view.changeZoom(.25)} aria-label="Zoom graph in">+</Button><Button onClick={view.reset}>Reset</Button></div><svg className="sui-map sui-graph" role="img" aria-label="Semantic progression graph. Arrow keys pan; Tab focuses nodes." tabIndex={0} viewBox={`0 0 ${extent.width} ${extent.height}`} {...view.handlers}><g transform={`translate(${view.pan.x} ${view.pan.y}) scale(${view.zoom})`}>{nodes.flatMap(node => node.prerequisites.map(id => { const from = byId.get(id); return from ? <line key={`${id}-${node.id}`} x1={from.x + 75} y1={from.y + 25} x2={node.x + 75} y2={node.y + 25} data-active={ancestors.has(id) && ancestors.has(node.id)} /> : null; }))}{nodes.filter(n => !search || n.name.toLowerCase().includes(search.toLowerCase())).map(node => <GraphPoint key={node.id} node={node} selected={selectedId === node.id} onSelect={() => setSelectedId(node.id)} />)}</g></svg>{selected ? <Panel inset><h3>{selected.name}</h3><Badge>{selected.state}</Badge><p>{selected.description}</p><p>Requires: {selected.prerequisites.map(id => byId.get(id)?.name || id).join(', ') || 'No prerequisites'}</p><div className="sui-toolbar"><CommandButton system="progression" command="purchase" args={{ id: selected.id }} disabled={selected.state !== 'available'}>Learn</CommandButton><CommandButton system="progression" command="refund" args={{ id: selected.id }} disabled={selected.state !== 'purchased'} confirm>Refund</CommandButton></div></Panel> : <small>Select a node to trace its prerequisites.</small>}</ResourceState>;
}
function GraphPoint({ node, selected, onSelect }: { node: GraphNode; selected: boolean; onSelect: () => void }) { return <g className="sui-graph-node" data-state={node.state} data-marker="true" transform={`translate(${node.x} ${node.y})`} role="button" tabIndex={0} aria-label={`${node.name}, ${node.state}`} aria-pressed={selected} onClick={onSelect} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(); } }}><rect width="150" height="50" rx="3" /><text x="75" y="21" textAnchor="middle">{node.name}</text><text x="75" y="40" textAnchor="middle">{node.state}</text></g>; }
