import { useId, useRef, useState, type ReactNode, type ButtonHTMLAttributes, type CSSProperties } from 'react';
import { BookOpen, Backpack, UserRound, Map, Sparkles, Network, Hammer, Users, Settings, ScrollText, Swords, Shield, Gem, Trophy, Library, MessageSquare, Compass, Skull, CircleHelp, Box, Store, X, Search, Lock, Grip, ChevronRight } from 'lucide-react';
import type { Item, Stat, SocketModel } from '../../lib/mmorpg/contracts';
import { UI_LIMITS } from '../../lib/mmorpg/state';
import { useTooltip } from './interactions';
const ICONS = { inventory: Backpack, character: UserRound, map: Map, quests: ScrollText, abilities: Sparkles, progression: Network, crafting: Hammer, enchanting: Gem, social: Users, settings: Settings, party: Users, raid: Shield, chat: MessageSquare, vendor: Store, loot: Box, codex: Library, achievements: Trophy, collections: Gem, dialogue: MessageSquare, death: Skull, encounters: Swords, tutorial: CircleHelp, inspect: UserRound, navigation: Compass, close: X, search: Search, lock: Lock, move: Grip, book: BookOpen };
export function Icon({ name, size = 20 }: { name: string; size?: number }) { const Glyph = ICONS[name as keyof typeof ICONS] || ChevronRight; return <Glyph size={size} strokeWidth={1.5} aria-hidden="true" />; }
export function Button({ children, tone = 'normal', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { tone?: string }) { return <button type="button" {...props} className={`sui-button ${props.className || ''}`} data-tone={tone}>{children}</button>; }
export function IconButton({ label, icon, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string; icon: string }) { return <Button {...props} aria-label={label}><Icon name={icon} /></Button>; }
export function Panel({ children, title, inset = false }: { children: ReactNode; title?: string; inset?: boolean }) { return <section className="sui-panel" data-inset={inset}>{title && <h3 className="sui-section-title">{title}</h3>}{children}</section>; }
export function SectionHeader({ title, meta }: { title: string; meta?: ReactNode }) { return <div className="sui-section-header"><h3>{title}</h3>{meta && <span>{meta}</span>}</div>; }
export function Badge({ children, state }: { children: ReactNode; state?: string }) { return <span className="sui-badge" data-state={state}>{children}</span>; }
export function StatRow({ label, value, delta, description }: Stat) { const tip = useTooltip(description || null); return <div className="sui-stat" {...tip} tabIndex={description ? 0 : undefined}><span>{label}</span><strong>{value}</strong>{delta !== undefined && <span data-sign={delta >= 0 ? 'positive' : 'negative'}>{delta > 0 ? '+' : ''}{delta}</span>}</div>; }
export function Meter({ label, value, max, kind = 'energy', subtle = false }: { label: string; value?: number; max?: number; kind?: string; subtle?: boolean }) {
  const valid = Number.isFinite(value) && Number.isFinite(max) && (max || 0) > 0;
  const total = valid ? max! : 1; const current = valid ? Math.max(0, Math.min(total, value!)) : 0;
  return <div className="sui-meter" data-kind={kind} data-subtle={subtle}><div><span>{label}</span><b>{valid ? `${Math.round(current)} / ${Math.round(total)}` : '—'}</b></div><progress aria-label={label} value={current} max={total} /></div>;
}
export function SearchField({ value, onChange, label = 'Search' }: { value: string; onChange: (value: string) => void; label?: string }) { return <label className="sui-search"><Icon name="search" /><input type="search" aria-label={label} placeholder={label} value={value} onChange={e => onChange(e.target.value)} /></label>; }
export function Tabs({ options, value, onChange, label = 'Categories' }: { options: string[]; value: string; onChange: (value: string) => void; label?: string }) {
  return <div className="sui-tabs" role="group" aria-label={label}>{options.map(option => <button key={option} type="button" aria-pressed={value === option} onClick={() => onChange(option)}>{option}</button>)}</div>;
}
export function EmptyState({ title, children, state = 'empty' }: { title: string; children?: ReactNode; state?: string }) { return <div className="sui-empty" role={state === 'error' ? 'alert' : 'status'}><Icon name={state === 'error' ? 'tutorial' : 'book'} size={32} /><h3>{title}</h3><p>{children}</p></div>; }
export function Socket({ socket, onClick, disabled }: { socket: SocketModel; onClick?: () => void; disabled?: boolean }) { return <button type="button" className="sui-socket" disabled={disabled} onClick={onClick}><span className="sui-socket-glyph"><Icon name="enchanting" /></span><span><b>{socket.category}</b><small>{socket.modifier || socket.label}</small></span><Badge>{socket.modifier ? 'Bound' : 'Empty'}</Badge></button>; }
export function ItemCard({ item, compare }: { item: Item; compare?: Item | null }) {
  const lines: [string, string[] | undefined][] = [['Modifiers', item.modifiers], ['Enchantments', item.enchantments], ['AMPs', item.ampRelationships], ['Shaders', item.shaderRelationships], ['Traits', item.traits], ['Requires', item.requirements]];
  return <article className="sui-item-card" data-rarity={item.rarity || 'common'}><header>{item.icon && <img src={item.icon} alt="" />}<div><h3>{item.name}</h3><span>{item.rarity || 'Common'} · {item.type}{item.itemLevel !== undefined ? ` · Item level ${item.itemLevel}` : ''}</span></div></header>{item.binding && <p>{item.binding}</p>}{item.description && <p>{item.description}</p>}{item.stats?.map(stat => <StatRow key={stat.id || stat.label} {...stat} delta={compare ? Number(stat.value) - Number(compare.stats?.find(s => s.label === stat.label)?.value || 0) : undefined} />)}{lines.filter(([, values]) => values?.length).map(([label, values]) => <section key={label}><h4>{label}</h4><ul>{values!.map(text => <li key={text}>{text}</li>)}</ul></section>)}{item.sockets?.length ? <section><h4>Binding matrix</h4>{item.sockets.map(socket => <p key={socket.id}>◇ {socket.category}: {socket.modifier || 'Empty'}</p>)}</section> : null}{item.flavor && <blockquote>{item.flavor}</blockquote>}{item.lore && <p className="sui-flavor">{item.lore}</p>}{item.sellValue && <StatRow label="Sell value" value={item.sellValue} />}{item.source && <small>Source: {item.source}</small>}{compare && <footer>Compared with {compare.name}</footer>}</article>;
}
export function Slot({ item, label, selected, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { item?: Item | null; label: string; selected?: boolean }) {
  const tooltip = useTooltip(item ? <ItemCard item={item} /> : label);
  return <button type="button" {...tooltip} {...props} className={`sui-slot ${props.className || ''}`} data-rarity={item?.rarity || 'empty'} aria-label={item ? `${label}: ${item.name}, ${item.rarity || 'common'}` : label} aria-pressed={selected}>{item?.icon ? <img src={item.icon} alt="" draggable={false} /> : <Icon name={item ? 'loot' : 'inventory'} />}{item?.count && item.count > 1 ? <span className="sui-slot-count">{item.count}</span> : null}{item?.locked && <span className="sui-slot-lock"><Icon name="lock" size={16} /></span>}{children}</button>;
}
export function VirtualList<T extends { id: string }>({ items, render, label, onSelect, selected }: { items: T[]; render: (item: T) => ReactNode; label: string; onSelect: (item: T) => void; selected?: string }) {
  const [offset, setOffset] = useState(0); const ref = useRef<HTMLDivElement>(null); const id = useId();
  const start = Math.max(0, Math.floor(offset / UI_LIMITS.rowHeight) - UI_LIMITS.overscan);
  const visible = Math.ceil((ref.current?.clientHeight || 400) / UI_LIMITS.rowHeight) + UI_LIMITS.overscan * 2;
  const selectIndex = (index: number) => { const safe = Math.max(0, Math.min(items.length - 1, index)); if (!items[safe]) return; onSelect(items[safe]); const top = safe * UI_LIMITS.rowHeight; if (ref.current && (top < ref.current.scrollTop || top + UI_LIMITS.rowHeight > ref.current.scrollTop + ref.current.clientHeight)) { ref.current.scrollTop = top; setOffset(top); } };
  return <div className="sui-virtual" ref={ref} role="listbox" aria-label={label} tabIndex={0} aria-activedescendant={selected ? `${id}-${selected}` : undefined} onScroll={e => setOffset(e.currentTarget.scrollTop)} onKeyDown={e => { const index = items.findIndex(item => item.id === selected); if (e.key === 'ArrowDown' || e.key === 'ArrowUp' || e.key === 'Home' || e.key === 'End') { e.preventDefault(); selectIndex(e.key === 'Home' ? 0 : e.key === 'End' ? items.length - 1 : index + (e.key === 'ArrowDown' ? 1 : -1)); } }}><div style={{ height: items.length * UI_LIMITS.rowHeight, position: 'relative' }}>{items.slice(start, start + visible).map((item, index) => <div role="option" aria-selected={item.id === selected} aria-setsize={items.length} aria-posinset={start + index + 1} id={`${id}-${item.id}`} tabIndex={-1} className="sui-list-row" key={item.id} style={{ top: (start + index) * UI_LIMITS.rowHeight, height: UI_LIMITS.rowHeight } as CSSProperties} onClick={() => onSelect(item)} onKeyDown={e => { if (e.key === 'Enter') onSelect(item); }}>{render(item)}</div>)}</div></div>;
}
