import { useMemo, useState } from 'react';
import { useGameChannel, useSystem } from '../../hooks/mmorpg/useGameUi';
import { readCharacter, type CombatSnapshot } from '../../lib/mmorpg/gameUi.adapter';
import type { RegistryEntry, Ability, Quest } from '../../lib/mmorpg/contracts';
import { Badge, Button, EmptyState, Icon, Meter, Panel, SearchField, SectionHeader, StatRow, Tabs, VirtualList } from './primitives';
import { ResourceState, CommandButton } from './systemSupport';
import { CharacterPreview, type Appearance } from './Inventory';
import { useInteractions } from './interactions';
export function CharacterWindow() {
  const appearance = useGameChannel<Appearance | null>('appearance', null);
  const stats = useGameChannel<CombatSnapshot | null>('combat', null);
  const xp = useGameChannel('xp', null); const inventory = useGameChannel('inventory', null);
  const snapshot = useMemo(() => readCharacter(stats || undefined), [stats, xp, inventory]);
  const [tab, setTab] = useState('Attributes');
  return <div className="sui-split"><div><h3 className="sui-character-name">{appearance?.name || 'Character'}</h3><small>Scholomance · Language made manifest</small><CharacterPreview /><Panel inset title="Identity"><StatRow label="Form" value={appearance?.assetId || 'Awaiting world'} /><StatRow label="Equipment" value={`${snapshot.equipment.equippedCount} bound`} /></Panel></div><div><Tabs options={['Attributes', 'Combat', 'Equipment']} value={tab} onChange={setTab} />{tab === 'Attributes' && snapshot.scholomance.categories.map((category: any) => <section key={category.id}><SectionHeader title={category.label} />{category.stats.map((stat: any) => <div key={stat.key}><StatRow label={stat.fullName} value={stat.value} description={stat.coreFunction} /><Meter label={`Rank ${stat.level} progress`} value={stat.xpProgress} max={100} subtle /></div>)}</section>)}{tab === 'Combat' && (stats ? snapshot.tactical.rows.map((stat: any) => <StatRow key={stat.key} label={stat.label} value={stat.value} description={stat.description} />) : <EmptyState title="No active combat">Combat statistics appear when this world supplies them.</EmptyState>)}{tab === 'Equipment' && snapshot.equipment.rows.map((row: any) => <StatRow key={row.slotId} label={row.slotLabel} value={row.item.name} />)}</div></div>;
}
export function RegistryWindow({ system }: { system: string }) {
  const resource = useSystem(system); const [search, setSearch] = useState(''); const [category, setCategory] = useState('All'); const [selected, setSelected] = useState<string>();
  const entries = resource.data.entries || [];
  const filtered = entries.filter(entry => !entry.hidden && (category === 'All' || entry.category === category) && `${entry.name} ${entry.description || ''}`.toLowerCase().includes(search.toLowerCase()));
  const item = entries.find(entry => entry.id === selected) || filtered[0];
  return <ResourceState resource={resource}><SearchField value={search} onChange={setSearch} label={`Search ${system}`} /><Tabs options={['All', ...new Set(entries.map(entry => entry.category))]} value={category} onChange={setCategory} />{filtered.length ? <div className="sui-split"><VirtualList items={filtered} selected={item?.id} label={system} onSelect={entry => setSelected(entry.id)} render={entry => <><b>{entry.name}</b><small>{entry.category} · {entry.status || 'Discovered'}</small></>} /><Panel inset>{item && <><h3 className="sui-character-name">{item.name}</h3><Badge>{item.category}</Badge><p>{item.description}</p>{item.progress !== undefined && <Meter label="Progress" value={item.progress} max={item.total || 100} />}{item.stats?.map(stat => <StatRow key={stat.id || stat.label} {...stat} />)}{item.rewards?.length ? <p>Rewards: {item.rewards.join(', ')}</p> : null}{item.completedAt && <p>Completed {item.completedAt}</p>}<div className="sui-toolbar">{item.tags?.map(tag => <Badge key={tag}>{tag}</Badge>)}</div><CommandButton system={system} command="select" args={{ id: item.id }}>Select</CommandButton></>}</Panel></div> : <EmptyState title="No matching records">Try another category or search.</EmptyState>}</ResourceState>;
}
export function AbilityWindow() {
  const resource = useSystem('abilities'); const api = useInteractions(); const [search, setSearch] = useState(''); const [category, setCategory] = useState('All'); const [selection, setSelection] = useState<string>();
  const entries = resource.data.abilities || [];
  const rows = entries.filter(a => (category === 'All' || a.category === category) && a.name.toLowerCase().includes(search.toLowerCase()));
  const ability = entries.find(a => a.id === selection) || rows[0];
  const pickup = (a: Ability) => api.pickup({ kind: 'ability', id: a.id, source: 'abilities', revision: resource.revision });
  return <ResourceState resource={resource}><SearchField value={search} onChange={setSearch} label="Search abilities" /><Tabs value={category} onChange={setCategory} options={['All', ...new Set(entries.map(a => a.category))]} /><div className="sui-split"><VirtualList items={rows} label="Abilities" selected={ability?.id} onSelect={a => setSelection(a.id)} render={a => <><b>{a.name}</b><small>{a.unlocked ? a.passive ? 'Passive' : 'Active' : 'Locked'} · {a.category}</small></>} />{ability ? <Panel inset><h3 className="sui-character-name">{ability.name}</h3><Badge>{ability.unlocked ? 'Unlocked' : 'Locked'}</Badge><p>{ability.description}</p>{[['Resource', ability.cost], ['Cooldown', ability.cooldown], ['Cast time', ability.castTime], ['Range', ability.range], ['Rank', ability.rank]].filter(([, value]) => value !== undefined).map(([label, value]) => <StatRow key={label} label={String(label)} value={String(value)} />)}<div className="sui-toolbar">{ability.tags?.map(tag => <Badge key={tag}>{tag}</Badge>)}</div><Button draggable={ability.unlocked && !ability.passive} onDragStart={e => { pickup(ability); e.dataTransfer.setData('text/plain', ability.id); }} onDragEnd={api.cancel} disabled={!ability.unlocked || ability.passive} onClick={() => pickup(ability)}><Icon name="move" />Place on action bar</Button><CommandButton system="abilities" command="upgrade" args={{ id: ability.id }}>Upgrade rank</CommandButton></Panel> : <EmptyState title="No abilities">Discover abilities through play.</EmptyState>}</div></ResourceState>;
}
export function QuestWindow() {
  const resource = useSystem('quests'); const [search, setSearch] = useState(''); const [category, setCategory] = useState('All'); const [selected, setSelected] = useState<string>(); const api = useInteractions();
  const quests = resource.data.quests || [];
  const filtered = quests.filter(q => (category === 'All' || q.category === category) && q.name.toLowerCase().includes(search.toLowerCase()));
  const quest = quests.find(q => q.id === selected) || filtered[0];
  return <ResourceState resource={resource}><SearchField value={search} onChange={setSearch} label="Search quests" /><Tabs options={['All', ...new Set(quests.map(q => q.category))]} value={category} onChange={setCategory} /><div className="sui-split"><VirtualList items={filtered} label="Quest journal" selected={quest?.id} onSelect={q => setSelected(q.id)} render={q => <><b>{q.tracked ? '◇ ' : ''}{q.name}</b><small>{q.region} · {q.status || q.category}</small></>} />{quest ? <QuestDetails quest={quest} onMap={() => api.window({ type: 'open', id: 'map' })} /> : <EmptyState title="Journal empty">Accepted quests appear here.</EmptyState>}</div></ResourceState>;
}
function QuestDetails({ quest, onMap }: { quest: Quest; onMap: () => void }) { return <Panel inset><h3 className="sui-character-name">{quest.name}</h3><div className="sui-toolbar"><Badge>{quest.category}</Badge>{quest.difficulty && <Badge>{quest.difficulty}</Badge>}{quest.recommendedLevel !== undefined && <Badge>Level {quest.recommendedLevel}</Badge>}</div><p>{quest.description}</p><SectionHeader title="Objectives" />{quest.objectives?.map(objective => <div key={objective.id}><p>{objective.complete ? '✓' : '◇'} {objective.label}</p>{objective.children?.map(child => <small key={child}>{child}<br /></small>)}</div>)}{quest.giver && <StatRow label="Quest giver" value={quest.giver} />}{quest.destination && <StatRow label="Destination" value={quest.destination} />}{quest.timer && <StatRow label="Remaining" value={quest.timer} />}{quest.rewards?.length ? <p>Rewards: {quest.rewards.join(', ')}</p> : null}<div className="sui-toolbar"><CommandButton system="quests" command="track" args={{ id: quest.id, tracked: !quest.tracked }}>{quest.tracked ? 'Untrack' : 'Track quest'}</CommandButton><Button onClick={onMap}>Open map</Button><CommandButton system="quests" command="abandon" args={{ id: quest.id }} confirm>Abandon</CommandButton></div></Panel>; }
export function TreeNode({ node }: { node: RegistryEntry }) { return <details><summary>{node.name} {node.status && <Badge>{node.status}</Badge>}</summary><p>{node.description}</p>{node.children?.map(child => <TreeNode key={child.id} node={child} />)}</details>; }
