/**
 * Scene Manifest contracts — PDR §15
 *
 * The scene manifest is a deterministic visual projection of room state.
 * It is generated by the scene compiler and consumed by the renderer.
 * "The world produces the picture. The picture does not produce the world."
 *
 * Milestone 4 aligns this contract with PDR §15.2: a manifest carries
 * layers, interactable hotspots, text regions, a visual revision, and a
 * deterministic contract hash. The same room state + compiler version must
 * always yield the same contractHash (§15.4).
 */

import { z } from "zod";

// --- Visual Layers (§15.3) ---

export const SceneLayerTypeSchema = z.enum([
  "background",
  "entity",
  "prop",
  "lighting",
  "effect",
  "hotspot",
  "player-marker",
]);
export type SceneLayerType = z.infer<typeof SceneLayerTypeSchema>;

export const SceneLayerSchema = z.object({
  layerId: z.string(),
  layerType: SceneLayerTypeSchema,
  assetKey: z.string().nullable(),
  position: z.object({ x: z.number(), y: z.number() }),
  zIndex: z.number().int(),
  visible: z.boolean(),
  flags: z.record(z.string(), z.union([z.boolean(), z.string(), z.number()])),
});
export type SceneLayer = z.infer<typeof SceneLayerSchema>;

// --- Interactable Hotspots (§5.3, §15.2, §16.1) ---

export const SceneHotspotSchema = z.object({
  hotspotId: z.string(),
  entityId: z.string(),
  label: z.string(),
  /** Suggested command the hotspot maps to, e.g. "light brazier". */
  command: z.string(),
  region: z.object({
    x: z.number(),
    y: z.number(),
    w: z.number(),
    h: z.number(),
  }),
  visible: z.boolean(),
});
export type SceneHotspot = z.infer<typeof SceneHotspotSchema>;

// --- Text Regions (§15.2, §16.2) ---

export const SceneTextRegionKindSchema = z.enum([
  "title",
  "description",
  "narrative",
  "entity-label",
]);
export type SceneTextRegionKind = z.infer<typeof SceneTextRegionKindSchema>;

export const SceneTextRegionSchema = z.object({
  regionId: z.string(),
  kind: SceneTextRegionKindSchema,
  anchor: z.object({ x: z.number(), y: z.number() }),
  width: z.number().nonnegative(),
  text: z.string(),
});
export type SceneTextRegion = z.infer<typeof SceneTextRegionSchema>;

// --- Scene Manifest (§15.2) ---

export const SceneManifestSchema = z.object({
  /** Stable scene identifier (`<roomId>_rev<roomRevision>`). */
  sceneId: z.string(),
  roomId: z.string(),
  roomRevision: z.number().int().nonnegative(),
  /**
   * Revision of the visual contract. Because a manifest is a pure projection
   * of room state, it advances exactly when the room revision does.
   */
  visualRevision: z.number().int().nonnegative(),
  worldId: z.string(),
  backgroundAssetKey: z.string(),
  layers: z.array(SceneLayerSchema),
  hotspots: z.array(SceneHotspotSchema),
  textRegions: z.array(SceneTextRegionSchema),
  lightingState: z.string(),
  ambientEffects: z.array(z.string()),
  /** Deterministic hash of the visual contract (§15.4). Excludes generatedAt. */
  contractHash: z.string(),
  generatedAt: z.string().datetime(),
});
export type SceneManifest = z.infer<typeof SceneManifestSchema>;
