import { generateCSS } from './style-dictionary';
import { applyDerivedTransforms } from './theme-transforms';
import { assertThemeParity } from './theme-parity';
import type { DTCGDictionary } from './index';

/** Public CSS vars → Compose semantic vars (stable names). */
export const PUBLIC_THEME_ALIASES: Record<string, string> = {
  '--bg-void': '--compose-color-surface-bg',
  '--bg-deep': '--compose-color-surface-bg-soft',
  '--bg-surface': '--compose-color-surface-default',
  '--bg-elevated': '--compose-color-surface-elevated',
  '--ritual-abyss': '--compose-color-surface-canvas',
  '--text-primary': '--compose-color-text-primary',
  '--text-secondary': '--compose-color-text-secondary',
  '--text-tertiary': '--compose-color-text-tertiary',
  '--text-muted': '--compose-color-text-muted',
  '--border-subtle': '--compose-color-border-subtle',
  '--border-soft': '--compose-color-border-soft',
  '--border-bold': '--compose-color-border-bold',
  '--border-glow': '--compose-color-border-strong',
};

function stripRootWrapper(css: string): string {
  return css.replace(/^:root\s*\{\n?/, '').replace(/\n?\}\s*$/, '');
}

function aliasBlock(): string {
  return Object.entries(PUBLIC_THEME_ALIASES)
    .map(([pub, compose]) => `  ${pub}: var(${compose});`)
    .join('\n');
}

export function generateThemeCSS(dark: DTCGDictionary, light: DTCGDictionary): string {
  const parity = assertThemeParity(dark, light);
  if (!parity.ok) {
    throw new Error(
      `Theme parity failed. missingInDark=${parity.missingInDark.join(',')} missingInLight=${parity.missingInLight.join(',')}`,
    );
  }

  const darkResolved = applyDerivedTransforms(dark);
  const lightResolved = applyDerivedTransforms(light);
  const darkBody = stripRootWrapper(generateCSS(darkResolved));
  const lightBody = stripRootWrapper(generateCSS(lightResolved));
  const aliases = aliasBlock();

  return [
    "/* AUTO-GENERATED by scripts/generate-compose-themes.mjs — do not edit */",
    `:root,`,
    `[data-theme='dark'] {`,
    `  color-scheme: dark;`,
    darkBody,
    aliases,
    `}`,
    ``,
    `[data-theme='light'] {`,
    `  color-scheme: light;`,
    lightBody,
    aliases,
    `}`,
    ``,
  ].join('\n');
}
