/**
 * Pilot query bank for gold adjudication.
 *
 * Contexts are written so a human can often recover the intended sense
 * even when the gloss shares no content word with the query — the
 * regime where the current probe refuses. Heads are explicit so rarest-
 * token selection cannot silently retarget the inquiry.
 *
 * Avoids phraseAnalysis craft-instruction / comparison trigger words.
 *
 * @module codex/research/semantic-adjudication/seed-queries
 */

function expand(head, queries) {
  return queries.map((query) => ({ query, head }));
}

export const SEED_QUERIES = Object.freeze([
  ...expand('bank', [
    'loan from the bank',
    'teller at the bank',
    'credit at the bank',
    'grassy bank of the stream',
    'picnic on the bank',
    'anglers on the bank',
    'reserve in the bank',
    'blood stored in the bank',
  ]),
  ...expand('crane', [
    'steel lifted by the crane',
    'hooks on the crane',
    'wading crane in the marsh',
    'nest of the crane',
    'long neck of the crane',
  ]),
  ...expand('bark', [
    'the dog began to bark',
    'loud bark in the yard',
    'rough bark of the oak',
    'stripped bark from the trunk',
    'canoe of bark',
  ]),
  ...expand('bass', [
    'fried bass on the platter',
    'the angler caught a bass',
    'loud bass in the song',
    'bass solo in the hall',
    'deep bass of the choir',
  ]),
  ...expand('bat', [
    'the bat hung in the cave',
    'nocturnal bat over the trees',
    'wooden bat in the game',
    'swing of the bat',
    'cracked bat on the field',
  ]),
  ...expand('bear', [
    'the bear fished in the stream',
    'fur of the bear',
    'heavy load to bear',
    'too much pain to bear',
    'they could not bear the news',
  ]),
  ...expand('bow', [
    'arrow from the bow',
    'string of the bow',
    'deep bow before the king',
    'ribbon tied in a bow',
    'bow of the ship',
  ]),
  ...expand('box', [
    'wooden box of letters',
    'lid of the box',
    'fighters in the box',
    'they box every evening',
    'a box of tools',
  ]),
  ...expand('case', [
    'leather case for the glasses',
    'closed the case',
    'legal case in court',
    'the case went to trial',
    'a case of measles',
  ]),
  ...expand('cell', [
    'prison cell with bars',
    'locked in a cell',
    'living cell under the lens',
    'blood cell in the sample',
    'cell of the honeycomb',
  ]),
  ...expand('charge', [
    'the cavalry began to charge',
    'sudden charge across the field',
    'fee and charge on the bill',
    'electrical charge in the wire',
    'they charge a small fee',
  ]),
  ...expand('check', [
    'write a check for the rent',
    'cashed the check',
    'a check of the figures',
    'they check the list',
    'pattern of check on the cloth',
  ]),
  ...expand('club', [
    'members of the club',
    'evening at the club',
    'wooden club in his hand',
    'struck with a club',
    'the club met at dusk',
  ]),
  ...expand('court', [
    'judge in the court',
    'trial at court',
    'tennis court at dawn',
    'royal court of the king',
    'they court the voters',
  ]),
  ...expand('current', [
    'swift current in the river',
    'dangerous current near the rocks',
    'current of the times',
    'electrical current in the wire',
    'current issue of the paper',
  ]),
  ...expand('date', [
    'they date every friday',
    'a date at the cafe',
    'date on the letter',
    'sweet date from the palm',
    'the date of the battle',
  ]),
  ...expand('deck', [
    'sailors on the deck',
    'wet deck of the ship',
    'deck of cards',
    'shuffled the deck',
    'wooden deck behind the house',
  ]),
  ...expand('draft', [
    'first draft of the poem',
    'rough draft on the desk',
    'cold draft from the window',
    'military draft in wartime',
    'draft of beer',
  ]),
  ...expand('duck', [
    'the duck swam in the pond',
    'feathers of the duck',
    'they duck under the beam',
    'a quick duck of the head',
    'roast duck at supper',
  ]),
  ...expand('fair', [
    'county fair in autumn',
    'rides at the fair',
    'fair weather after rain',
    'a fair ruling by the judge',
    'fair hair in the sun',
  ]),
  ...expand('file', [
    'papers in the file',
    'steel file on the bench',
    'they file the edge',
    'single file on the path',
    'file of soldiers',
  ]),
  ...expand('fine', [
    'paid a fine at court',
    'parking fine on the glass',
    'fine cloth from the loom',
    'fine rain in the evening',
    'a fine distinction',
  ]),
  ...expand('firm', [
    'law firm in the city',
    'partners of the firm',
    'firm ground underfoot',
    'firm handshake',
    'firm belief in the cause',
  ]),
  ...expand('flat', [
    'rented a flat in town',
    'the flat was quiet',
    'flat land by the river',
    'a flat note in the song',
    'flat tire on the road',
  ]),
  ...expand('fly', [
    'the fly landed on the bread',
    'wings of the fly',
    'eagles fly over the ridge',
    'they fly south in winter',
    'a high fly to the outfield',
  ]),
  ...expand('fold', [
    'a fold in the cloth',
    'they fold the letter',
    'sheep in the fold',
    'the fold of the hills',
    'a fold of paper',
  ]),
  ...expand('foot', [
    'sore foot after the climb',
    'foot of the mountain',
    'they foot the bill',
    'a foot of snow',
    'foot of the bed',
  ]),
  ...expand('game', [
    'the game ended at dusk',
    'rules of the game',
    'wild game in the forest',
    'they hunt game',
    'a game smile',
  ]),
  ...expand('glass', [
    'a glass of water',
    'broken glass on the floor',
    'pane of glass',
    'reading glass on the desk',
    'glass of the greenhouse',
  ]),
  ...expand('harbor', [
    'ships in the harbor',
    'fog over the harbor',
    'they harbor a secret',
    'harbor of refuge',
    'the harbor was still',
  ]),
  ...expand('head', [
    'head of the table',
    'head of the school',
    'they head north at dawn',
    'a wound to the head',
    'head of the river',
  ]),
  ...expand('interest', [
    'interest on the loan',
    'rate of interest',
    'a keen interest in stars',
    'they lost interest',
    'public interest in the case',
  ]),
  ...expand('iron', [
    'hot iron on the cloth',
    'they iron the shirt',
    'iron in the earth',
    'an iron will',
    'bar of iron',
  ]),
  ...expand('jam', [
    'jar of jam',
    'sweet jam on bread',
    'traffic jam on the bridge',
    'they jam the door',
    'a jam of logs',
  ]),
  ...expand('jar', [
    'glass jar of honey',
    'lid of the jar',
    'the blow did jar him',
    'a jar of the nerves',
    'they jar against each other',
  ]),
  ...expand('key', [
    'iron key in the lock',
    'lost the key',
    'key of the song',
    'key to the puzzle',
    'a key point in the speech',
  ]),
  ...expand('kind', [
    'a kind word',
    'kind to the stranger',
    'what kind of stone',
    'every kind of bird',
    'kind of the old tales',
  ]),
  ...expand('letter', [
    'sealed letter on the desk',
    'posted the letter',
    'a letter of the alphabet',
    'capital letter',
    'letter of introduction',
  ]),
  ...expand('light', [
    'a light in the window',
    'faint light at dawn',
    'light as a feather',
    'they light the lamp',
    'light of the moon',
  ]),
  ...expand('match', [
    'struck a match',
    'wooden match in the box',
    'the match ended in a draw',
    'a match of wits',
    'they match the colors',
  ]),
  ...expand('mint', [
    'fresh mint in the tea',
    'leaves of mint',
    'the mint struck coins',
    'a mint of money',
    'in mint condition',
  ]),
  ...expand('mole', [
    'the mole dug in the lawn',
    'fur of the mole',
    'a mole on the skin',
    'secret mole in the court',
    'mole of the harbor',
  ]),
  ...expand('nail', [
    'iron nail in the board',
    'they nail the plank',
    'nail of the finger',
    'broken nail',
    'a nail in the coffin',
  ]),
  ...expand('note', [
    'a note on the door',
    'short note of thanks',
    'a note in the song',
    'high note of the choir',
    'they note the error',
  ]),
  ...expand('object', [
    'a small object on the table',
    'unknown object in the sky',
    'they object to the ruling',
    'object of the search',
    'the object of desire',
  ]),
  ...expand('park', [
    'children in the park',
    'trees of the park',
    'they park the cart',
    'a park of guns',
    'national park in the hills',
  ]),
  ...expand('pass', [
    'mountain pass in snow',
    'narrow pass between cliffs',
    'they pass the bread',
    'a pass to the hall',
    'the pass was refused',
  ]),
  ...expand('plant', [
    'water the plant',
    'green plant by the window',
    'the plant closed at dusk',
    'workers at the plant',
    'they plant the seed',
  ]),
  ...expand('play', [
    'children at play',
    'a play on the stage',
    'they play the game',
    'a play of light',
    'free play of the mind',
  ]),
  ...expand('pound', [
    'a pound of flour',
    'pound sterling',
    'they pound the grain',
    'a pound on the door',
    'stray dogs at the pound',
  ]),
  ...expand('present', [
    'a present for the child',
    'wrapped present',
    'they present the prize',
    'present at the gathering',
    'the present hour',
  ]),
  ...expand('race', [
    'the race began at dawn',
    'winner of the race',
    'a race of giants',
    'they race the horses',
    'human race on earth',
  ]),
  ...expand('rest', [
    'they rest at noon',
    'a short rest',
    'the rest of the bread',
    'rest of the company',
    'the rest was silence',
  ]),
  ...expand('ring', [
    'gold ring on the hand',
    'wedding ring',
    'they ring the bell',
    'a ring of trees',
    'the ring of steel',
  ]),
  ...expand('rock', [
    'a rock in the path',
    'they rock the cradle',
    'rock of the cliff',
    'loud rock in the hall',
    'rock and stone',
  ]),
  ...expand('rose', [
    'a rose in the garden',
    'scent of the rose',
    'they rose at dawn',
    'the river rose',
    'rose of the compass',
  ]),
  ...expand('row', [
    'a row of trees',
    'they row the boat',
    'a row on the water',
    'loud row in the street',
    'the back row',
  ]),
  ...expand('scale', [
    'scale of the fish',
    'they scale the fish',
    'a scale of notes',
    'scale of the map',
    'they scale the wall',
  ]),
  ...expand('seal', [
    'the seal swam near the ice',
    'fur of the seal',
    'wax seal on the letter',
    'they seal the jar',
    'the seal of office',
  ]),
  ...expand('sentence', [
    'a long sentence in prison',
    'the judge read the sentence',
    'ungrammatical sentence on the page',
    'first sentence of the book',
    'they sentence the thief',
  ]),
  ...expand('sink', [
    'water in the sink',
    'stone sink in the kitchen',
    'they sink the stone',
    'the ship began to sink',
    'a sink of vice',
  ]),
  ...expand('spring', [
    'cold spring in the hills',
    'water from the spring',
    'they spring from the ledge',
    'a spring in the lock',
    'spring after winter',
  ]),
  ...expand('staff', [
    'wooden staff in his hand',
    'leaned on the staff',
    'staff of the school',
    'the staff met at noon',
    'staff of office',
  ]),
  ...expand('stamp', [
    'postage stamp on the letter',
    'they stamp the paper',
    'a stamp of the foot',
    'official stamp',
    'stamp of the age',
  ]),
  ...expand('state', [
    'the state of the roads',
    'a state of unrest',
    'they state the facts',
    'the state raised a tax',
    'state of the union',
  ]),
  ...expand('stick', [
    'a stick of wood',
    'they stick the notice',
    'the wheels stick in mud',
    'walking stick',
    'a stick of wax',
  ]),
  ...expand('stock', [
    'stock on the shelf',
    'they stock the shop',
    'cattle stock in the field',
    'stock of the gun',
    'stock in the firm',
  ]),
  ...expand('story', [
    'a story by the fire',
    'old story of the king',
    'second story of the house',
    'the story above',
    'true story of the voyage',
  ]),
  ...expand('strike', [
    'the workers began to strike',
    'a strike at the plant',
    'they strike the bell',
    'a strike of lightning',
    'lucky strike',
  ]),
  ...expand('table', [
    'oak table in the hall',
    'they table the motion',
    'a table of figures',
    'set the table',
    'table of the law',
  ]),
  ...expand('tap', [
    'a tap on the door',
    'they tap the keg',
    'water from the tap',
    'a tap of the cane',
    'they tap the maple',
  ]),
  ...expand('tie', [
    'silk tie at the neck',
    'they tie the rope',
    'a tie in the race',
    'the game ended in a tie',
    'family tie',
  ]),
  ...expand('toast', [
    'burnt toast on the plate',
    'they toast the bread',
    'a toast to the host',
    'they toast the victor',
    'warm toast with jam',
  ]),
  ...expand('trip', [
    'a trip to the hills',
    'they trip on the stone',
    'a trip of the foot',
    'short trip by boat',
    'the trip lasted a week',
  ]),
  ...expand('watch', [
    'gold watch in the pocket',
    'they watch the road',
    'night watch on the wall',
    'a watch of sailors',
    'the watch struck twelve',
  ]),
  ...expand('wave', [
    'a wave on the shore',
    'they wave from the pier',
    'a wave of the hand',
    'heat wave in the valley',
    'wave of sound',
  ]),
  ...expand('well', [
    'water from the well',
    'deep well in the yard',
    'they well with tears',
    'all is well',
    'a well of memory',
  ]),
  ...expand('yard', [
    'children in the yard',
    'a yard of cloth',
    'ship in the yard',
    'the yard was quiet',
    'a yard of ale',
  ]),
  ...expand('wound', [
    'the wound healed',
    'a deep wound in the side',
    'they wound the clock',
    'he wound the coil',
    'linen around the wound',
  ]),
  ...expand('tear', [
    'a tear on the cheek',
    'they tear the cloth',
    'a tear in the sail',
    'bitter tear',
    'they tear down the hut',
  ]),
  ...expand('wind', [
    'cold wind from the north',
    'they wind the clock',
    'a wind in the pines',
    'they wind the path',
    'the wind rose',
  ]),
  ...expand('lead', [
    'they lead the horses',
    'a lead of two lengths',
    'heavy lead in the pipe',
    'lead of the roof',
    'the lead singer',
  ]),
  ...expand('close', [
    'they close the gate',
    'a close friend',
    'close of the day',
    'a close race',
    'the close of the letter',
  ]),
  ...expand('count', [
    'they count the coins',
    'a count of the votes',
    'the count entered the hall',
    'a noble count',
    'lost count of the days',
  ]),
  ...expand('draw', [
    'they draw the map',
    'a draw in the contest',
    'they draw water',
    'the draw of the bow',
    'a lucky draw',
  ]),
  ...expand('fall', [
    'leaves fall in autumn',
    'a fall from the wall',
    'the fall of the city',
    'they fall silent',
    'a fall of snow',
  ]),
  ...expand('hold', [
    'they hold the rope',
    'a hold on the cliff',
    'cargo in the hold',
    'the hold of the ship',
    'they hold the fort',
  ]),
  ...expand('leave', [
    'they leave at dawn',
    'a leave of absence',
    'the leave on the tree',
    'they leave a note',
    'granted leave',
  ]),
  ...expand('lie', [
    'they lie in the grass',
    'a lie on the tongue',
    'they lie about the gold',
    'the lie of the land',
    'a useful lie',
  ]),
  ...expand('mean', [
    'they mean no harm',
    'a mean remark',
    'the mean of the figures',
    'what they mean',
    'a mean street',
  ]),
  ...expand('raise', [
    'they raise the flag',
    'a raise in pay',
    'they raise cattle',
    'a raise of the voice',
    'they raise the question',
  ]),
  ...expand('saw', [
    'they saw the timber',
    'a saw on the bench',
    'they saw the ship',
    'the saw bit the wood',
    'old saw of the village',
  ]),
  ...expand('set', [
    'they set the table',
    'a set of tools',
    'the sun began to set',
    'a set of rules',
    'they set the type',
  ]),
  ...expand('can', [
    'a can of beans',
    'they can the fruit',
    'tin can on the shelf',
    'they can leave at dusk',
    'a dented can',
  ]),
  ...expand('may', [
    'blossoms of the may',
    'a day in may',
    'they may arrive at dusk',
    'hawthorn in may',
    'the first of may',
  ]),
  ...expand('will', [
    'last will of the elder',
    'they will arrive at dusk',
    'the will to live',
    'iron will',
    'they read the will',
  ]),
  ...expand('page', [
    'a page of the book',
    'torn page',
    'the page announced the king',
    'a young page at court',
    'they page the doctor',
  ]),
  ...expand('plain', [
    'wide plain of grass',
    'a plain answer',
    'plain cloth',
    'they crossed the plain',
    'the plain truth',
  ]),
  ...expand('right', [
    'the right hand',
    'a right to speak',
    'they right the boat',
    'the right path',
    'in the right',
  ]),
  ...expand('left', [
    'the left hand',
    'they left at dawn',
    'what they left',
    'a left turn',
    'the left bank',
  ]),
  ...expand('mine', [
    'a mine in the hills',
    'they mine the ore',
    'the mine collapsed',
    'a mine of stories',
    'this book is mine',
  ]),
  ...expand('net', [
    'a net in the water',
    'they net the fish',
    'a net of lies',
    'the net profit',
    'torn net',
  ]),
  ...expand('pen', [
    'a pen on the desk',
    'they pen the letter',
    'sheep in the pen',
    'they pen the flock',
    'ink of the pen',
  ]),
  ...expand('pool', [
    'a pool of water',
    'they pool the coins',
    'swimmers in the pool',
    'a pool of blood',
    'the pool was still',
  ]),
  ...expand('port', [
    'ships in the port',
    'a port of call',
    'port side of the ship',
    'they port the gun',
    'sweet port in the glass',
  ]),
  ...expand('post', [
    'a post in the ground',
    'they post the letter',
    'a post at the court',
    'the last post',
    'wooden post',
  ]),
  ...expand('press', [
    'they press the grapes',
    'a press of the crowd',
    'the press printed the news',
    'a press of business',
    'iron press',
  ]),
  ...expand('quarter', [
    'a quarter of the loaf',
    'they quarter the apple',
    'the old quarter of the city',
    'a quarter of an hour',
    'they quarter the troops',
  ]),
  ...expand('rash', [
    'a rash on the skin',
    'a rash decision',
    'they were rash',
    'heat rash',
    'a rash of thefts',
  ]),
  ...expand('rule', [
    'a rule of the house',
    'they rule the land',
    'a wooden rule',
    'the golden rule',
    'they rule the line',
  ]),
  ...expand('season', [
    'the dry season',
    'they season the stew',
    'a season of rain',
    'in season',
    'the season of the hunt',
  ]),
  ...expand('sound', [
    'a sound in the night',
    'they sound the horn',
    'sound of the sea',
    'a sound argument',
    'the sound between the isles',
  ]),
  ...expand('space', [
    'a space on the shelf',
    'they space the trees',
    'empty space',
    'a space of time',
    'the wide space of the sky',
  ]),
  ...expand('spell', [
    'a spell of rain',
    'they spell the word',
    'a magic spell',
    'under a spell',
    'a spell at the oars',
  ]),
  ...expand('spot', [
    'a spot of ink',
    'they spot the ship',
    'a quiet spot',
    'a spot of rain',
    'the weak spot',
  ]),
  ...expand('stable', [
    'horses in the stable',
    'a stable door',
    'stable ground',
    'a stable mind',
    'the stable was dark',
  ]),
  ...expand('stem', [
    'stem of the rose',
    'they stem the flood',
    'the stem of the ship',
    'a stem of glass',
    'they stem from the hills',
  ]),
  ...expand('stern', [
    'stern of the ship',
    'a stern look',
    'they stood at the stern',
    'stern weather',
    'the stern judge',
  ]),
  ...expand('strain', [
    'a strain of music',
    'they strain the soup',
    'a strain of the voice',
    'the strain of the work',
    'they strain against the rope',
  ]),
  ...expand('swallow', [
    'the swallow flew low',
    'nest of the swallow',
    'they swallow the bread',
    'a swallow of water',
    'hard to swallow',
  ]),
  ...expand('temple', [
    'the old temple on the hill',
    'priests of the temple',
    'a blow to the temple',
    'gray at the temple',
    'the temple stood empty',
  ]),
  ...expand('tender', [
    'a tender word',
    'they tender the fare',
    'tender meat',
    'the ship and her tender',
    'a legal tender',
  ]),
  ...expand('trace', [
    'a trace of snow',
    'they trace the path',
    'no trace of the thief',
    'a trace of sadness',
    'they trace the letters',
  ]),
  ...expand('train', [
    'the train left at dawn',
    'they train the horses',
    'a train of thought',
    'the train of the gown',
    'a long train',
  ]),
  ...expand('vault', [
    'gold in the vault',
    'they vault the wall',
    'a stone vault',
    'the vault of the sky',
    'they vaulted the gate',
  ]),
  ...expand('vice', [
    'a vice of the age',
    'iron vice on the bench',
    'they vice the board',
    'a private vice',
    'the vice of drink',
  ]),
  ...expand('volume', [
    'a volume of verse',
    'the volume of the river',
    'loud volume',
    'a second volume',
    'the volume of trade',
  ]),
  ...expand('wake', [
    'they wake at dawn',
    'a wake behind the ship',
    'the wake of the storm',
    'a wake for the dead',
    'in the wake of war',
  ]),
  ...expand('waste', [
    'they waste the hours',
    'a waste of land',
    'the waste of war',
    'they waste the water',
    'barren waste',
  ]),
  ...expand('yardarm', [
    'sail from the yardarm',
    'the yardarm swung',
  ]),
  ...expand('crane', [
    'they crane the neck',
    'a crane over the dock',
  ]),
  ...expand('bank', [
    'fog on the river bank',
    'they bank the fire',
    'a bank of cloud',
    'they bank the plane',
  ]),
]);
