import {
  mkdir,
  readFile,
  readdir,
  unlink,
  writeFile,
} from "node:fs/promises";
import { basename, isAbsolute, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import {
  computePngRevision,
  processPixelBrainPacket,
  toHexRgba,
} from "@polaris/pixelbrain-bridge";

export interface PixelBrainAssetRegistryEntry {
  assetKey: string;
  pixelBrainUrl?: string;
  expectedPacketContentHash?: `pb1:${string}`;
  pngUrl?: string;
  expectedPngHash?: `png1:${string}`;
}

export type PixelBrainAssetRegistry = Record<
  string,
  PixelBrainAssetRegistryEntry
>;

export interface BuildPixelBrainAssetsOptions {
  sourceDir: string;
  publicDir: string;
  registryFile: string;
}

export interface BuildPixelBrainAssetsResult {
  registry: PixelBrainAssetRegistry;
  files: readonly string[];
}

interface SourceEnvelope {
  assetKey: string;
  packet: unknown;
  pngFile?: string;
}

interface GeneratedManifest {
  version: 1;
  files: string[];
}

const MANIFEST_FILENAME = "generated-file-manifest.json";

function normalizedRenderPacket(
  packet: ReturnType<typeof processPixelBrainPacket> & { ok: true },
): Record<string, unknown> {
  return {
    kind: packet.packet.packetVersion,
    id: packet.packet.packetId,
    schemaVersion: packet.packet.schemaVersion,
    contentHash: packet.packet.packetContentHash,
    canvas: {
      width: packet.packet.width,
      height: packet.packet.height,
      cellSize: packet.packet.cellSize,
      transparent: packet.packet.transparent,
      background: toHexRgba(packet.packet.background),
    },
    coordinates: packet.packet.cells.map(({ x, y, z, rgba }) => ({
      snappedX: x,
      snappedY: y,
      z,
      color: toHexRgba(rgba),
    })),
  };
}

function registrySource(registry: PixelBrainAssetRegistry): string {
  return `/**
 * Generated by scripts/build-pixelbrain-assets.ts.
 * Do not edit by hand.
 */
export interface PixelBrainAssetRegistryEntry {
  readonly assetKey: string;
  readonly pixelBrainUrl?: string;
  readonly expectedPacketContentHash?: \`pb1:\${string}\`;
  readonly pngUrl?: string;
  readonly expectedPngHash?: \`png1:\${string}\`;
}

export type PixelBrainAssetRegistry = Readonly<
  Record<string, PixelBrainAssetRegistryEntry>
>;

export const pixelBrainAssetRegistry = ${JSON.stringify(registry, null, 2)} as const satisfies PixelBrainAssetRegistry;
`;
}

function assertEnvelope(value: unknown, filename: string): SourceEnvelope {
  if (
    typeof value !== "object"
    || value === null
    || Array.isArray(value)
  ) {
    throw new Error(`${filename}: source envelope must be an object`);
  }
  const record = value as Record<string, unknown>;
  if (
    typeof record.assetKey !== "string"
    || record.assetKey.trim().length === 0
  ) {
    throw new Error(`${filename}: assetKey must be a non-empty string`);
  }
  if (!("packet" in record)) {
    throw new Error(`${filename}: packet is required`);
  }
  if (record.pngFile !== undefined && typeof record.pngFile !== "string") {
    throw new Error(`${filename}: pngFile must be a string`);
  }
  return {
    assetKey: record.assetKey,
    packet: record.packet,
    ...(typeof record.pngFile === "string"
      ? { pngFile: record.pngFile }
      : {}),
  };
}

function assetStem(filename: string): string {
  return basename(filename).replace(/\.pixelbrain\.json$/u, "");
}

function safePngPath(sourceDir: string, pngFile: string): string {
  if (isAbsolute(pngFile)) {
    throw new Error(`pngFile must be relative: ${pngFile}`);
  }
  const resolved = resolve(sourceDir, pngFile);
  const relation = relative(resolve(sourceDir), resolved);
  if (relation.startsWith("..") || isAbsolute(relation)) {
    throw new Error(`pngFile escapes source directory: ${pngFile}`);
  }
  return resolved;
}

async function removeStaleFiles(
  publicDir: string,
  currentFiles: ReadonlySet<string>,
): Promise<void> {
  try {
    const value = JSON.parse(
      await readFile(resolve(publicDir, MANIFEST_FILENAME), "utf8"),
    ) as Partial<GeneratedManifest>;
    if (!Array.isArray(value.files)) return;
    await Promise.all(value.files
      .filter((filename) => (
        typeof filename === "string" && !currentFiles.has(filename)
      ))
      .map(async (filename) => {
        if (basename(filename) !== filename) return;
        try {
          await unlink(resolve(publicDir, filename));
        } catch (cause) {
          if (
            !(cause instanceof Error)
            || !("code" in cause)
            || cause.code !== "ENOENT"
          ) {
            throw cause;
          }
        }
      }));
  } catch (cause) {
    if (
      cause instanceof SyntaxError
      || (
        cause instanceof Error
        && "code" in cause
        && cause.code === "ENOENT"
      )
    ) {
      return;
    }
    throw cause;
  }
}

export async function buildPixelBrainAssets(
  options: BuildPixelBrainAssetsOptions,
): Promise<BuildPixelBrainAssetsResult> {
  const sourceNames = (await readdir(options.sourceDir))
    .filter((name) => name.endsWith(".pixelbrain.json"))
    .sort();
  const registry: PixelBrainAssetRegistry = {};
  const generated = new Map<string, Uint8Array>();
  const utf8 = new TextEncoder();

  for (const sourceName of sourceNames) {
    const sourcePath = resolve(options.sourceDir, sourceName);
    const envelope = assertEnvelope(
      JSON.parse(await readFile(sourcePath, "utf8")) as unknown,
      sourceName,
    );
    if (registry[envelope.assetKey] !== undefined) {
      throw new Error(`duplicate assetKey: ${envelope.assetKey}`);
    }

    const processed = processPixelBrainPacket(envelope.packet);
    if (!processed.ok) {
      const details = processed.diagnostics
        .map(({ code, detail }) => `${code}: ${detail}`)
        .join("; ");
      throw new Error(`${sourceName}: ${details}`);
    }

    const stem = assetStem(sourceName);
    const packetDigest = processed.packet.packetContentHash.slice(4);
    const packetFilename =
      `${stem}.pb1-${packetDigest}.pixelbrain.json`;
    generated.set(
      packetFilename,
      utf8.encode(`${JSON.stringify(normalizedRenderPacket(processed), null, 2)}\n`),
    );

    const entry: PixelBrainAssetRegistryEntry = {
      assetKey: envelope.assetKey,
      pixelBrainUrl: `/assets/generated/${packetFilename}`,
      expectedPacketContentHash: processed.packet.packetContentHash,
    };

    if (envelope.pngFile !== undefined) {
      const pngBytes = new Uint8Array(
        await readFile(safePngPath(options.sourceDir, envelope.pngFile)),
      );
      const pngRevision = computePngRevision(pngBytes);
      const pngFilename = `${stem}.${pngRevision.replace(":", "-")}.png`;
      generated.set(pngFilename, pngBytes);
      entry.pngUrl = `/assets/generated/${pngFilename}`;
      entry.expectedPngHash = pngRevision;
    }
    registry[envelope.assetKey] = entry;
  }

  const sortedRegistry = Object.fromEntries(
    Object.entries(registry).sort(([left], [right]) => (
      left < right ? -1 : left > right ? 1 : 0
    )),
  );
  const filenames = [...generated.keys()].sort();
  await mkdir(options.publicDir, { recursive: true });
  await mkdir(resolve(options.registryFile, ".."), { recursive: true });
  await removeStaleFiles(options.publicDir, new Set(filenames));

  await Promise.all(filenames.map((filename) => (
    writeFile(resolve(options.publicDir, filename), generated.get(filename)!)
  )));
  const manifest: GeneratedManifest = { version: 1, files: filenames };
  await writeFile(
    resolve(options.publicDir, MANIFEST_FILENAME),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
  await writeFile(options.registryFile, registrySource(sortedRegistry));

  return {
    registry: sortedRegistry,
    files: filenames,
  };
}

async function main(): Promise<void> {
  const root = process.cwd();
  const result = await buildPixelBrainAssets({
    sourceDir: resolve(root, "worldpacks/shrine-demo/assets-src"),
    publicDir: resolve(root, "apps/client/public/assets/generated"),
    registryFile: resolve(
      root,
      "apps/client/src/generated/pixelbrainAssetRegistry.ts",
    ),
  });
  process.stdout.write(
    `Generated ${result.files.length} PixelBrain asset file(s).\n`,
  );
}

if (
  process.argv[1] !== undefined
  && import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  await main();
}
