/** @type {Array<[number, string, string[], Array<[string, string, boolean]>, string | null, string]>} */
const DEFINITIONS = [
  [0x0001, 'SCDL', ['PROGRAM'], [['VERSION', 'I32', true]], null, 'DECLARATION'],
  [0x0002, 'ASSET', ['PROGRAM'], [['ID', 'IDENT', true]], null, 'DECLARATION'],
  [0x0003, 'CANVAS', ['PROGRAM'], [['WIDTH', 'U32', true], ['HEIGHT', 'U32', true]], null, 'DECLARATION'],
  [0x0004, 'BUDGET', ['PROGRAM'], [['INSTRUCTIONS', 'U32', true], ['GENERATED_SHAPES', 'U32', true], ['RASTER_CELLS', 'U32', true], ['RECURSION_DEPTH', 'U32', false]], null, 'DECLARATION'],
  [0x0010, 'CONST', ['PROGRAM'], [['SYMBOL', 'SYMBOL', true], ['TYPE', 'TYPE', true], ['VALUE', 'EXPRESSION', true]], null, 'PURE'],
  [0x0020, 'SHAPE', ['PROGRAM'], [['SYMBOL', 'SYMBOL', true], ['VALUE', 'SHAPE', true]], 'SHAPE', 'PURE'],
  [0x0030, 'LAYER', ['PROGRAM'], [['ID', 'IDENT', true], ['ORDER', 'I32', true], ['BLEND', 'COMPOSITE_MODE', false], ['OPACITY', 'SCALAR', false], ['VISIBLE', 'BOOL', false], ['BODY', 'BLOCK', true]], 'LAYER', 'CONSTRUCTION'],
  [0x0031, 'PAINT', ['LAYER'], [['SHAPE', 'SHAPE', true], ['AT', 'VEC2', false], ['FILL', 'COLOR', true], ['RASTER', 'RASTER_POLICY', true], ['BLEND', 'COMPOSITE_MODE', false], ['CLIP_TO', 'MASK', false], ['MATERIAL', 'ANY', false], ['OPACITY', 'SCALAR', false]], null, 'CONSTRUCTION'],
  [0x0100, 'ADD', ['EXPRESSION'], [['LEFT', 'NUMERIC', true], ['RIGHT', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0101, 'SUB', ['EXPRESSION'], [['LEFT', 'NUMERIC', true], ['RIGHT', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0102, 'MUL', ['EXPRESSION'], [['LEFT', 'NUMERIC', true], ['RIGHT', 'NUMERIC', true]], 'PRODUCT', 'PURE'],
  [0x0103, 'DIV', ['EXPRESSION'], [['LEFT', 'NUMERIC', true], ['RIGHT', 'NUMERIC', true]], 'QUOTIENT', 'PURE'],
  [0x0110, 'PX', ['EXPRESSION'], [['VALUE', 'SCALAR', true]], 'PX', 'PURE'],
  [0x0111, 'VEC2', ['EXPRESSION'], [['X', 'PX', true], ['Y', 'PX', true]], 'VEC2', 'PURE'],
  [0x0200, 'PIXEL', ['EXPRESSION'], [['AT', 'VEC2', true]], 'SHAPE', 'PURE'],
  [0x0201, 'CIRCLE', ['EXPRESSION'], [['CENTER', 'VEC2', true], ['RADIUS', 'PX', true]], 'SHAPE', 'PURE'],
  [0x0021, 'MASK', ['PROGRAM'], [['SYMBOL', 'SYMBOL', true], ['VALUE', 'MASK', true]], 'MASK', 'PURE'],
  [0x0040, 'ANCHOR', ['PROGRAM'], [['SYMBOL', 'SYMBOL', true], ['ON', 'SHAPE', true], ['AT', 'ANY', true]], null, 'PURE'],
  [0x0041, 'ASSERT', ['PROGRAM'], [['CONDITION', 'EXPRESSION', true]], null, 'PURE'],
  [0x0202, 'LINE', ['EXPRESSION'], [['FROM', 'VEC2', true], ['TO', 'VEC2', true]], 'SHAPE', 'PURE'],
  [0x0203, 'POLYLINE', ['EXPRESSION'], [['POINTS', 'LIST<VEC2>', true]], 'SHAPE', 'PURE'],
  [0x0204, 'RAY', ['EXPRESSION'], [['ORIGIN', 'VEC2', true], ['DIR', 'VEC2', true], ['LENGTH', 'PX', true]], 'SHAPE', 'PURE'],
  [0x0205, 'RECT', ['EXPRESSION'], [['ORIGIN', 'VEC2', false], ['CENTER', 'VEC2', false], ['SIZE', 'VEC2', true]], 'SHAPE', 'PURE'],
  [0x0206, 'ROUNDED_RECT', ['EXPRESSION'], [['ORIGIN', 'VEC2', false], ['CENTER', 'VEC2', false], ['SIZE', 'VEC2', true], ['CORNER_RADIUS', 'PX', true]], 'SHAPE', 'PURE'],
  [0x0207, 'RING', ['EXPRESSION'], [['CENTER', 'VEC2', true], ['RADIUS', 'PX', true], ['THICKNESS', 'PX', true]], 'SHAPE', 'PURE'],
  [0x0208, 'ELLIPSE', ['EXPRESSION'], [['CENTER', 'VEC2', true], ['RADIUS_X', 'PX', true], ['RADIUS_Y', 'PX', true]], 'SHAPE', 'PURE'],
  [0x0209, 'ARC', ['EXPRESSION'], [['CENTER', 'VEC2', true], ['RADIUS', 'PX', true], ['START', 'ANGLE', true], ['END', 'ANGLE', true]], 'SHAPE', 'PURE'],
  [0x020A, 'SECTOR', ['EXPRESSION'], [['CENTER', 'VEC2', true], ['RADIUS', 'PX', true], ['START', 'ANGLE', true], ['END', 'ANGLE', true]], 'SHAPE', 'PURE'],
  [0x020B, 'TRIANGLE', ['EXPRESSION'], [['P1', 'VEC2', true], ['P2', 'VEC2', true], ['P3', 'VEC2', true]], 'SHAPE', 'PURE'],
  [0x020C, 'REGULAR_POLYGON', ['EXPRESSION'], [['SIDES', 'I32', true], ['RADIUS', 'PX', true], ['CENTER', 'VEC2', true]], 'SHAPE', 'PURE'],
  [0x020D, 'POLYGON', ['EXPRESSION'], [['VERTICES', 'LIST<VEC2>', true]], 'SHAPE', 'PURE'],
  [0x020E, 'STAR', ['EXPRESSION'], [['POINTS', 'I32', true], ['INNER_RADIUS', 'PX', true], ['OUTER_RADIUS', 'PX', true], ['CENTER', 'VEC2', true]], 'SHAPE', 'PURE'],
  [0x020F, 'PATH', ['EXPRESSION'], [['DATA', 'STRING', true]], 'SHAPE', 'PURE'],
  [0x0210, 'DEGREES', ['EXPRESSION'], [['VALUE', 'SCALAR', true]], 'ANGLE', 'PURE'],
  [0x0211, 'RADIANS', ['EXPRESSION'], [['VALUE', 'SCALAR', true]], 'ANGLE', 'PURE'],
  [0x0212, 'TURNS', ['EXPRESSION'], [['VALUE', 'SCALAR', true]], 'ANGLE', 'PURE'],
  [0x0213, 'ROTATE', ['EXPRESSION'], [['ANGLE', 'ANGLE', true], ['PIVOT', 'VEC2', false]], 'TRANSFORM', 'PURE'],
  [0x0214, 'TRANSLATE', ['EXPRESSION'], [['OFFSET', 'VEC2', true]], 'TRANSFORM', 'PURE'],
  [0x0215, 'SCALE', ['EXPRESSION'], [['FACTOR', 'SCALAR', true], ['PIVOT', 'VEC2', false]], 'TRANSFORM', 'PURE'],
  [0x0216, 'TRANSFORM_COMPOSE', ['EXPRESSION'], [['T1', 'TRANSFORM', true], ['T2', 'TRANSFORM', true]], 'TRANSFORM', 'PURE'],
  [0x0217, 'TRANSFORM_APPLY', ['EXPRESSION'], [['TRANSFORM', 'TRANSFORM', true], ['TARGET', 'ANY', true]], 'ANY', 'PURE'],
  [0x0218, 'TRANSFORM_MATRIX', ['EXPRESSION'], [
    ['A', 'SCALAR', true],
    ['C', 'SCALAR', true],
    ['TX', 'SCALAR', true],
    ['B', 'SCALAR', true],
    ['D', 'SCALAR', true],
    ['TY', 'SCALAR', true],
  ], 'TRANSFORM', 'PURE'],
  [0x0220, 'UNION', ['EXPRESSION'], [['A', 'SHAPE', true], ['B', 'SHAPE', true]], 'SHAPE', 'PURE'],
  [0x0221, 'SUBTRACT', ['EXPRESSION'], [['A', 'SHAPE', true], ['B', 'SHAPE', true]], 'SHAPE', 'PURE'],
  [0x0222, 'INTERSECT', ['EXPRESSION'], [['A', 'SHAPE', true], ['B', 'SHAPE', true]], 'SHAPE', 'PURE'],
  [0x0223, 'XOR', ['EXPRESSION'], [['A', 'SHAPE', true], ['B', 'SHAPE', true]], 'SHAPE', 'PURE'],
  [0x0224, 'OUTLINE', ['EXPRESSION'], [['SHAPE', 'SHAPE', true], ['WIDTH', 'PX', true]], 'SHAPE', 'PURE'],
  [0x0230, 'TO_MASK', ['EXPRESSION'], [['SHAPE', 'SHAPE', true], ['RASTER', 'RASTER_POLICY', false]], 'MASK', 'PURE'],
  [0x0231, 'MASK_UNION', ['EXPRESSION'], [['A', 'MASK', true], ['B', 'MASK', true]], 'MASK', 'PURE'],
  [0x0232, 'MASK_INTERSECT', ['EXPRESSION'], [['A', 'MASK', true], ['B', 'MASK', true]], 'MASK', 'PURE'],
  [0x0233, 'MASK_SUBTRACT', ['EXPRESSION'], [['A', 'MASK', true], ['B', 'MASK', true]], 'MASK', 'PURE'],
  [0x0234, 'MASK_INVERT', ['EXPRESSION'], [['MASK', 'MASK', true]], 'MASK', 'PURE'],
  [0x0240, 'ALIGN', ['EXPRESSION'], [['TARGET', 'SHAPE', true], ['ANCHOR', 'IDENT', true], ['TO', 'SHAPE', true], ['OFFSET', 'VEC2', false]], 'SHAPE', 'PURE'],
  [0x0241, 'ANCHOR_OF', ['EXPRESSION'], [['SHAPE', 'SHAPE', true], ['ANCHOR', 'IDENT', true]], 'VEC2', 'PURE'],
  [0x0242, 'BOUNDS', ['EXPRESSION'], [['TARGET', 'ANY', true]], 'RECT', 'PURE'],
  [0x0243, 'INSIDE', ['EXPRESSION'], [['POINT', 'VEC2', true], ['TARGET', 'ANY', true]], 'BOOL', 'PURE'],
  [0x0244, 'CONTAINS', ['EXPRESSION'], [['CONTAINER', 'ANY', true], ['CONTAINED', 'ANY', true]], 'BOOL', 'PURE'],
  [0x0245, 'TOUCHES', ['EXPRESSION'], [['A', 'ANY', true], ['B', 'ANY', true]], 'BOOL', 'PURE'],
  [0x0246, 'OVERLAPS', ['EXPRESSION'], [['A', 'ANY', true], ['B', 'ANY', true]], 'BOOL', 'PURE'],
  [0x0050, 'FN', ['PROGRAM'], [['ID', 'IDENT', true], ['PARAMS', 'LIST<PARAM>', false], ['RETURNS', 'TYPE', true], ['RECURSION_MAX', 'I32', false], ['BODY', 'BLOCK', true]], null, 'PURE'],
  [0x0051, 'SEQUENCE', ['PROGRAM'], [['SYMBOL', 'SYMBOL', true], ['TYPE', 'TYPE', true], ['COUNT', 'I32', true], ['BODY', 'BLOCK', true]], 'SEQUENCE', 'PURE'],
  [0x0052, 'RNG', ['PROGRAM'], [['SYMBOL', 'SYMBOL', true], ['ALGORITHM', 'IDENT', true], ['SEED', 'I32', true]], 'RNG', 'PURE'],
  [0x0053, 'LET', ['FUNCTION', 'BLOCK', 'SHAPE', 'LAYER'], [['SYMBOL', 'SYMBOL', true], ['TYPE', 'TYPE', true], ['VALUE', 'EXPRESSION', true]], null, 'PURE'],
  [0x0054, 'RETURN', ['FUNCTION', 'BLOCK'], [['VALUE', 'EXPRESSION', true]], null, 'PURE'],
  [0x0055, 'EMIT', ['SHAPE', 'BLOCK'], [['VALUE', 'EXPRESSION', true]], null, 'PURE'],
  [0x0056, 'FOR', ['SHAPE', 'LAYER', 'FUNCTION', 'BLOCK'], [['VAR', 'SYMBOL', true], ['IN', 'EXPRESSION', true], ['BODY', 'BLOCK', true]], null, 'PURE'],
  [0x0057, 'IF', ['FUNCTION', 'BLOCK', 'SHAPE', 'LAYER'], [['CONDITION', 'EXPRESSION', true], ['THEN', 'BLOCK', true], ['ELSE', 'BLOCK', false]], null, 'PURE'],
  [0x0058, 'MATCH', ['FUNCTION', 'BLOCK'], [['VALUE', 'EXPRESSION', true], ['CASES', 'BLOCK', true]], null, 'PURE'],
  [0x0059, 'RADIAL', ['SHAPE', 'BLOCK'], [['COUNT', 'I32', true], ['CENTER', 'VEC2', false], ['RADIUS', 'PX', false], ['BODY', 'BLOCK', true]], null, 'PURE'],
  [0x0104, 'MOD', ['EXPRESSION'], [['LEFT', 'NUMERIC', true], ['RIGHT', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0105, 'POW', ['EXPRESSION'], [['BASE', 'NUMERIC', true], ['EXP', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0106, 'ABS', ['EXPRESSION'], [['VALUE', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0107, 'MIN', ['EXPRESSION'], [['A', 'NUMERIC', true], ['B', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0108, 'MAX', ['EXPRESSION'], [['A', 'NUMERIC', true], ['B', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0109, 'CLAMP', ['EXPRESSION'], [['VALUE', 'NUMERIC', true], ['MIN', 'NUMERIC', true], ['MAX', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x010A, 'FLOOR', ['EXPRESSION'], [['VALUE', 'NUMERIC', true]], 'I32', 'PURE'],
  [0x010B, 'CEIL', ['EXPRESSION'], [['VALUE', 'NUMERIC', true]], 'I32', 'PURE'],
  [0x010C, 'ROUND', ['EXPRESSION'], [['VALUE', 'NUMERIC', true]], 'I32', 'PURE'],
  [0x010D, 'SQRT', ['EXPRESSION'], [['VALUE', 'NUMERIC', true]], 'NUMERIC', 'PURE'],
  [0x010E, 'SIN', ['EXPRESSION'], [['ANGLE', 'ANGLE', true]], 'FIXED', 'PURE'],
  [0x010F, 'COS', ['EXPRESSION'], [['ANGLE', 'ANGLE', true]], 'FIXED', 'PURE'],
  [0x0112, 'TAN', ['EXPRESSION'], [['ANGLE', 'ANGLE', true]], 'FIXED', 'PURE'],
  [0x0113, 'ATAN2', ['EXPRESSION'], [['Y', 'NUMERIC', true], ['X', 'NUMERIC', true]], 'ANGLE', 'PURE'],
  [0x0114, 'LERP', ['EXPRESSION'], [['A', 'NUMERIC', true], ['B', 'NUMERIC', true], ['T', 'SCALAR', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0115, 'MAP_RANGE', ['EXPRESSION'], [['VAL', 'NUMERIC', true], ['IN_MIN', 'NUMERIC', true], ['IN_MAX', 'NUMERIC', true], ['OUT_MIN', 'NUMERIC', true], ['OUT_MAX', 'NUMERIC', true]], 'SAME_NUMERIC', 'PURE'],
  [0x0116, 'GCD', ['EXPRESSION'], [['A', 'I32', true], ['B', 'I32', true]], 'I32', 'PURE'],
  [0x0117, 'LCM', ['EXPRESSION'], [['A', 'I32', true], ['B', 'I32', true]], 'I32', 'PURE'],
  [0x0118, 'DISTANCE', ['EXPRESSION'], [['A', 'VEC2', true], ['B', 'VEC2', true]], 'PX', 'PURE'],
  [0x0119, 'DOT', ['EXPRESSION'], [['A', 'VEC2', true], ['B', 'VEC2', true]], 'SCALAR', 'PURE'],
  [0x011A, 'CROSS', ['EXPRESSION'], [['A', 'VEC2', true], ['B', 'VEC2', true]], 'SCALAR', 'PURE'],
  [0x011B, 'NORMALIZE', ['EXPRESSION'], [['V', 'VEC2', true]], 'VEC2', 'PURE'],
  [0x0120, 'EQ', ['EXPRESSION'], [['A', 'ANY', true], ['B', 'ANY', true]], 'BOOL', 'PURE'],
  [0x0121, 'NEQ', ['EXPRESSION'], [['A', 'ANY', true], ['B', 'ANY', true]], 'BOOL', 'PURE'],
  [0x0122, 'LT', ['EXPRESSION'], [['A', 'NUMERIC', true], ['B', 'NUMERIC', true]], 'BOOL', 'PURE'],
  [0x0123, 'LTE', ['EXPRESSION'], [['A', 'NUMERIC', true], ['B', 'NUMERIC', true]], 'BOOL', 'PURE'],
  [0x0124, 'GT', ['EXPRESSION'], [['A', 'NUMERIC', true], ['B', 'NUMERIC', true]], 'BOOL', 'PURE'],
  [0x0125, 'GTE', ['EXPRESSION'], [['A', 'NUMERIC', true], ['B', 'NUMERIC', true]], 'BOOL', 'PURE'],
  [0x0126, 'AND', ['EXPRESSION'], [['A', 'BOOL', true], ['B', 'BOOL', true]], 'BOOL', 'PURE'],
  [0x0127, 'OR', ['EXPRESSION'], [['A', 'BOOL', true], ['B', 'BOOL', true]], 'BOOL', 'PURE'],
  [0x0128, 'NOT', ['EXPRESSION'], [['A', 'BOOL', true]], 'BOOL', 'PURE'],
  [0x0130, 'RANGE', ['EXPRESSION'], [['START', 'I32', true], ['END', 'I32', true], ['STEP', 'I32', false]], 'RANGE', 'PURE'],
  [0x0131, 'AT', ['EXPRESSION'], [['COLLECTION', 'ANY', true], ['INDEX', 'I32', true]], 'ANY', 'PURE'],
  [0x0132, 'LENGTH', ['EXPRESSION'], [['COLLECTION', 'ANY', true]], 'I32', 'PURE'],
  [0x0133, 'SUM', ['EXPRESSION'], [['COLLECTION', 'ANY', true]], 'NUMERIC', 'PURE'],
  [0x0134, 'PRODUCT', ['EXPRESSION'], [['COLLECTION', 'ANY', true]], 'NUMERIC', 'PURE'],
  [0x0135, 'FOLD', ['EXPRESSION'], [['COLLECTION', 'ANY', true], ['INITIAL', 'ANY', true], ['FN', 'IDENT', true]], 'ANY', 'PURE'],
  [0x0136, 'MAP', ['EXPRESSION'], [['COLLECTION', 'ANY', true], ['FN', 'IDENT', true]], 'ANY', 'PURE'],
  [0x0137, 'FILTER', ['EXPRESSION'], [['COLLECTION', 'ANY', true], ['FN', 'IDENT', true]], 'ANY', 'PURE'],
  [0x0138, 'ZIP', ['EXPRESSION'], [['A', 'ANY', true], ['B', 'ANY', true]], 'ANY', 'PURE'],
  [0x0139, 'PREV', ['EXPRESSION'], [['OFFSET', 'I32', true]], 'ANY', 'PURE'],
  [0x013A, 'CALL', ['EXPRESSION'], [['FN', 'IDENT', true]], 'ANY', 'PURE'],
  [0x0140, 'RANDOM_I32', ['EXPRESSION'], [['RNG', 'SYMBOL', true], ['MIN', 'I32', true], ['MAX', 'I32', true]], 'I32', 'PURE'],
  [0x0141, 'RANDOM_SCALAR', ['EXPRESSION'], [['RNG', 'SYMBOL', true], ['MIN', 'SCALAR', true], ['MAX', 'SCALAR', true]], 'SCALAR', 'PURE'],
  [0x0142, 'RANDOM_VEC2', ['EXPRESSION'], [['RNG', 'SYMBOL', true], ['MIN', 'ANY', true], ['MAX', 'ANY', true]], 'VEC2', 'PURE'],
  [0x0143, 'NOISE_2D', ['EXPRESSION'], [['SEED', 'I32', true], ['FREQUENCY', 'SCALAR', false], ['OCTAVES', 'I32', false], ['AT', 'VEC2', true]], 'FIXED', 'PURE'],
  [0x0060, 'APPLY_AMP', ['PROGRAM', 'LAYER', 'SHAPE', 'BLOCK'], [['SYMBOL', 'SYMBOL', false], ['TYPE', 'TYPE', false], ['BODY', 'BLOCK', true]], 'ANY', 'CONSTRUCTION'],
  [0x0061, 'SELECT_AMPS', ['PROGRAM'], [['BODY', 'BLOCK', false]], null, 'CONSTRUCTION'],
  [0x8000, 'BC.CONST', ['BYTECODE'], [['CONSTANT', 'CONSTANT_INDEX', true]], 'DECLARED', 'PURE'],
  [0x8001, 'BC.LAYER.NEW', ['BYTECODE'], [['ID', 'IDENT', true], ['ORDER', 'I32', true]], 'LAYER', 'CONSTRUCTION'],
  [0x8002, 'BC.PAINT', ['BYTECODE'], [['LAYER', 'LAYER', true], ['SHAPE', 'SHAPE', true], ['FILL', 'COLOR', true], ['RASTER', 'RASTER_POLICY', true]], null, 'CONSTRUCTION'],
  [0x8003, 'BC.EMIT.ASSET', ['BYTECODE'], [['LAYERS', 'LIST<LAYER>', true]], null, 'CONSTRUCTION'],
  [0x8010, 'BC.CALL', ['BYTECODE'], [['FN', 'IDENT', true], ['ARGS', 'LIST<REGISTER>', true]], 'ANY', 'PURE'],
  [0x8011, 'BC.SEQ.RECURRENCE', ['BYTECODE'], [['COUNT', 'REGISTER', true], ['SEEDS', 'LIST<REGISTER>', true], ['STEP', 'STRING', true]], 'SEQUENCE', 'PURE'],
  [0x8012, 'BC.RNG.INIT', ['BYTECODE'], [['ALGORITHM', 'IDENT', true], ['SEED', 'I32', true]], 'RNG', 'PURE'],
  [0x8013, 'BC.RNG.SAMPLE', ['BYTECODE'], [['RNG', 'REGISTER', true], ['MIN', 'REGISTER', true], ['MAX', 'REGISTER', true]], 'ANY', 'PURE'],
  [0x8014, 'BC.MATH', ['BYTECODE'], [['OP', 'IDENT', true], ['ARGS', 'LIST<REGISTER>', true]], 'ANY', 'PURE'],
  [0x8020, 'BC.AMP.APPLY', ['BYTECODE'], [['AMP', 'IDENT', true], ['STAGE', 'IDENT', true], ['INPUTS', 'MAP', true], ['PARAMS', 'MAP', true]], 'ANY', 'CONSTRUCTION'],
  [0x8021, 'BC.AMP.SELECT', ['BYTECODE'], [['PLAN', 'LIST<IDENT>', true]], null, 'CONSTRUCTION'],
];

const CAPABILITIES = Object.freeze({
  SCDL: 'CORE.MATH@2.0',
  ASSET: 'CORE.MATH@2.0',
  CANVAS: 'GEOMETRY.STANDARD@2.0',
  BUDGET: 'CORE.MATH@2.0',
  CONST: 'CORE.MATH@2.0',
  SHAPE: 'GEOMETRY.STANDARD@2.0',
  LAYER: 'PAINT.LAYERS@2.0',
  PAINT: 'PAINT.LAYERS@2.0',
  ADD: 'CORE.MATH@2.0',
  SUB: 'CORE.MATH@2.0',
  MUL: 'CORE.MATH@2.0',
  DIV: 'CORE.MATH@2.0',
  PX: 'GEOMETRY.STANDARD@2.0',
  VEC2: 'GEOMETRY.STANDARD@2.0',
  PIXEL: 'GEOMETRY.STANDARD@2.0',
  CIRCLE: 'GEOMETRY.STANDARD@2.0',
  MASK: 'PAINT.MASKS@2.0',
  ANCHOR: 'GEOMETRY.STANDARD@2.0',
  ASSERT: 'GEOMETRY.STANDARD@2.0',
  LINE: 'GEOMETRY.STANDARD@2.0',
  POLYLINE: 'GEOMETRY.STANDARD@2.0',
  RAY: 'GEOMETRY.STANDARD@2.0',
  RECT: 'GEOMETRY.STANDARD@2.0',
  ROUNDED_RECT: 'GEOMETRY.STANDARD@2.0',
  RING: 'GEOMETRY.STANDARD@2.0',
  ELLIPSE: 'GEOMETRY.STANDARD@2.0',
  ARC: 'GEOMETRY.STANDARD@2.0',
  SECTOR: 'GEOMETRY.STANDARD@2.0',
  TRIANGLE: 'GEOMETRY.STANDARD@2.0',
  REGULAR_POLYGON: 'GEOMETRY.STANDARD@2.0',
  POLYGON: 'GEOMETRY.STANDARD@2.0',
  STAR: 'GEOMETRY.STANDARD@2.0',
  PATH: 'GEOMETRY.PATH@2.0',
  DEGREES: 'GEOMETRY.STANDARD@2.0',
  RADIANS: 'GEOMETRY.STANDARD@2.0',
  TURNS: 'GEOMETRY.STANDARD@2.0',
  ROTATE: 'GEOMETRY.STANDARD@2.0',
  TRANSLATE: 'GEOMETRY.STANDARD@2.0',
  SCALE: 'GEOMETRY.STANDARD@2.0',
  TRANSFORM_COMPOSE: 'GEOMETRY.STANDARD@2.0',
  TRANSFORM_APPLY: 'GEOMETRY.STANDARD@2.0',
  TRANSFORM_MATRIX: 'GEOMETRY.STANDARD@2.0',
  UNION: 'GEOMETRY.STANDARD@2.0',
  SUBTRACT: 'GEOMETRY.STANDARD@2.0',
  INTERSECT: 'GEOMETRY.STANDARD@2.0',
  XOR: 'GEOMETRY.STANDARD@2.0',
  OUTLINE: 'GEOMETRY.STANDARD@2.0',
  TO_MASK: 'PAINT.MASKS@2.0',
  MASK_UNION: 'PAINT.MASKS@2.0',
  MASK_INTERSECT: 'PAINT.MASKS@2.0',
  MASK_SUBTRACT: 'PAINT.MASKS@2.0',
  MASK_INVERT: 'PAINT.MASKS@2.0',
  ALIGN: 'GEOMETRY.STANDARD@2.0',
  ANCHOR_OF: 'GEOMETRY.STANDARD@2.0',
  BOUNDS: 'GEOMETRY.STANDARD@2.0',
  INSIDE: 'GEOMETRY.STANDARD@2.0',
  CONTAINS: 'GEOMETRY.STANDARD@2.0',
  TOUCHES: 'GEOMETRY.STANDARD@2.0',
  OVERLAPS: 'GEOMETRY.STANDARD@2.0',
  FN: 'CORE.MATH@2.0',
  SEQUENCE: 'CORE.SEQUENCE@2.0',
  RNG: 'NOISE.DETERMINISTIC@2.0',
  LET: 'CORE.MATH@2.0',
  RETURN: 'CORE.MATH@2.0',
  EMIT: 'GEOMETRY.STANDARD@2.0',
  FOR: 'CORE.MATH@2.0',
  IF: 'CORE.MATH@2.0',
  MATCH: 'CORE.MATH@2.0',
  RADIAL: 'GEOMETRY.PARAMETRIC@2.0',
  MOD: 'CORE.MATH@2.0',
  POW: 'CORE.MATH@2.0',
  ABS: 'CORE.MATH@2.0',
  MIN: 'CORE.MATH@2.0',
  MAX: 'CORE.MATH@2.0',
  CLAMP: 'CORE.MATH@2.0',
  FLOOR: 'CORE.MATH@2.0',
  CEIL: 'CORE.MATH@2.0',
  ROUND: 'CORE.MATH@2.0',
  SQRT: 'CORE.MATH@2.0',
  SIN: 'CORE.MATH@2.0',
  COS: 'CORE.MATH@2.0',
  TAN: 'CORE.MATH@2.0',
  ATAN2: 'CORE.MATH@2.0',
  LERP: 'CORE.MATH@2.0',
  MAP_RANGE: 'CORE.MATH@2.0',
  GCD: 'CORE.MATH@2.0',
  LCM: 'CORE.MATH@2.0',
  DISTANCE: 'CORE.MATH@2.0',
  DOT: 'CORE.MATH@2.0',
  CROSS: 'CORE.MATH@2.0',
  NORMALIZE: 'CORE.MATH@2.0',
  EQ: 'CORE.MATH@2.0',
  NEQ: 'CORE.MATH@2.0',
  LT: 'CORE.MATH@2.0',
  LTE: 'CORE.MATH@2.0',
  GT: 'CORE.MATH@2.0',
  GTE: 'CORE.MATH@2.0',
  AND: 'CORE.MATH@2.0',
  OR: 'CORE.MATH@2.0',
  NOT: 'CORE.MATH@2.0',
  RANGE: 'CORE.SEQUENCE@2.0',
  AT: 'CORE.SEQUENCE@2.0',
  LENGTH: 'CORE.SEQUENCE@2.0',
  SUM: 'CORE.SEQUENCE@2.0',
  PRODUCT: 'CORE.SEQUENCE@2.0',
  FOLD: 'CORE.SEQUENCE@2.0',
  MAP: 'CORE.SEQUENCE@2.0',
  FILTER: 'CORE.SEQUENCE@2.0',
  ZIP: 'CORE.SEQUENCE@2.0',
  PREV: 'CORE.SEQUENCE@2.0',
  CALL: 'CORE.MATH@2.0',
  RANDOM_I32: 'NOISE.DETERMINISTIC@2.0',
  RANDOM_SCALAR: 'NOISE.DETERMINISTIC@2.0',
  RANDOM_VEC2: 'NOISE.DETERMINISTIC@2.0',
  NOISE_2D: 'NOISE.DETERMINISTIC@2.0',
  'BC.CONST': 'CORE.MATH@2.0',
  'BC.LAYER.NEW': 'PAINT.LAYERS@2.0',
  'BC.PAINT': 'PAINT.LAYERS@2.0',
  'BC.EMIT.ASSET': 'PAINT.LAYERS@2.0',
  'BC.CALL': 'CORE.MATH@2.0',
  'BC.SEQ.RECURRENCE': 'CORE.SEQUENCE@2.0',
  'BC.RNG.INIT': 'NOISE.DETERMINISTIC@2.0',
  'BC.RNG.SAMPLE': 'NOISE.DETERMINISTIC@2.0',
  'BC.MATH': 'CORE.MATH@2.0',
  APPLY_AMP: 'MATERIAL.PIXELBRAIN@2.0',
  SELECT_AMPS: 'MATERIAL.PIXELBRAIN@2.0',
  'BC.AMP.APPLY': 'MATERIAL.PIXELBRAIN@2.0',
  'BC.AMP.SELECT': 'MATERIAL.PIXELBRAIN@2.0',
});

const DOCS = Object.freeze({
  SCDL: 'Declares the SCDL source language version.',
  ASSET: 'Declares the emitted asset identifier.',
  CANVAS: 'Declares the pixel canvas dimensions.',
  BUDGET: 'Declares static instruction, shape, and raster limits.',
  CONST: 'Binds a typed immutable value.',
  SHAPE: 'Binds an immutable shape expression or shape generator block.',
  LAYER: 'Constructs an ordered paint layer.',
  PAINT: 'Paints a shape with a color and raster policy.',
  APPLY_AMP: 'Explicitly applies an AMP effect pass with verified inputs and parameters.',
  SELECT_AMPS: 'Runs deterministic relevance selection across registered AMPs.',
  ADD: 'Adds two compatible numeric values.',
  SUB: 'Subtracts the right numeric value from the left.',
  MUL: 'Multiplies two compatible numeric values.',
  DIV: 'Divides a numeric value by a nonzero scalar.',
  PX: 'Constructs a pixel-distance value from a scalar.',
  VEC2: 'Constructs a two-dimensional pixel vector.',
  PIXEL: 'Constructs a one-cell shape at a named position.',
  CIRCLE: 'Constructs a circle from named center and radius operands.',
  MASK: 'Binds an immutable binary lattice mask.',
  ANCHOR: 'Declares a named anchor on a shape.',
  ASSERT: 'Asserts a geometric condition at compile time.',
  FN: 'Declares a pure, bounded function.',
  SEQUENCE: 'Defines a finite recurrence sequence.',
  RNG: 'Initializes a seeded pseudo-random number generator.',
  LET: 'Binds a scoped immutable local variable.',
  RETURN: 'Returns a value from a function.',
  EMIT: 'Emits a shape into a surrounding generator block.',
  FOR: 'Iterates deterministically over a finite range or collection.',
  IF: 'Executes a block conditionally based on a boolean expression.',
  MATCH: 'Matches an expression against pattern branches.',
  RADIAL: 'Arranges emitted shapes radially around a center point.',
  MOD: 'Computes the modulo of two integers.',
  POW: 'Computes an integer power of a base value.',
  ABS: 'Computes the absolute value of a numeric value.',
  MIN: 'Computes the minimum of two numeric values.',
  MAX: 'Computes the maximum of two numeric values.',
  CLAMP: 'Clamps a numeric value between minimum and maximum bounds.',
  FLOOR: 'Floors a numeric value to the nearest integer below.',
  CEIL: 'Ceils a numeric value to the nearest integer above.',
  ROUND: 'Rounds a numeric value to the nearest integer.',
  SQRT: 'Computes the deterministic square root of a numeric value.',
  SIN: 'Computes the deterministic sine of an angle.',
  COS: 'Computes the deterministic cosine of an angle.',
  TAN: 'Computes the deterministic tangent of an angle.',
  ATAN2: 'Computes the deterministic angle between origin and (x, y).',
  LERP: 'Linearly interpolates between two numeric values.',
  MAP_RANGE: 'Linearly maps a value from an input range to an output range.',
  GCD: 'Computes the greatest common divisor of two integers.',
  LCM: 'Computes the least common multiple of two integers.',
  DISTANCE: 'Computes the Euclidean distance between two vectors.',
  DOT: 'Computes the scalar dot product of two vectors.',
  CROSS: 'Computes the 2D cross product of two vectors.',
  NORMALIZE: 'Normalizes a 2D vector to unit length.',
  EQ: 'Tests equality of two values.',
  NEQ: 'Tests inequality of two values.',
  LT: 'Tests if left value is strictly less than right.',
  LTE: 'Tests if left value is less than or equal to right.',
  GT: 'Tests if left value is strictly greater than right.',
  GTE: 'Tests if left value is greater than or equal to right.',
  AND: 'Computes boolean logical conjunction.',
  OR: 'Computes boolean logical disjunction.',
  NOT: 'Computes boolean logical negation.',
  RANGE: 'Constructs a finite numeric integer range.',
  AT: 'Retrieves an element from a collection at an integer index.',
  LENGTH: 'Returns the length of a finite collection.',
  SUM: 'Computes the sum of a collection of numeric values.',
  PRODUCT: 'Computes the product of a collection of numeric values.',
  FOLD: 'Folds a collection with a binary function and initial accumulator.',
  MAP: 'Maps a unary function over every element in a collection.',
  FILTER: 'Filters a collection by a unary predicate function.',
  ZIP: 'Combines two collections element-wise.',
  PREV: 'Retrieves a previous recurrence element by historical offset.',
  CALL: 'Calls a pure function with evaluated arguments.',
  RANDOM_I32: 'Generates a pseudo-random 32-bit integer within bounds.',
  RANDOM_SCALAR: 'Generates a pseudo-random scalar within bounds.',
  RANDOM_VEC2: 'Generates a pseudo-random 2D vector within bounds.',
  NOISE_2D: 'Computes deterministic 2D coherent noise at coordinates.',
  LINE: 'Constructs a line segment between two vectors.',
  POLYLINE: 'Constructs an open or closed polyline.',
  RAY: 'Constructs a ray segment from origin with direction and length.',
  RECT: 'Constructs a rectangle from origin/center and size.',
  ROUNDED_RECT: 'Constructs a rounded rectangle.',
  RING: 'Constructs a hollow ring.',
  ELLIPSE: 'Constructs an ellipse from radii.',
  ARC: 'Constructs a circular arc.',
  SECTOR: 'Constructs a circular pie sector.',
  TRIANGLE: 'Constructs a triangle.',
  REGULAR_POLYGON: 'Constructs a regular polygon with N sides.',
  POLYGON: 'Constructs an arbitrary polygon from vertices.',
  STAR: 'Constructs a star polygon.',
  PATH: 'Constructs an SVG-compatible vector path.',
  DEGREES: 'Constructs an angle in degrees.',
  RADIANS: 'Constructs an angle in radians.',
  TURNS: 'Constructs an angle in turns.',
  ROTATE: 'Constructs a rotation transform.',
  TRANSLATE: 'Constructs a translation transform.',
  SCALE: 'Constructs a scale transform.',
  TRANSFORM_COMPOSE: 'Composes two 2D affine transforms.',
  TRANSFORM_APPLY: 'Applies an affine transform to a vector or shape.',
  TRANSFORM_MATRIX: 'Constructs a 2D affine transform from matrix components.',
  UNION: 'Computes the CSG union of two shapes.',
  SUBTRACT: 'Computes the CSG difference of two shapes.',
  INTERSECT: 'Computes the CSG intersection of two shapes.',
  XOR: 'Computes the CSG symmetric difference of two shapes.',
  OUTLINE: 'Extracts the boundary outline of a shape.',
  TO_MASK: 'Converts a shape into an immutable binary mask.',
  MASK_UNION: 'Computes the union of two masks.',
  MASK_INTERSECT: 'Computes the intersection of two masks.',
  MASK_SUBTRACT: 'Computes the difference of two masks.',
  MASK_INVERT: 'Inverts a binary mask within canvas bounds.',
  ALIGN: 'Aligns a target shape to a reference shape using anchors.',
  ANCHOR_OF: 'Retrieves the position vector of a named anchor.',
  BOUNDS: 'Computes the bounding box of a shape or canvas.',
  INSIDE: 'Tests if a point is inside a shape or bounds.',
  CONTAINS: 'Tests if a shape bounds completely contains another.',
  TOUCHES: 'Tests if two shapes touch or intersect.',
  OVERLAPS: 'Tests if two shapes overlap in area.',
  'BC.CONST': 'Loads a declared constant in canonical bytecode.',
  'BC.LAYER.NEW': 'Creates an ordered layer in canonical bytecode.',
  'BC.PAINT': 'Paints a shape into a bytecode layer.',
  'BC.EMIT.ASSET': 'Emits the completed asset from bytecode layers.',
  'BC.CALL': 'Calls a function in canonical bytecode.',
  'BC.SEQ.RECURRENCE': 'Executes a bounded recurrence in canonical bytecode.',
  'BC.RNG.INIT': 'Initializes an RNG stream in canonical bytecode.',
  'BC.RNG.SAMPLE': 'Samples from an RNG stream in canonical bytecode.',
  'BC.MATH': 'Evaluates a mathematical operation in canonical bytecode.',
  'BC.AMP.APPLY': 'Executes a certified AMP pass or registers a descriptor.',
  'BC.AMP.SELECT': 'Records the selected deterministic AMP execution plan.',
});

const STUBBED_COLLECTION_OPCODES = new Set(['FOLD', 'MAP', 'FILTER']);

const RASTER_AFFECTING_OPCODES = new Set([
  'CANVAS', 'SHAPE', 'LAYER', 'PAINT', 'MASK', 'LET', 'RETURN', 'EMIT', 'FOR', 'IF', 'MATCH', 'RADIAL',
  'APPLY_AMP', 'SELECT_AMPS', 'PIXEL', 'CIRCLE', 'LINE', 'POLYLINE', 'RAY', 'RECT', 'ROUNDED_RECT',
  'RING', 'ELLIPSE', 'ARC', 'SECTOR', 'TRIANGLE', 'REGULAR_POLYGON', 'POLYGON', 'STAR', 'PATH',
  'UNION', 'SUBTRACT', 'INTERSECT', 'XOR', 'OUTLINE', 'TO_MASK', 'MASK_UNION', 'MASK_INTERSECT',
  'MASK_SUBTRACT', 'MASK_INVERT', 'ALIGN', 'BC.LAYER.NEW', 'BC.PAINT', 'BC.EMIT.ASSET', 'BC.AMP.APPLY', 'BC.AMP.SELECT',
]);

const OPERAND_RESTRICTIONS = Object.freeze({
  OUTLINE: Object.freeze({ WIDTH: 'Integer >= 0; multi-pass erosion peeling' }),
  RADIAL: Object.freeze({ COUNT: 'Integer >= 1', RADIUS: 'Distance >= 0' }),
  CANVAS: Object.freeze({ WIDTH: 'U32 > 0', HEIGHT: 'U32 > 0' }),
  BUDGET: Object.freeze({ INSTRUCTIONS: 'U32 > 0', GENERATED_SHAPES: 'U32 > 0', RASTER_CELLS: 'U32 > 0' }),
  PAINT: Object.freeze({ RASTER: 'CENTER | MIDPOINT | BRESENHAM | SUPERCOVER (THRESHOLD stubbed)' }),
  ALIGN: Object.freeze({ ANCHOR: 'Named anchor on target shape' }),
  REGULAR_POLYGON: Object.freeze({ SIDES: 'Integer >= 3' }),
  STAR: Object.freeze({ POINTS: 'Integer >= 3' }),
  FOLD: Object.freeze({ STATUS: 'Stubbed collection placeholder' }),
  MAP: Object.freeze({ STATUS: 'Stubbed collection placeholder' }),
  FILTER: Object.freeze({ STATUS: 'Stubbed collection placeholder' }),
});

const OPCODES = Object.freeze(DEFINITIONS.map(([id, mnemonic, scope, operands, result, purity]) => {
  const frozenOperands = Object.freeze(operands.map(([name, type, required]) => Object.freeze({
    name,
    type,
    required,
  })));
  const isStubbed = STUBBED_COLLECTION_OPCODES.has(mnemonic);
  const isRaster = RASTER_AFFECTING_OPCODES.has(mnemonic);
  const restrictions = OPERAND_RESTRICTIONS[mnemonic] || Object.freeze({});

  return Object.freeze({
    id,
    mnemonic,
    scope: Object.freeze([...scope]),
    legalScopes: Object.freeze([...scope]),
    operands: frozenOperands,
    operandRestrictions: restrictions,
    result,
    purity,
    cost: 1,
    capability: CAPABILITIES[mnemonic],
    version: '2.0.0',
    docs: DOCS[mnemonic],
    status: isStubbed ? 'STUBBED' : (mnemonic === 'THRESHOLD' ? 'STUBBED' : 'IMPLEMENTED'),
    implemented: !isStubbed && mnemonic !== 'THRESHOLD',
    parsed: true,
    analyzed: !isStubbed,
    lowered: !isStubbed,
    evaluated: !isStubbed,
    rasterized: !isStubbed && isRaster,
    exported: !isStubbed,
    tested: !isStubbed,
  });
}));

export const OPCODE_REGISTRY = OPCODES;

export const OPCODE_SUPPORT_FLAGS = Object.freeze({
  ...Object.fromEntries(OPCODES.map((op) => [op.mnemonic, op.status])),
  THRESHOLD: 'STUBBED',
});

const OPCODE_BY_MNEMONIC = new Map(OPCODES.map((definition) => [definition.mnemonic, definition]));

export function getSCDLV2Opcode(mnemonic) {
  return OPCODE_BY_MNEMONIC.get(mnemonic) || null;
}

export function listSCDLV2Opcodes() {
  return OPCODES;
}

export function listSCDLV2Capabilities() {
  const capMap = new Map();
  for (const op of OPCODES) {
    const capId = op.capability || 'CORE.MATH@2.0';
    if (!capMap.has(capId)) {
      capMap.set(capId, {
        id: capId,
        version: '2.0.0',
        opcodes: [],
        supportedCount: 0,
        stubbedCount: 0,
      });
    }
    const cap = capMap.get(capId);
    cap.opcodes.push(op.mnemonic);
    if (op.status === 'IMPLEMENTED' || op.status === 'SUPPORTED') cap.supportedCount += 1;
    else cap.stubbedCount += 1;
  }

  return Object.freeze({
    contract: 'PB-SCDL-CAPABILITIES-v1',
    opcodes: OPCODES,
    descriptors: Object.freeze(['PACKET', 'ASSET', 'ANY', 'SOIL_SURFACE_DESCRIPTOR']),
    formats: Object.freeze(['json', 'svg', 'phaser', 'png', 'aseprite']),
    flags: Object.freeze({ SCDL_V2_ENABLED: true }),
    capabilities: Object.freeze(Array.from(capMap.values()).map((c) => Object.freeze({
      ...c,
      opcodes: Object.freeze([...c.opcodes]),
    }))),
    rasterPolicies: Object.freeze([
      Object.freeze({ name: 'CENTER', status: 'SUPPORTED' }),
      Object.freeze({ name: 'MIDPOINT', status: 'SUPPORTED' }),
      Object.freeze({ name: 'BRESENHAM', status: 'SUPPORTED' }),
      Object.freeze({ name: 'SUPERCOVER', status: 'SUPPORTED' }),
      Object.freeze({ name: 'THRESHOLD', status: 'STUBBED', reason: "Raster policy 'THRESHOLD' is reserved but has no registered rasterizer algorithm" }),
    ]),
    compositeModes: Object.freeze([
      Object.freeze({ name: 'OVER', status: 'SUPPORTED' }),
      Object.freeze({ name: 'ADD', status: 'SUPPORTED' }),
      Object.freeze({ name: 'SUBTRACT', status: 'SUPPORTED' }),
      Object.freeze({ name: 'MULTIPLY', status: 'SUPPORTED' }),
      Object.freeze({ name: 'MASK_IN', status: 'SUPPORTED' }),
      Object.freeze({ name: 'MASK_OUT', status: 'SUPPORTED' }),
      Object.freeze({ name: 'REPLACE', status: 'SUPPORTED' }),
    ]),
  });
}
