/**
 * PolarisOS Stateful Lattice Console — deterministic build adapter (Task 2).
 *
 * Authors + validates the canonical PB-UI-SCENE-v1, lowers it through the
 * Compose DOM adapter, and emits a runtime-neutral DOM plan (TypeScript) plus
 * token CSS custom properties into the Polaris client. Build/test-time only —
 * never imported by the production browser bundle.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPolarisConsoleScene } from '../src/core/compose/kits/polaris-console';
import { validateComposeScene } from '../src/core/compose/validate/scene';
import { renderSceneToDomSpec, type DomNodeSpec } from '../src/core/compose/render/dom-adapter';
import { checksumCanonical } from '../src/core/compose/schema/canonicalize';

function resolveRepoRoot(): string {
  try {
    if (import.meta.url && import.meta.url.startsWith('file:')) {
      return resolve(dirname(fileURLToPath(import.meta.url)), '..');
    }
  } catch {
    // fall through to cwd
  }
  return process.cwd();
}

const REPO_ROOT = resolveRepoRoot();
export interface BuildPolarisConsoleUiOptions {
  domPlanFile: string;
  tokenCssFile: string;
}

export interface BuildPolarisConsoleUiResult {
  sceneChecksum: string;
  files: readonly string[];
}

const BANNER =
  '/* AUTO-GENERATED by scripts/build-polaris-console-ui.ts — do not hand-edit. */\n';

/** Stable JSON stringify with recursively sorted object keys. */
function stableStringify(value: unknown, indent = 2): string {
  const sortDeep = (v: unknown): unknown => {
    if (Array.isArray(v)) return v.map(sortDeep);
    if (v && typeof v === 'object') {
      const out: Record<string, unknown> = {};
      for (const key of Object.keys(v as Record<string, unknown>).sort()) {
        out[key] = sortDeep((v as Record<string, unknown>)[key]);
      }
      return out;
    }
    return v;
  };
  return JSON.stringify(sortDeep(value), null, indent);
}

interface TokenLeaf {
  path: string;
  value: string;
}

/** Flatten DTCG-style token groups into sorted `--polaris-*` leaves. */
function flattenTokens(node: unknown, prefix: string, out: TokenLeaf[]): void {
  if (node && typeof node === 'object' && !Array.isArray(node)) {
    const record = node as Record<string, unknown>;
    if ('$value' in record && '$type' in record) {
      out.push({ path: prefix, value: String(record.$value) });
      return;
    }
    for (const key of Object.keys(record)) {
      const next = prefix ? `${prefix}-${key}` : key;
      flattenTokens(record[key], next, out);
    }
  }
}

function buildTokenCss(tokensPath: string): string {
  const tokens = JSON.parse(readFileSync(tokensPath, 'utf8'));
  const leaves: TokenLeaf[] = [];
  flattenTokens(tokens, '', leaves);
  leaves.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  const lines = leaves.map((leaf) => `  --polaris-${leaf.path}: ${leaf.value};`);
  return `${BANNER}:root {\n${lines.join('\n')}\n}\n`;
}

function buildDomPlanTs(spec: DomNodeSpec, sceneChecksum: string): string {
  return (
    `${BANNER}` +
    `export const polarisConsoleSceneChecksum = ${JSON.stringify(sceneChecksum)} as const;\n\n` +
    `export const polarisConsoleDomPlan = ${stableStringify(spec)} as const;\n\n` +
    `export type PolarisConsoleDomPlan = typeof polarisConsoleDomPlan;\n`
  );
}

function formatDiagnostics(diagnostics: readonly { code: string; severity: string; message: string; sourceNodeId?: string }[]): string {
  return diagnostics
    .map((d) => `  [${d.severity}] ${d.code} ${d.sourceNodeId ? `(${d.sourceNodeId}) ` : ''}${d.message}`)
    .join('\n');
}

export async function buildPolarisConsoleUi(
  options: BuildPolarisConsoleUiOptions,
): Promise<BuildPolarisConsoleUiResult> {
  const scene = createPolarisConsoleScene();

  const validation = validateComposeScene(scene);
  const errors = validation.diagnostics.filter((d) => d.severity === 'ERROR');
  if (!validation.ok || errors.length > 0) {
    throw new Error(
      `Polaris console scene failed Compose validation:\n${formatDiagnostics(errors)}`,
    );
  }

  const sceneChecksum = checksumCanonical(scene);
  const spec = renderSceneToDomSpec(scene);

  // Build both outputs fully before writing anything.
  const tokensPath = join(REPO_ROOT, 'tokens/compose/polaris-console.tokens.json');
  const domPlanTs = buildDomPlanTs(spec, sceneChecksum);
  const tokenCss = buildTokenCss(tokensPath);

  mkdirSync(dirname(options.domPlanFile), { recursive: true });
  mkdirSync(dirname(options.tokenCssFile), { recursive: true });
  writeFileSync(options.domPlanFile, domPlanTs, 'utf8');
  writeFileSync(options.tokenCssFile, tokenCss, 'utf8');

  return {
    sceneChecksum,
    files: [options.domPlanFile, options.tokenCssFile],
  };
}

/** CLI entrypoint (npm run polaris:build-console-ui). */
async function main(): Promise<void> {
  const result = await buildPolarisConsoleUi({
    domPlanFile: join(
      REPO_ROOT,
      'PolarisOS/apps/client/src/generated/polaris-console.dom-plan.ts',
    ),
    tokenCssFile: join(
      REPO_ROOT,
      'PolarisOS/apps/client/src/generated/polaris-console.tokens.css',
    ),
  });
  // eslint-disable-next-line no-console
  console.log(
    `polaris-console-ui: wrote ${result.files.length} files (sceneChecksum ${result.sceneChecksum})`,
  );
}

let isDirectRun = false;
try {
  isDirectRun =
    !!process.argv[1] &&
    import.meta.url.startsWith('file:') &&
    resolve(process.argv[1]) === fileURLToPath(import.meta.url);
} catch {
  isDirectRun = false;
}

if (isDirectRun) {
  main().catch((err) => {
    // eslint-disable-next-line no-console
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
