/**
 * Scholomium Ink — Tree Projection Adapter (Botanical Morphology & AMP Substrate)
 *
 * Translates approved SCD128 Lawyer counsel receipts into valid semantic SCDL v2
 * source code and editable PixelBrain layer surfaces across the 9 semantic layers:
 *   1. ground_shadow
 *   2. roots_and_ground
 *   3. trunk
 *   4. primary_branches
 *   5. secondary_branches
 *   6. canopy_masses
 *   7. foliage_edges
 *   8. surface_detail
 *   9. highlights
 *
 * Enforces:
 * - Species-distinct botanical morphology (Oak, Hickory, Redwood, Cedar, Pine, Evergreen, Maple, and Hybrids)
 * - Proportional geometry that gracefully scales across all canvas sizes (32x52, 48x64, 48x112)
 * - Universal AMP Substrate activation (`SELECT_AMPS PIPELINE render-fidelity`)
 * - Multi-tier foliage depth shading, bark striations, and directional highlight relief
 * - Fails closed on quarantined counsel receipts
 */

import { compileSCDLV2 } from '../../../scdl/v2/scdl-v2.compiler.js';
import { isQuarantined } from '../../scd128/counsel/quarantine.js';
import { SCD128_ERROR_CODES } from '../../scd128/scd128.constants.js';
import { TREE_PALETTES } from './tree-realization.vocabulary.js';

export function projectCounseledTreeToSCDLV2({ receipt, artPacket, assetName = 'scholomium_tree' }) {
  if (isQuarantined(receipt)) {
    const err = new Error('Tree projection refused: counsel receipt is quarantined');
    err.code = SCD128_ERROR_CODES.PROJECTION_REFUSED;
    throw err;
  }

  const form = artPacket?.form;
  const realization = artPacket?.realization;

  const formSlots = Object.fromEntries((form?.slots || []).map((s) => [s.slot, s]));
  const realSlots = Object.fromEntries((realization?.slots || []).map((s) => [s.slot, s]));

  const familyKey = (formSlots.ASSET_CLASS?.canonicalCategory || 'oak').toLowerCase();
  const envelope = (formSlots.SILHOUETTE?.canonicalCategory || 'broad_rounded').toLowerCase();
  const paletteThemeKey = (realSlots.PALETTE_LOGIC?.canonicalCategory || 'verdant_forest').toLowerCase();
  const palette = TREE_PALETTES[paletteThemeKey] || TREE_PALETTES.verdant_forest;

  // Geometry dimensions from SCALE_FRAME or default
  const canvasWidth = Number(formSlots.SCALE_FRAME?.parameters?.canvas_width || 48);
  const canvasHeight = Number(formSlots.SCALE_FRAME?.parameters?.canvas_height || 64);
  const cx = Math.floor(canvasWidth / 2);
  const groundY = canvasHeight - 8;
  const rasterBudget = Math.max(16384, canvasWidth * canvasHeight * 3);

  // Build semantic SCDL v2 source with Universal AMP activation
  const lines = [
    'SCDL 2',
    `ASSET ${assetName}`,
    `CANVAS WIDTH ${canvasWidth} HEIGHT ${canvasHeight}`,
    `BUDGET INSTRUCTIONS 20000 GENERATED_SHAPES 500 RASTER_CELLS ${rasterBudget} RECURSION_DEPTH 16`,
    'SELECT_AMPS PIPELINE render-fidelity',
    '# APPLY_AMP pixelbrain.fibonacci-seed-field',
    '# SHADER canopy_masses FOLIAGE',
    '# SHADER surface_detail BARK_DETAIL',
    '',
    `CONST $cx I32 ${cx}`,
    `CONST $gy I32 ${groundY}`,
    '',
    `# Palette declarations for theme ${paletteThemeKey}`,
    `CONST $canopy_spec COLOR ${palette.canopy_spec}`,
    `CONST $canopy_hi COLOR ${palette.canopy_hi}`,
    `CONST $canopy_lit COLOR ${palette.canopy_lit}`,
    `CONST $canopy_mid COLOR ${palette.canopy_mid}`,
    `CONST $canopy_base COLOR ${palette.canopy_base}`,
    `CONST $canopy_dark COLOR ${palette.canopy_dark}`,
    `CONST $bark_lit COLOR ${palette.bark_lit}`,
    `CONST $bark_mid COLOR ${palette.bark_mid}`,
    `CONST $bark_base COLOR ${palette.bark_base}`,
    `CONST $bark_dark COLOR ${palette.bark_dark}`,
    `CONST $shadow_abyss COLOR ${palette.shadow_abyss}`,
    '',
  ];

  // ── LAYER 1: ground_shadow ──────────────────────────────────────────────
  const shadowR = Math.max(8, Math.min(24, Math.floor(canvasWidth * 0.32)));
  lines.push(
    '# --- Semantic Layer 1: ground_shadow ---',
    `SHAPE $sh_core (CIRCLE CENTER (VEC2 (PX $cx) (PX $gy)) RADIUS (PX ${shadowR}))`,
    `SHAPE $sh_ring (ELLIPSE CENTER (VEC2 (PX $cx) (PX $gy)) RADIUS_X (PX ${shadowR + 4}) RADIUS_Y (PX 4))`,
    'LAYER ground_shadow ORDER 5 {',
    '  PAINT $sh_ring FILL $shadow_abyss RASTER MIDPOINT',
    '  PAINT $sh_core FILL $shadow_abyss RASTER MIDPOINT',
    '}',
    ''
  );

  // ── MORPHOLOGY SWITCH ──────────────────────────────────────────────────
  if (familyKey === 'redwood' || envelope === 'tapered_spire') {
    // REDWOOD: extreme verticality, massive buttressed flare, long bare trunk, high tiered bough whorls, spire top
    const trunkBaseW = Math.max(10, Math.floor(canvasWidth * 0.32));
    const trunkTopW = Math.max(4, Math.floor(canvasWidth * 0.1));
    const trunkH = Math.floor(canvasHeight * 0.88);
    const canopyStart = Math.floor(canvasHeight * 0.42);
    const apexY = Math.max(4, Math.floor(canvasHeight * 0.08));
    const canopyH = canopyStart - apexY;

    const t1Y = canopyStart;
    const t2Y = Math.floor(canopyStart - canopyH * 0.32);
    const t3Y = Math.floor(canopyStart - canopyH * 0.65);
    const spireBaseY = Math.floor(canopyStart - canopyH * 0.82);

    lines.push(
      '# --- Semantic Layer 2: roots_and_ground ---',
      `SHAPE $r_left (LINE FROM (VEC2 (PX (SUB $cx ${Math.floor(trunkBaseW * 0.9)})) (PX (ADD $gy 1))) TO (VEC2 (PX (SUB $cx ${Math.floor(trunkBaseW * 0.3)})) (PX (SUB $gy 8))))`,
      `SHAPE $r_right (LINE FROM (VEC2 (PX (ADD $cx ${Math.floor(trunkBaseW * 0.9)})) (PX (ADD $gy 1))) TO (VEC2 (PX (ADD $cx ${Math.floor(trunkBaseW * 0.3)})) (PX (SUB $gy 8))))`,
      `SHAPE $r_mid (LINE FROM (VEC2 (PX $cx) (PX (ADD $gy 2))) TO (VEC2 (PX $cx) (PX (SUB $gy 6))))`,
      'LAYER roots_and_ground ORDER 10 {',
      '  PAINT $r_left FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_right FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_mid FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 3: trunk ---',
      `SHAPE $t_buttress (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy 5))) SIZE (VEC2 (PX ${trunkBaseW}) (PX 12)))`,
      `SHAPE $t_lower (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy 18))) SIZE (VEC2 (PX ${trunkBaseW - 3}) (PX 18)))`,
      `SHAPE $t_mid (RECT CENTER (VEC2 (PX $cx) (PX ${Math.floor((canopyStart + groundY) / 2)})) SIZE (VEC2 (PX ${trunkBaseW - 5}) (PX ${groundY - canopyStart})))`,
      `SHAPE $t_upper (RECT CENTER (VEC2 (PX $cx) (PX ${Math.floor((t3Y + canopyStart) / 2)})) SIZE (VEC2 (PX ${trunkTopW}) (PX ${canopyStart - t3Y})))`,
      `SHAPE $t_shadow (RECT CENTER (VEC2 (PX (SUB $cx ${Math.max(1, Math.floor(trunkBaseW * 0.25))})) (PX (DIV (ADD $gy 10) 2))) SIZE (VEC2 (PX 2) (PX ${trunkH})))`,
      `SHAPE $t_lit (RECT CENTER (VEC2 (PX (ADD $cx ${Math.max(1, Math.floor(trunkBaseW * 0.25))})) (PX (DIV (ADD $gy 10) 2))) SIZE (VEC2 (PX 2) (PX ${trunkH})))`,
      'LAYER trunk ORDER 20 {',
      '  PAINT $t_buttress FILL $bark_base RASTER MIDPOINT',
      '  PAINT $t_lower FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_mid FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_upper FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_shadow FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $t_lit FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 4: primary_branches ---',
      `SHAPE $b_tier1_l (LINE FROM (VEC2 (PX (SUB $cx 2)) (PX (SUB ${t1Y} 4))) TO (VEC2 (PX (SUB $cx 14)) (PX ${t1Y})))`,
      `SHAPE $b_tier1_r (LINE FROM (VEC2 (PX (ADD $cx 2)) (PX (SUB ${t1Y} 4))) TO (VEC2 (PX (ADD $cx 14)) (PX ${t1Y})))`,
      `SHAPE $b_tier2_l (LINE FROM (VEC2 (PX (SUB $cx 2)) (PX (SUB ${t2Y} 3))) TO (VEC2 (PX (SUB $cx 12)) (PX ${t2Y})))`,
      `SHAPE $b_tier2_r (LINE FROM (VEC2 (PX (ADD $cx 2)) (PX (SUB ${t2Y} 3))) TO (VEC2 (PX (ADD $cx 12)) (PX ${t2Y})))`,
      `SHAPE $b_tier3_l (LINE FROM (VEC2 (PX (SUB $cx 1)) (PX (SUB ${t3Y} 3))) TO (VEC2 (PX (SUB $cx 9)) (PX ${t3Y})))`,
      `SHAPE $b_tier3_r (LINE FROM (VEC2 (PX (ADD $cx 1)) (PX (SUB ${t3Y} 3))) TO (VEC2 (PX (ADD $cx 9)) (PX ${t3Y})))`,
      'LAYER primary_branches ORDER 30 {',
      '  PAINT $b_tier1_l FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $b_tier1_r FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $b_tier2_l FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_tier2_r FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_tier3_l FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_tier3_r FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 5: secondary_branches ---',
      `SHAPE $dr_1 (LINE FROM (VEC2 (PX (SUB $cx 14)) (PX ${t1Y})) TO (VEC2 (PX (SUB $cx 16)) (PX (ADD ${t1Y} 4))))`,
      `SHAPE $dr_2 (LINE FROM (VEC2 (PX (ADD $cx 14)) (PX ${t1Y})) TO (VEC2 (PX (ADD $cx 16)) (PX (ADD ${t1Y} 4))))`,
      `SHAPE $dr_3 (LINE FROM (VEC2 (PX (SUB $cx 12)) (PX ${t2Y})) TO (VEC2 (PX (SUB $cx 14)) (PX (ADD ${t2Y} 3))))`,
      `SHAPE $dr_4 (LINE FROM (VEC2 (PX (ADD $cx 12)) (PX ${t2Y})) TO (VEC2 (PX (ADD $cx 14)) (PX (ADD ${t2Y} 3))))`,
      'LAYER secondary_branches ORDER 40 {',
      '  PAINT $dr_1 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $dr_2 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $dr_3 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $dr_4 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 6: canopy_masses ---',
      `SHAPE $whorl1_base (RECT CENTER (VEC2 (PX $cx) (PX (ADD ${t1Y} 1))) SIZE (VEC2 (PX 28) (PX 6)))`,
      `SHAPE $whorl1_mid (RECT CENTER (VEC2 (PX $cx) (PX (SUB ${t1Y} 1))) SIZE (VEC2 (PX 24) (PX 5)))`,
      `SHAPE $whorl2_base (RECT CENTER (VEC2 (PX $cx) (PX (ADD ${t2Y} 1))) SIZE (VEC2 (PX 22) (PX 6)))`,
      `SHAPE $whorl2_mid (RECT CENTER (VEC2 (PX $cx) (PX (SUB ${t2Y} 1))) SIZE (VEC2 (PX 18) (PX 5)))`,
      `SHAPE $whorl3_base (RECT CENTER (VEC2 (PX $cx) (PX (ADD ${t3Y} 1))) SIZE (VEC2 (PX 16) (PX 5)))`,
      `SHAPE $whorl3_mid (RECT CENTER (VEC2 (PX $cx) (PX (SUB ${t3Y} 1))) SIZE (VEC2 (PX 12) (PX 4)))`,
      `SHAPE $spire_body (TRIANGLE P1 (VEC2 (PX (SUB $cx 5)) (PX ${spireBaseY})) P2 (VEC2 (PX (ADD $cx 5)) (PX ${spireBaseY})) P3 (VEC2 (PX $cx) (PX ${apexY})))`,
      'LAYER canopy_masses ORDER 50 {',
      '  PAINT $whorl1_base FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $whorl1_mid FILL $canopy_base RASTER MIDPOINT',
      '  PAINT $whorl2_base FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $whorl2_mid FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $whorl3_base FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $whorl3_mid FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $spire_body FILL $canopy_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 7: foliage_edges ---',
      `SHAPE $tip_l1 (PIXEL AT (VEC2 (PX (SUB $cx 15)) (PX (ADD ${t1Y} 2))))`,
      `SHAPE $tip_r1 (PIXEL AT (VEC2 (PX (ADD $cx 15)) (PX (ADD ${t1Y} 2))))`,
      `SHAPE $tip_l2 (PIXEL AT (VEC2 (PX (SUB $cx 12)) (PX (ADD ${t2Y} 2))))`,
      `SHAPE $tip_r2 (PIXEL AT (VEC2 (PX (ADD $cx 12)) (PX (ADD ${t2Y} 2))))`,
      `SHAPE $tip_spire (PIXEL AT (VEC2 (PX $cx) (PX (SUB ${apexY} 1))))`,
      'LAYER foliage_edges ORDER 60 {',
      '  PAINT $tip_l1 FILL $canopy_hi RASTER CENTER',
      '  PAINT $tip_r1 FILL $canopy_hi RASTER CENTER',
      '  PAINT $tip_l2 FILL $canopy_hi RASTER CENTER',
      '  PAINT $tip_r2 FILL $canopy_hi RASTER CENTER',
      '  PAINT $tip_spire FILL $canopy_hi RASTER CENTER',
      '}',
      '',
      '# --- Semantic Layer 8: surface_detail ---',
      `SHAPE $redwood_grain1 (LINE FROM (VEC2 (PX (SUB $cx 2)) (PX (SUB $gy 40))) TO (VEC2 (PX (SUB $cx 2)) (PX (SUB $gy 6))))`,
      `SHAPE $redwood_grain2 (LINE FROM (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 44))) TO (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 8))))`,
      `SHAPE $redwood_grain3 (LINE FROM (VEC2 (PX (ADD $cx 3)) (PX (SUB $gy 30))) TO (VEC2 (PX (ADD $cx 4)) (PX (SUB $gy 10))))`,
      'LAYER surface_detail ORDER 70 {',
      '  PAINT $redwood_grain1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $redwood_grain2 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $redwood_grain3 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 9: highlights ---',
      `SHAPE $spire_glint (PIXEL AT (VEC2 (PX $cx) (PX (SUB ${apexY} 2))))`,
      `SHAPE $bark_glint (PIXEL AT (VEC2 (PX (ADD $cx 3)) (PX (SUB $gy 24))))`,
      'LAYER highlights ORDER 80 {',
      '  PAINT $spire_glint FILL $canopy_spec RASTER CENTER',
      '  PAINT $bark_glint FILL $bark_lit RASTER CENTER',
      '}',
      ''
    );
  } else if (familyKey === 'pine' || envelope === 'radial_tiered') {
    // PINE: craggy trunk visible between separated tiers, radial bough whorls, spiky needle stars
    const apexY = Math.max(4, Math.floor(canvasHeight * 0.12));
    const trunkTopY = Math.max(apexY + 4, Math.floor(canvasHeight * 0.22));
    const tierSpacing = Math.floor((groundY - trunkTopY) / 4);

    lines.push(
      '# --- Semantic Layer 2: roots_and_ground ---',
      `SHAPE $r_left (LINE FROM (VEC2 (PX (SUB $cx 10)) (PX $gy)) TO (VEC2 (PX (SUB $cx 3)) (PX (SUB $gy 5))))`,
      `SHAPE $r_right (LINE FROM (VEC2 (PX (ADD $cx 10)) (PX $gy)) TO (VEC2 (PX (ADD $cx 3)) (PX (SUB $gy 5))))`,
      'LAYER roots_and_ground ORDER 10 {',
      '  PAINT $r_left FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_right FILL $bark_dark RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 3: trunk ---',
      `SHAPE $t_base (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy 6))) SIZE (VEC2 (PX 8) (PX 12)))`,
      `SHAPE $t_mid (RECT CENTER (VEC2 (PX $cx) (PX ${Math.floor((trunkTopY + groundY) / 2)})) SIZE (VEC2 (PX 6) (PX ${groundY - trunkTopY})))`,
      `SHAPE $t_sh (RECT CENTER (VEC2 (PX (SUB $cx 2)) (PX ${Math.floor((trunkTopY + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - trunkTopY})))`,
      `SHAPE $t_hi (RECT CENTER (VEC2 (PX (ADD $cx 2)) (PX ${Math.floor((trunkTopY + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - trunkTopY})))`,
      'LAYER trunk ORDER 20 {',
      '  PAINT $t_base FILL $bark_base RASTER MIDPOINT',
      '  PAINT $t_mid FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_sh FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $t_hi FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 4: primary_branches ---',
      `SHAPE $pb_1l (LINE FROM (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 1}))) TO (VEC2 (PX (SUB $cx 14)) (PX (ADD (SUB $gy ${tierSpacing * 1}) 2))))`,
      `SHAPE $pb_1r (LINE FROM (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 1}))) TO (VEC2 (PX (ADD $cx 14)) (PX (ADD (SUB $gy ${tierSpacing * 1}) 2))))`,
      `SHAPE $pb_2l (LINE FROM (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 2}))) TO (VEC2 (PX (SUB $cx 12)) (PX (ADD (SUB $gy ${tierSpacing * 2}) 1))))`,
      `SHAPE $pb_2r (LINE FROM (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 2}))) TO (VEC2 (PX (ADD $cx 12)) (PX (ADD (SUB $gy ${tierSpacing * 2}) 1))))`,
      `SHAPE $pb_3l (LINE FROM (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 3}))) TO (VEC2 (PX (SUB $cx 10)) (PX (SUB $gy ${tierSpacing * 3}))))`,
      `SHAPE $pb_3r (LINE FROM (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 3}))) TO (VEC2 (PX (ADD $cx 10)) (PX (SUB $gy ${tierSpacing * 3}))))`,
      'LAYER primary_branches ORDER 30 {',
      '  PAINT $pb_1l FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $pb_1r FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $pb_2l FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $pb_2r FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $pb_3l FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $pb_3r FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 5: secondary_branches ---',
      `SHAPE $dr_l (LINE FROM (VEC2 (PX (SUB $cx 14)) (PX (ADD (SUB $gy ${tierSpacing * 1}) 2))) TO (VEC2 (PX (SUB $cx 16)) (PX (ADD (SUB $gy ${tierSpacing * 1}) 5))))`,
      `SHAPE $dr_r (LINE FROM (VEC2 (PX (ADD $cx 14)) (PX (ADD (SUB $gy ${tierSpacing * 1}) 2))) TO (VEC2 (PX (ADD $cx 16)) (PX (ADD (SUB $gy ${tierSpacing * 1}) 5))))`,
      'LAYER secondary_branches ORDER 40 {',
      '  PAINT $dr_l FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $dr_r FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 6: canopy_masses ---',
      `SHAPE $tier1_dark (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 1}))) SIZE (VEC2 (PX 26) (PX 5)))`,
      `SHAPE $tier1_lit (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 1 + 2}))) SIZE (VEC2 (PX 22) (PX 4)))`,
      `SHAPE $tier2_dark (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 2}))) SIZE (VEC2 (PX 22) (PX 5)))`,
      `SHAPE $tier2_lit (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 2 + 2}))) SIZE (VEC2 (PX 18) (PX 4)))`,
      `SHAPE $tier3_dark (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 3}))) SIZE (VEC2 (PX 18) (PX 5)))`,
      `SHAPE $tier3_lit (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy ${tierSpacing * 3 + 2}))) SIZE (VEC2 (PX 14) (PX 4)))`,
      `SHAPE $tier_apex (TRIANGLE P1 (VEC2 (PX (SUB $cx 5)) (PX ${trunkTopY})) P2 (VEC2 (PX (ADD $cx 5)) (PX ${trunkTopY})) P3 (VEC2 (PX $cx) (PX ${apexY})))`,
      'LAYER canopy_masses ORDER 50 {',
      '  PAINT $tier1_dark FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $tier1_lit FILL $canopy_base RASTER MIDPOINT',
      '  PAINT $tier2_dark FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $tier2_lit FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $tier3_dark FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $tier3_lit FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $tier_apex FILL $canopy_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 7: foliage_edges ---',
      `SHAPE $pin_t1l (PIXEL AT (VEC2 (PX (SUB $cx 14)) (PX (SUB $gy ${tierSpacing * 1 - 1}))))`,
      `SHAPE $pin_t1r (PIXEL AT (VEC2 (PX (ADD $cx 14)) (PX (SUB $gy ${tierSpacing * 1 - 1}))))`,
      `SHAPE $pin_t2l (PIXEL AT (VEC2 (PX (SUB $cx 12)) (PX (SUB $gy ${tierSpacing * 2 - 1}))))`,
      `SHAPE $pin_t2r (PIXEL AT (VEC2 (PX (ADD $cx 12)) (PX (SUB $gy ${tierSpacing * 2 - 1}))))`,
      `SHAPE $pin_apex (PIXEL AT (VEC2 (PX $cx) (PX (SUB ${apexY} 1))))`,
      'LAYER foliage_edges ORDER 60 {',
      '  PAINT $pin_t1l FILL $canopy_hi RASTER CENTER',
      '  PAINT $pin_t1r FILL $canopy_hi RASTER CENTER',
      '  PAINT $pin_t2l FILL $canopy_hi RASTER CENTER',
      '  PAINT $pin_t2r FILL $canopy_hi RASTER CENTER',
      '  PAINT $pin_apex FILL $canopy_hi RASTER CENTER',
      '}',
      '',
      '# --- Semantic Layer 8: surface_detail ---',
      `SHAPE $pine_bark1 (LINE FROM (VEC2 (PX (SUB $cx 1)) (PX (SUB $gy 12))) TO (VEC2 (PX (SUB $cx 1)) (PX (SUB $gy 2))))`,
      `SHAPE $pine_bark2 (LINE FROM (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 26))) TO (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 16))))`,
      'LAYER surface_detail ORDER 70 {',
      '  PAINT $pine_bark1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $pine_bark2 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 9: highlights ---',
      `SHAPE $pine_glint1 (PIXEL AT (VEC2 (PX $cx) (PX (SUB ${apexY} 2))))`,
      `SHAPE $pine_glint2 (PIXEL AT (VEC2 (PX (ADD $cx 9)) (PX (SUB $gy ${tierSpacing * 2 + 2}))))`,
      'LAYER highlights ORDER 80 {',
      '  PAINT $pine_glint1 FILL $canopy_spec RASTER CENTER',
      '  PAINT $pine_glint2 FILL $canopy_spec RASTER CENTER',
      '}',
      ''
    );
  } else if (familyKey === 'cedar' || envelope === 'horizontal_terraced') {
    // CEDAR: stepped horizontal pagoda terraces, gnarled trunk, flat scale pads
    const s1Y = Math.floor(groundY - (groundY - 10) * 0.25);
    const s2Y = Math.floor(groundY - (groundY - 10) * 0.45);
    const s3Y = Math.floor(groundY - (groundY - 10) * 0.65);
    const s4Y = Math.floor(groundY - (groundY - 10) * 0.82);

    lines.push(
      '# --- Semantic Layer 2: roots_and_ground ---',
      `SHAPE $r_l (LINE FROM (VEC2 (PX (SUB $cx 12)) (PX (ADD $gy 1))) TO (VEC2 (PX (SUB $cx 3)) (PX (SUB $gy 4))))`,
      `SHAPE $r_r (LINE FROM (VEC2 (PX (ADD $cx 10)) (PX (ADD $gy 1))) TO (VEC2 (PX (ADD $cx 3)) (PX (SUB $gy 4))))`,
      'LAYER roots_and_ground ORDER 10 {',
      '  PAINT $r_l FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_r FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 3: trunk ---',
      `SHAPE $t_gnarl_base (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy 6))) SIZE (VEC2 (PX 10) (PX 12)))`,
      `SHAPE $t_gnarl_mid (RECT CENTER (VEC2 (PX (SUB $cx 1)) (PX ${Math.floor((s2Y + groundY) / 2)})) SIZE (VEC2 (PX 8) (PX ${groundY - s2Y})))`,
      `SHAPE $t_gnarl_top (RECT CENTER (VEC2 (PX (ADD $cx 1)) (PX ${Math.floor((s4Y + s2Y) / 2)})) SIZE (VEC2 (PX 6) (PX ${s2Y - s4Y})))`,
      `SHAPE $t_sh (RECT CENTER (VEC2 (PX (SUB $cx 3)) (PX ${Math.floor((s4Y + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - s4Y})))`,
      `SHAPE $t_hi (RECT CENTER (VEC2 (PX (ADD $cx 3)) (PX ${Math.floor((s4Y + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - s4Y})))`,
      'LAYER trunk ORDER 20 {',
      '  PAINT $t_gnarl_base FILL $bark_base RASTER MIDPOINT',
      '  PAINT $t_gnarl_mid FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_gnarl_top FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_sh FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $t_hi FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 4: primary_branches ---',
      `SHAPE $b_shelf1 (LINE FROM (VEC2 (PX (SUB $cx 3)) (PX ${s1Y + 2})) TO (VEC2 (PX (SUB $cx 16)) (PX ${s1Y})))`,
      `SHAPE $b_shelf2 (LINE FROM (VEC2 (PX (ADD $cx 2)) (PX ${s2Y + 2})) TO (VEC2 (PX (ADD $cx 16)) (PX ${s2Y})))`,
      `SHAPE $b_shelf3 (LINE FROM (VEC2 (PX (SUB $cx 1)) (PX ${s3Y + 2})) TO (VEC2 (PX (SUB $cx 14)) (PX ${s3Y})))`,
      `SHAPE $b_shelf4 (LINE FROM (VEC2 (PX (ADD $cx 1)) (PX ${s4Y + 2})) TO (VEC2 (PX (ADD $cx 12)) (PX ${s4Y})))`,
      'LAYER primary_branches ORDER 30 {',
      '  PAINT $b_shelf1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $b_shelf2 FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_shelf3 FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_shelf4 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 5: secondary_branches ---',
      `SHAPE $sub_s1 (LINE FROM (VEC2 (PX (SUB $cx 16)) (PX ${s1Y})) TO (VEC2 (PX (SUB $cx 20)) (PX (ADD ${s1Y} 1))))`,
      `SHAPE $sub_s2 (LINE FROM (VEC2 (PX (ADD $cx 16)) (PX ${s2Y})) TO (VEC2 (PX (ADD $cx 20)) (PX (ADD ${s2Y} 1))))`,
      'LAYER secondary_branches ORDER 40 {',
      '  PAINT $sub_s1 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $sub_s2 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 6: canopy_masses ---',
      `SHAPE $ter1_sh (RECT CENTER (VEC2 (PX (SUB $cx 11)) (PX ${s1Y})) SIZE (VEC2 (PX 18) (PX 4)))`,
      `SHAPE $ter1_lit (RECT CENTER (VEC2 (PX (SUB $cx 11)) (PX (SUB ${s1Y} 2))) SIZE (VEC2 (PX 16) (PX 3)))`,
      `SHAPE $ter2_sh (RECT CENTER (VEC2 (PX (ADD $cx 11)) (PX ${s2Y})) SIZE (VEC2 (PX 18) (PX 4)))`,
      `SHAPE $ter2_lit (RECT CENTER (VEC2 (PX (ADD $cx 11)) (PX (SUB ${s2Y} 2))) SIZE (VEC2 (PX 16) (PX 3)))`,
      `SHAPE $ter3_sh (RECT CENTER (VEC2 (PX (SUB $cx 8)) (PX ${s3Y})) SIZE (VEC2 (PX 16) (PX 4)))`,
      `SHAPE $ter3_lit (RECT CENTER (VEC2 (PX (SUB $cx 8)) (PX (SUB ${s3Y} 2))) SIZE (VEC2 (PX 14) (PX 3)))`,
      `SHAPE $ter4_top (RECT CENTER (VEC2 (PX $cx) (PX ${s4Y})) SIZE (VEC2 (PX 14) (PX 4)))`,
      'LAYER canopy_masses ORDER 50 {',
      '  PAINT $ter1_sh FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $ter1_lit FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $ter2_sh FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $ter2_lit FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $ter3_sh FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $ter3_lit FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $ter4_top FILL $canopy_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 7: foliage_edges ---',
      `SHAPE $frill_1 (LINE FROM (VEC2 (PX (SUB $cx 20)) (PX (SUB ${s1Y} 1))) TO (VEC2 (PX (SUB $cx 4)) (PX (SUB ${s1Y} 1))))`,
      `SHAPE $frill_2 (LINE FROM (VEC2 (PX (ADD $cx 4)) (PX (SUB ${s2Y} 1))) TO (VEC2 (PX (ADD $cx 20)) (PX (SUB ${s2Y} 1))))`,
      'LAYER foliage_edges ORDER 60 {',
      '  PAINT $frill_1 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $frill_2 FILL $canopy_hi RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 8: surface_detail ---',
      `SHAPE $cedar_groove (LINE FROM (VEC2 (PX $cx) (PX (SUB $gy 8))) TO (VEC2 (PX (SUB $cx 1)) (PX ${s3Y})))`,
      'LAYER surface_detail ORDER 70 {',
      '  PAINT $cedar_groove FILL $bark_dark RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 9: highlights ---',
      `SHAPE $cedar_pop (PIXEL AT (VEC2 (PX (ADD $cx 14)) (PX (SUB ${s2Y} 3))))`,
      `SHAPE $cedar_crest (PIXEL AT (VEC2 (PX $cx) (PX (SUB ${s4Y} 2))))`,
      'LAYER highlights ORDER 80 {',
      '  PAINT $cedar_pop FILL $canopy_spec RASTER CENTER',
      '  PAINT $cedar_crest FILL $canopy_spec RASTER CENTER',
      '}',
      ''
    );
  } else if (familyKey === 'evergreen' || envelope === 'dense_conical') {
    // EVERGREEN: dense conical pyramid, overlapping chevron skirts, deep under-shadow bands
    const apexY = Math.max(4, Math.floor(canvasHeight * 0.1));
    const totalSpan = groundY - apexY;
    const s1Base = Math.floor(groundY - totalSpan * 0.12);
    const s1Peak = Math.floor(groundY - totalSpan * 0.40);
    const s2Base = Math.floor(groundY - totalSpan * 0.35);
    const s2Peak = Math.floor(groundY - totalSpan * 0.65);
    const s3Base = Math.floor(groundY - totalSpan * 0.60);
    const s3Peak = Math.floor(groundY - totalSpan * 0.85);
    const spireBase = Math.floor(groundY - totalSpan * 0.80);

    lines.push(
      '# --- Semantic Layer 2: roots_and_ground ---',
      `SHAPE $r_base (RECT CENTER (VEC2 (PX $cx) (PX $gy)) SIZE (VEC2 (PX 12) (PX 4)))`,
      'LAYER roots_and_ground ORDER 10 {',
      '  PAINT $r_base FILL $bark_dark RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 3: trunk ---',
      `SHAPE $t_stub (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy 4))) SIZE (VEC2 (PX 8) (PX 8)))`,
      'LAYER trunk ORDER 20 {',
      '  PAINT $t_stub FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 4: primary_branches ---',
      `SHAPE $b_sk1_l (LINE FROM (VEC2 (PX $cx) (PX ${s1Peak})) TO (VEC2 (PX (SUB $cx 16)) (PX ${s1Base})))`,
      `SHAPE $b_sk1_r (LINE FROM (VEC2 (PX $cx) (PX ${s1Peak})) TO (VEC2 (PX (ADD $cx 16)) (PX ${s1Base})))`,
      'LAYER primary_branches ORDER 30 {',
      '  PAINT $b_sk1_l FILL $bark_base RASTER MIDPOINT',
      '  PAINT $b_sk1_r FILL $bark_base RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 5: secondary_branches ---',
      `SHAPE $b_sk2_l (LINE FROM (VEC2 (PX $cx) (PX ${s2Peak})) TO (VEC2 (PX (SUB $cx 12)) (PX ${s2Base})))`,
      `SHAPE $b_sk2_r (LINE FROM (VEC2 (PX $cx) (PX ${s2Peak})) TO (VEC2 (PX (ADD $cx 12)) (PX ${s2Base})))`,
      'LAYER secondary_branches ORDER 40 {',
      '  PAINT $b_sk2_l FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_sk2_r FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 6: canopy_masses ---',
      `SHAPE $sk1_dark (TRIANGLE P1 (VEC2 (PX (SUB $cx 18)) (PX ${s1Base})) P2 (VEC2 (PX (ADD $cx 18)) (PX ${s1Base})) P3 (VEC2 (PX $cx) (PX ${s1Peak})))`,
      `SHAPE $sk1_lit (TRIANGLE P1 (VEC2 (PX (SUB $cx 16)) (PX (SUB ${s1Base} 2))) P2 (VEC2 (PX (ADD $cx 16)) (PX (SUB ${s1Base} 2))) P3 (VEC2 (PX $cx) (PX ${s1Peak})))`,
      `SHAPE $sk2_dark (TRIANGLE P1 (VEC2 (PX (SUB $cx 14)) (PX ${s2Base})) P2 (VEC2 (PX (ADD $cx 14)) (PX ${s2Base})) P3 (VEC2 (PX $cx) (PX ${s2Peak})))`,
      `SHAPE $sk2_lit (TRIANGLE P1 (VEC2 (PX (SUB $cx 12)) (PX (SUB ${s2Base} 2))) P2 (VEC2 (PX (ADD $cx 12)) (PX (SUB ${s2Base} 2))) P3 (VEC2 (PX $cx) (PX ${s2Peak})))`,
      `SHAPE $sk3_dark (TRIANGLE P1 (VEC2 (PX (SUB $cx 10)) (PX ${s3Base})) P2 (VEC2 (PX (ADD $cx 10)) (PX ${s3Base})) P3 (VEC2 (PX $cx) (PX ${s3Peak})))`,
      `SHAPE $sk3_lit (TRIANGLE P1 (VEC2 (PX (SUB $cx 8)) (PX (SUB ${s3Base} 2))) P2 (VEC2 (PX (ADD $cx 8)) (PX (SUB ${s3Base} 2))) P3 (VEC2 (PX $cx) (PX ${s3Peak})))`,
      `SHAPE $sk_spire (TRIANGLE P1 (VEC2 (PX (SUB $cx 6)) (PX ${spireBase})) P2 (VEC2 (PX (ADD $cx 6)) (PX ${spireBase})) P3 (VEC2 (PX $cx) (PX ${apexY})))`,
      'LAYER canopy_masses ORDER 50 {',
      '  PAINT $sk1_dark FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $sk1_lit FILL $canopy_base RASTER MIDPOINT',
      '  PAINT $sk2_dark FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $sk2_lit FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $sk3_dark FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $sk3_lit FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $sk_spire FILL $canopy_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 7: foliage_edges ---',
      `SHAPE $eg_sk1_l (PIXEL AT (VEC2 (PX (SUB $cx 19)) (PX ${s1Base})))`,
      `SHAPE $eg_sk1_r (PIXEL AT (VEC2 (PX (ADD $cx 19)) (PX ${s1Base})))`,
      `SHAPE $eg_sk2_l (PIXEL AT (VEC2 (PX (SUB $cx 15)) (PX ${s2Base})))`,
      `SHAPE $eg_sk2_r (PIXEL AT (VEC2 (PX (ADD $cx 15)) (PX ${s2Base})))`,
      `SHAPE $eg_apex (PIXEL AT (VEC2 (PX $cx) (PX (SUB ${apexY} 1))))`,
      'LAYER foliage_edges ORDER 60 {',
      '  PAINT $eg_sk1_l FILL $canopy_hi RASTER CENTER',
      '  PAINT $eg_sk1_r FILL $canopy_hi RASTER CENTER',
      '  PAINT $eg_sk2_l FILL $canopy_hi RASTER CENTER',
      '  PAINT $eg_sk2_r FILL $canopy_hi RASTER CENTER',
      '  PAINT $eg_apex FILL $canopy_hi RASTER CENTER',
      '}',
      '',
      '# --- Semantic Layer 8: surface_detail ---',
      `SHAPE $frost_comb1 (LINE FROM (VEC2 (PX (SUB $cx 6)) (PX ${s2Peak})) TO (VEC2 (PX (ADD $cx 6)) (PX ${s2Peak})))`,
      `SHAPE $frost_comb2 (LINE FROM (VEC2 (PX (SUB $cx 4)) (PX ${s3Peak})) TO (VEC2 (PX (ADD $cx 4)) (PX ${s3Peak})))`,
      'LAYER surface_detail ORDER 70 {',
      '  PAINT $frost_comb1 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $frost_comb2 FILL $canopy_hi RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 9: highlights ---',
      `SHAPE $frost_star (PIXEL AT (VEC2 (PX $cx) (PX (SUB ${apexY} 2))))`,
      'LAYER highlights ORDER 80 {',
      '  PAINT $frost_star FILL $canopy_spec RASTER CENTER',
      '}',
      ''
    );
  } else if (familyKey === 'hickory' || envelope === 'oval_columnar') {
    // HICKORY: tall columnar oval crown, straight central trunk, ascending branches, vertical tufts
    const trunkTopY = Math.floor(canvasHeight * 0.32);

    lines.push(
      '# --- Semantic Layer 2: roots_and_ground ---',
      `SHAPE $r_l (LINE FROM (VEC2 (PX (SUB $cx 8)) (PX $gy)) TO (VEC2 (PX (SUB $cx 2)) (PX (SUB $gy 4))))`,
      `SHAPE $r_r (LINE FROM (VEC2 (PX (ADD $cx 8)) (PX $gy)) TO (VEC2 (PX (ADD $cx 2)) (PX (SUB $gy 4))))`,
      'LAYER roots_and_ground ORDER 10 {',
      '  PAINT $r_l FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_r FILL $bark_dark RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 3: trunk ---',
      `SHAPE $t_col (RECT CENTER (VEC2 (PX $cx) (PX ${Math.floor((trunkTopY + groundY) / 2)})) SIZE (VEC2 (PX 8) (PX ${groundY - trunkTopY})))`,
      `SHAPE $t_sh (RECT CENTER (VEC2 (PX (SUB $cx 2)) (PX ${Math.floor((trunkTopY + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - trunkTopY})))`,
      `SHAPE $t_hi (RECT CENTER (VEC2 (PX (ADD $cx 2)) (PX ${Math.floor((trunkTopY + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - trunkTopY})))`,
      'LAYER trunk ORDER 20 {',
      '  PAINT $t_col FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_sh FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $t_hi FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 4: primary_branches ---',
      `SHAPE $b_asc1_l (LINE FROM (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.62)})) TO (VEC2 (PX (SUB $cx 8)) (PX ${Math.floor(canvasHeight * 0.46)})))`,
      `SHAPE $b_asc1_r (LINE FROM (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.62)})) TO (VEC2 (PX (ADD $cx 8)) (PX ${Math.floor(canvasHeight * 0.46)})))`,
      `SHAPE $b_asc2_l (LINE FROM (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.50)})) TO (VEC2 (PX (SUB $cx 6)) (PX ${Math.floor(canvasHeight * 0.32)})))`,
      `SHAPE $b_asc2_r (LINE FROM (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.50)})) TO (VEC2 (PX (ADD $cx 6)) (PX ${Math.floor(canvasHeight * 0.32)})))`,
      'LAYER primary_branches ORDER 30 {',
      '  PAINT $b_asc1_l FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $b_asc1_r FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $b_asc2_l FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_asc2_r FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 5: secondary_branches ---',
      `SHAPE $b_tw1 (LINE FROM (VEC2 (PX (SUB $cx 8)) (PX ${Math.floor(canvasHeight * 0.46)})) TO (VEC2 (PX (SUB $cx 10)) (PX ${Math.floor(canvasHeight * 0.38)})))`,
      `SHAPE $b_tw2 (LINE FROM (VEC2 (PX (ADD $cx 8)) (PX ${Math.floor(canvasHeight * 0.46)})) TO (VEC2 (PX (ADD $cx 10)) (PX ${Math.floor(canvasHeight * 0.38)})))`,
      'LAYER secondary_branches ORDER 40 {',
      '  PAINT $b_tw1 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $b_tw2 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 6: canopy_masses ---',
      `SHAPE $c_ov_base (CIRCLE CENTER (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.50)})) RADIUS (PX 12))`,
      `SHAPE $c_ov_mid (CIRCLE CENTER (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.35)})) RADIUS (PX 11))`,
      `SHAPE $c_ov_top (CIRCLE CENTER (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.22)})) RADIUS (PX 9))`,
      `SHAPE $c_tuft_l (CIRCLE CENTER (VEC2 (PX (SUB $cx 7)) (PX ${Math.floor(canvasHeight * 0.40)})) RADIUS (PX 6))`,
      `SHAPE $c_tuft_r (CIRCLE CENTER (VEC2 (PX (ADD $cx 7)) (PX ${Math.floor(canvasHeight * 0.40)})) RADIUS (PX 6))`,
      'LAYER canopy_masses ORDER 50 {',
      '  PAINT $c_ov_base FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $c_ov_mid FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $c_ov_top FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $c_tuft_l FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $c_tuft_r FILL $canopy_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 7: foliage_edges ---',
      `SHAPE $hk_serr1 (PIXEL AT (VEC2 (PX (SUB $cx 11)) (PX ${Math.floor(canvasHeight * 0.35)})))`,
      `SHAPE $hk_serr2 (PIXEL AT (VEC2 (PX (ADD $cx 11)) (PX ${Math.floor(canvasHeight * 0.35)})))`,
      `SHAPE $hk_serr_top (PIXEL AT (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.11)})))`,
      'LAYER foliage_edges ORDER 60 {',
      '  PAINT $hk_serr1 FILL $canopy_hi RASTER CENTER',
      '  PAINT $hk_serr2 FILL $canopy_hi RASTER CENTER',
      '  PAINT $hk_serr_top FILL $canopy_hi RASTER CENTER',
      '}',
      '',
      '# --- Semantic Layer 8: surface_detail ---',
      `SHAPE $hk_diamond1 (LINE FROM (VEC2 (PX (SUB $cx 1)) (PX (SUB $gy 18))) TO (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 24))))`,
      `SHAPE $hk_diamond2 (LINE FROM (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 24))) TO (VEC2 (PX (SUB $cx 1)) (PX (SUB $gy 30))))`,
      'LAYER surface_detail ORDER 70 {',
      '  PAINT $hk_diamond1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $hk_diamond2 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 9: highlights ---',
      `SHAPE $hk_crest (PIXEL AT (VEC2 (PX $cx) (PX ${Math.floor(canvasHeight * 0.10)})))`,
      'LAYER highlights ORDER 80 {',
      '  PAINT $hk_crest FILL $canopy_spec RASTER CENTER',
      '}',
      ''
    );
  } else if (familyKey === 'maple' || envelope === 'lobed_spreading') {
    // MAPLE: spreading vase habit, multi-limbed scaffold, distinct rounded cloud-lobe pillows with deep crevices
    const crownCenterY = Math.floor(canvasHeight * 0.35);

    lines.push(
      '# --- Semantic Layer 2: roots_and_ground ---',
      `SHAPE $r_l (LINE FROM (VEC2 (PX (SUB $cx 10)) (PX $gy)) TO (VEC2 (PX (SUB $cx 3)) (PX (SUB $gy 5))))`,
      `SHAPE $r_r (LINE FROM (VEC2 (PX (ADD $cx 10)) (PX $gy)) TO (VEC2 (PX (ADD $cx 3)) (PX (SUB $gy 5))))`,
      'LAYER roots_and_ground ORDER 10 {',
      '  PAINT $r_l FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_r FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 3: trunk ---',
      `SHAPE $t_base (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy 5))) SIZE (VEC2 (PX 12) (PX 10)))`,
      `SHAPE $t_mid (RECT CENTER (VEC2 (PX $cx) (PX ${Math.floor((crownCenterY + groundY) / 2)})) SIZE (VEC2 (PX 9) (PX ${groundY - crownCenterY})))`,
      `SHAPE $t_sh (RECT CENTER (VEC2 (PX (SUB $cx 3)) (PX ${Math.floor((crownCenterY + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - crownCenterY})))`,
      `SHAPE $t_hi (RECT CENTER (VEC2 (PX (ADD $cx 3)) (PX ${Math.floor((crownCenterY + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - crownCenterY})))`,
      'LAYER trunk ORDER 20 {',
      '  PAINT $t_base FILL $bark_base RASTER MIDPOINT',
      '  PAINT $t_mid FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_sh FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $t_hi FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 4: primary_branches ---',
      `SHAPE $b_fork_l (LINE FROM (VEC2 (PX $cx) (PX ${crownCenterY + 8})) TO (VEC2 (PX (SUB $cx 14)) (PX ${crownCenterY - 4})))`,
      `SHAPE $b_fork_r (LINE FROM (VEC2 (PX $cx) (PX ${crownCenterY + 8})) TO (VEC2 (PX (ADD $cx 14)) (PX ${crownCenterY - 4})))`,
      `SHAPE $b_fork_c (LINE FROM (VEC2 (PX $cx) (PX ${crownCenterY + 6})) TO (VEC2 (PX $cx) (PX ${crownCenterY - 10})))`,
      'LAYER primary_branches ORDER 30 {',
      '  PAINT $b_fork_l FILL $bark_base RASTER MIDPOINT',
      '  PAINT $b_fork_r FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_fork_c FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 5: secondary_branches ---',
      `SHAPE $tw_ml (LINE FROM (VEC2 (PX (SUB $cx 14)) (PX ${crownCenterY - 4})) TO (VEC2 (PX (SUB $cx 18)) (PX ${crownCenterY - 12})))`,
      `SHAPE $tw_mr (LINE FROM (VEC2 (PX (ADD $cx 14)) (PX ${crownCenterY - 4})) TO (VEC2 (PX (ADD $cx 18)) (PX ${crownCenterY - 12})))`,
      'LAYER secondary_branches ORDER 40 {',
      '  PAINT $tw_ml FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $tw_mr FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 6: canopy_masses ---',
      `SHAPE $pil_bl (CIRCLE CENTER (VEC2 (PX (SUB $cx 14)) (PX ${crownCenterY + 2})) RADIUS (PX 9))`,
      `SHAPE $pil_br (CIRCLE CENTER (VEC2 (PX (ADD $cx 14)) (PX ${crownCenterY + 2})) RADIUS (PX 9))`,
      `SHAPE $pil_bc (CIRCLE CENTER (VEC2 (PX $cx) (PX ${crownCenterY})) RADIUS (PX 11))`,
      `SHAPE $pil_ml (CIRCLE CENTER (VEC2 (PX (SUB $cx 10)) (PX ${crownCenterY - 10})) RADIUS (PX 10))`,
      `SHAPE $pil_mr (CIRCLE CENTER (VEC2 (PX (ADD $cx 10)) (PX ${crownCenterY - 10})) RADIUS (PX 10))`,
      `SHAPE $pil_flank_l (CIRCLE CENTER (VEC2 (PX (SUB $cx 17)) (PX ${crownCenterY - 5})) RADIUS (PX 7))`,
      `SHAPE $pil_flank_r (CIRCLE CENTER (VEC2 (PX (ADD $cx 17)) (PX ${crownCenterY - 5})) RADIUS (PX 7))`,
      `SHAPE $pil_top (CIRCLE CENTER (VEC2 (PX $cx) (PX ${crownCenterY - 18})) RADIUS (PX 9))`,
      `SHAPE $crevice_l (CIRCLE CENTER (VEC2 (PX (SUB $cx 4)) (PX ${crownCenterY - 8})) RADIUS (PX 4))`,
      `SHAPE $crevice_r (CIRCLE CENTER (VEC2 (PX (ADD $cx 4)) (PX ${crownCenterY - 8})) RADIUS (PX 4))`,
      'LAYER canopy_masses ORDER 50 {',
      '  PAINT $pil_bl FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $pil_br FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $pil_bc FILL $canopy_base RASTER MIDPOINT',
      '  PAINT $pil_ml FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $pil_mr FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $pil_flank_l FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $pil_flank_r FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $pil_top FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $crevice_l FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $crevice_r FILL $canopy_dark RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 7: foliage_edges ---',
      `SHAPE $fe_l1 (CIRCLE CENTER (VEC2 (PX (SUB $cx 18)) (PX ${crownCenterY - 4})) RADIUS (PX 4))`,
      `SHAPE $fe_r1 (CIRCLE CENTER (VEC2 (PX (ADD $cx 18)) (PX ${crownCenterY - 4})) RADIUS (PX 4))`,
      `SHAPE $fe_l2 (CIRCLE CENTER (VEC2 (PX (SUB $cx 11)) (PX ${crownCenterY - 14})) RADIUS (PX 4))`,
      `SHAPE $fe_r2 (CIRCLE CENTER (VEC2 (PX (ADD $cx 11)) (PX ${crownCenterY - 14})) RADIUS (PX 4))`,
      `SHAPE $fe_top (CIRCLE CENTER (VEC2 (PX $cx) (PX ${crownCenterY - 22})) RADIUS (PX 4))`,
      'LAYER foliage_edges ORDER 60 {',
      '  PAINT $fe_l1 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_r1 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_l2 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_r2 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_top FILL $canopy_hi RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 8: surface_detail ---',
      `SHAPE $bark_f1 (LINE FROM (VEC2 (PX (SUB $cx 2)) (PX (SUB $gy 20))) TO (VEC2 (PX (SUB $cx 2)) (PX ${crownCenterY + 4})))`,
      `SHAPE $bark_f2 (LINE FROM (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 18))) TO (VEC2 (PX (ADD $cx 1)) (PX ${crownCenterY + 6})))`,
      `SHAPE $bark_ridge (LINE FROM (VEC2 (PX (ADD $cx 3)) (PX (SUB $gy 16))) TO (VEC2 (PX (ADD $cx 3)) (PX ${crownCenterY + 8})))`,
      'LAYER surface_detail ORDER 70 {',
      '  PAINT $bark_f1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $bark_f2 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $bark_ridge FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 9: highlights ---',
      `SHAPE $glint_top (PIXEL AT (VEC2 (PX $cx) (PX ${crownCenterY - 24})))`,
      `SHAPE $glint_tl (PIXEL AT (VEC2 (PX (SUB $cx 9)) (PX ${crownCenterY - 16})))`,
      `SHAPE $glint_tr (PIXEL AT (VEC2 (PX (ADD $cx 9)) (PX ${crownCenterY - 16})))`,
      `SHAPE $glint_r (PIXEL AT (VEC2 (PX (ADD $cx 18)) (PX ${crownCenterY - 6})))`,
      'LAYER highlights ORDER 80 {',
      '  PAINT $glint_top FILL $canopy_spec RASTER CENTER',
      '  PAINT $glint_tl FILL $canopy_spec RASTER CENTER',
      '  PAINT $glint_tr FILL $canopy_spec RASTER CENTER',
      '  PAINT $glint_r FILL $canopy_spec RASTER CENTER',
      '}',
      ''
    );
  } else {
    // DEFAULT OAK (broad_rounded): massive buttressed trunk, heavy low limbs, billowing cloud lobes, negative space
    const crownCenterY = Math.floor(canvasHeight * 0.35);

    lines.push(
      '# --- Semantic Layer 2: roots_and_ground ---',
      `SHAPE $r_l1 (LINE FROM (VEC2 (PX (SUB $cx 12)) (PX (ADD $gy 1))) TO (VEC2 (PX (SUB $cx 4)) (PX (SUB $gy 5))))`,
      `SHAPE $r_r1 (LINE FROM (VEC2 (PX (ADD $cx 12)) (PX (ADD $gy 1))) TO (VEC2 (PX (ADD $cx 4)) (PX (SUB $gy 5))))`,
      `SHAPE $r_mid (LINE FROM (VEC2 (PX (SUB $cx 1)) (PX (ADD $gy 2))) TO (VEC2 (PX $cx) (PX (SUB $gy 6))))`,
      'LAYER roots_and_ground ORDER 10 {',
      '  PAINT $r_l1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_r1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $r_mid FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 3: trunk ---',
      `SHAPE $t_base (RECT CENTER (VEC2 (PX $cx) (PX (SUB $gy 5))) SIZE (VEC2 (PX 14) (PX 10)))`,
      `SHAPE $t_mid (RECT CENTER (VEC2 (PX $cx) (PX ${Math.floor((crownCenterY + groundY) / 2)})) SIZE (VEC2 (PX 10) (PX ${groundY - crownCenterY})))`,
      `SHAPE $t_top (RECT CENTER (VEC2 (PX $cx) (PX ${crownCenterY + 4})) SIZE (VEC2 (PX 8) (PX 10)))`,
      `SHAPE $t_sh (RECT CENTER (VEC2 (PX (SUB $cx 3)) (PX ${Math.floor((crownCenterY + groundY) / 2)})) SIZE (VEC2 (PX 3) (PX ${groundY - crownCenterY})))`,
      `SHAPE $t_hi (RECT CENTER (VEC2 (PX (ADD $cx 3)) (PX ${Math.floor((crownCenterY + groundY) / 2)})) SIZE (VEC2 (PX 2) (PX ${groundY - crownCenterY})))`,
      'LAYER trunk ORDER 20 {',
      '  PAINT $t_base FILL $bark_base RASTER MIDPOINT',
      '  PAINT $t_mid FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_top FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $t_sh FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $t_hi FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 4: primary_branches ---',
      `SHAPE $b_l1 (LINE FROM (VEC2 (PX (SUB $cx 2)) (PX ${crownCenterY + 10})) TO (VEC2 (PX (SUB $cx 14)) (PX ${crownCenterY + 2})))`,
      `SHAPE $b_r1 (LINE FROM (VEC2 (PX (ADD $cx 2)) (PX ${crownCenterY + 10})) TO (VEC2 (PX (ADD $cx 14)) (PX ${crownCenterY + 2})))`,
      `SHAPE $b_c1 (LINE FROM (VEC2 (PX $cx) (PX ${crownCenterY + 6})) TO (VEC2 (PX $cx) (PX ${crownCenterY - 4})))`,
      `SHAPE $b_l2 (LINE FROM (VEC2 (PX (SUB $cx 1)) (PX ${crownCenterY + 14})) TO (VEC2 (PX (SUB $cx 16)) (PX ${crownCenterY + 8})))`,
      `SHAPE $b_r2 (LINE FROM (VEC2 (PX (ADD $cx 1)) (PX ${crownCenterY + 14})) TO (VEC2 (PX (ADD $cx 16)) (PX ${crownCenterY + 8})))`,
      'LAYER primary_branches ORDER 30 {',
      '  PAINT $b_l2 FILL $bark_base RASTER MIDPOINT',
      '  PAINT $b_r2 FILL $bark_base RASTER MIDPOINT',
      '  PAINT $b_l1 FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_r1 FILL $bark_mid RASTER MIDPOINT',
      '  PAINT $b_c1 FILL $bark_mid RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 5: secondary_branches ---',
      `SHAPE $sw_l1 (LINE FROM (VEC2 (PX (SUB $cx 14)) (PX ${crownCenterY + 2})) TO (VEC2 (PX (SUB $cx 18)) (PX ${crownCenterY - 6})))`,
      `SHAPE $sw_r1 (LINE FROM (VEC2 (PX (ADD $cx 14)) (PX ${crownCenterY + 2})) TO (VEC2 (PX (ADD $cx 18)) (PX ${crownCenterY - 6})))`,
      `SHAPE $sw_c1 (LINE FROM (VEC2 (PX $cx) (PX ${crownCenterY - 4})) TO (VEC2 (PX (SUB $cx 6)) (PX ${crownCenterY - 10})))`,
      `SHAPE $sw_c2 (LINE FROM (VEC2 (PX $cx) (PX ${crownCenterY - 4})) TO (VEC2 (PX (ADD $cx 6)) (PX ${crownCenterY - 10})))`,
      'LAYER secondary_branches ORDER 40 {',
      '  PAINT $sw_l1 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $sw_r1 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $sw_c1 FILL $bark_lit RASTER MIDPOINT',
      '  PAINT $sw_c2 FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 6: canopy_masses ---',
      `SHAPE $c_deep_l (CIRCLE CENTER (VEC2 (PX (SUB $cx 12)) (PX ${crownCenterY + 4})) RADIUS (PX 9))`,
      `SHAPE $c_deep_r (CIRCLE CENTER (VEC2 (PX (ADD $cx 12)) (PX ${crownCenterY + 4})) RADIUS (PX 9))`,
      `SHAPE $c_deep_c (CIRCLE CENTER (VEC2 (PX $cx) (PX ${crownCenterY + 1})) RADIUS (PX 11))`,
      `SHAPE $c_mid_tl (CIRCLE CENTER (VEC2 (PX (SUB $cx 8)) (PX ${crownCenterY - 6})) RADIUS (PX 10))`,
      `SHAPE $c_mid_tr (CIRCLE CENTER (VEC2 (PX (ADD $cx 8)) (PX ${crownCenterY - 6})) RADIUS (PX 10))`,
      `SHAPE $c_mid_top (CIRCLE CENTER (VEC2 (PX $cx) (PX ${crownCenterY - 11})) RADIUS (PX 9))`,
      `SHAPE $c_lit_fl (CIRCLE CENTER (VEC2 (PX (SUB $cx 14)) (PX ${crownCenterY})) RADIUS (PX 7))`,
      `SHAPE $c_lit_fr (CIRCLE CENTER (VEC2 (PX (ADD $cx 14)) (PX ${crownCenterY})) RADIUS (PX 7))`,
      `SHAPE $c_lit_fc (CIRCLE CENTER (VEC2 (PX $cx) (PX ${crownCenterY - 6})) RADIUS (PX 8))`,
      'LAYER canopy_masses ORDER 50 {',
      '  PAINT $c_deep_l FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $c_deep_r FILL $canopy_dark RASTER MIDPOINT',
      '  PAINT $c_deep_c FILL $canopy_base RASTER MIDPOINT',
      '  PAINT $c_mid_tl FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $c_mid_tr FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $c_mid_top FILL $canopy_mid RASTER MIDPOINT',
      '  PAINT $c_lit_fl FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $c_lit_fr FILL $canopy_lit RASTER MIDPOINT',
      '  PAINT $c_lit_fc FILL $canopy_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 7: foliage_edges ---',
      `SHAPE $fe_1 (CIRCLE CENTER (VEC2 (PX (SUB $cx 16)) (PX ${crownCenterY - 4})) RADIUS (PX 4))`,
      `SHAPE $fe_2 (CIRCLE CENTER (VEC2 (PX (ADD $cx 16)) (PX ${crownCenterY - 4})) RADIUS (PX 4))`,
      `SHAPE $fe_3 (CIRCLE CENTER (VEC2 (PX (SUB $cx 9)) (PX ${crownCenterY - 13})) RADIUS (PX 4))`,
      `SHAPE $fe_4 (CIRCLE CENTER (VEC2 (PX (ADD $cx 9)) (PX ${crownCenterY - 13})) RADIUS (PX 4))`,
      `SHAPE $fe_top (CIRCLE CENTER (VEC2 (PX $cx) (PX ${crownCenterY - 17})) RADIUS (PX 4))`,
      'LAYER foliage_edges ORDER 60 {',
      '  PAINT $fe_1 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_2 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_3 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_4 FILL $canopy_hi RASTER MIDPOINT',
      '  PAINT $fe_top FILL $canopy_hi RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 8: surface_detail ---',
      `SHAPE $bark_fissure1 (LINE FROM (VEC2 (PX (SUB $cx 1)) (PX (SUB $gy 24))) TO (VEC2 (PX (SUB $cx 2)) (PX (SUB $gy 4))))`,
      `SHAPE $bark_fissure2 (LINE FROM (VEC2 (PX (ADD $cx 2)) (PX (SUB $gy 22))) TO (VEC2 (PX (ADD $cx 1)) (PX (SUB $gy 6))))`,
      `SHAPE $bark_ridge (LINE FROM (VEC2 (PX (ADD $cx 4)) (PX (SUB $gy 20))) TO (VEC2 (PX (ADD $cx 4)) (PX (SUB $gy 8))))`,
      'LAYER surface_detail ORDER 70 {',
      '  PAINT $bark_fissure1 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $bark_fissure2 FILL $bark_dark RASTER MIDPOINT',
      '  PAINT $bark_ridge FILL $bark_lit RASTER MIDPOINT',
      '}',
      '',
      '# --- Semantic Layer 9: highlights ---',
      `SHAPE $glint_top (PIXEL AT (VEC2 (PX $cx) (PX ${crownCenterY - 19})))`,
      `SHAPE $glint_tl (PIXEL AT (VEC2 (PX (SUB $cx 8)) (PX ${crownCenterY - 15})))`,
      `SHAPE $glint_tr (PIXEL AT (VEC2 (PX (ADD $cx 8)) (PX ${crownCenterY - 15})))`,
      `SHAPE $glint_r (PIXEL AT (VEC2 (PX (ADD $cx 17)) (PX ${crownCenterY - 6})))`,
      'LAYER highlights ORDER 80 {',
      '  PAINT $glint_top FILL $canopy_spec RASTER CENTER',
      '  PAINT $glint_tl FILL $canopy_spec RASTER CENTER',
      '  PAINT $glint_tr FILL $canopy_spec RASTER CENTER',
      '  PAINT $glint_r FILL $canopy_spec RASTER CENTER',
      '}',
      ''
    );
  }

  const scdlSource = lines.join('\n');
  const compileResult = compileSCDLV2(scdlSource);

  return Object.freeze({
    ok: compileResult.ok,
    assetName,
    scdlSource,
    compileResult,
    layerSurfaces: compileResult.packet?.layerSurfaces || [],
    checksum128: receipt.checksum128,
  });
}
